#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/tapi-connectivity-nano-plan-services.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module tapi-connectivity-nano-plan-services.yang


class ns(object):
    hash = 370825419

    id = "http://cisco.com/ns/nso/cfp/tapi-connectivity-nano-plan-services"

    uri = "http://cisco.com/ns/nso/cfp/tapi-connectivity-nano-plan-services"

    prefix = "tapi-connectivity-nano-plan-services"

    tapi_connectivity_nano_plan_services_installed = 956363481
    tapi_connectivity_nano_plan_services_installed_ = "installed"
    tapi_connectivity_nano_plan_services_config_apply = 1554681992
    tapi_connectivity_nano_plan_services_config_apply_ = "config-apply"
