#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/core-fp-common-status-codes.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module core-fp-common-status-codes.yang


class ns(object):
    hash = 756363296

    id = "http://com/cisco/cfp-common-status-codes"

    uri = "http://com/cisco/cfp-common-status-codes"

    prefix = "cfp-common-status-codes"

    cfp_common_status_codes_code = 9025151
    cfp_common_status_codes_code_ = "code"
    cfp_common_status_codes_recommended_actions = 180304737
    cfp_common_status_codes_recommended_actions_ = "recommended-actions"
    cfp_common_status_codes_WARNING = 777626720
    cfp_common_status_codes_WARNING_ = "WARNING"
    cfp_common_status_codes_status_codes = 1805334616
    cfp_common_status_codes_status_codes_ = "status-codes"
    cfp_common_status_codes_core_function_pack = 14173825
    cfp_common_status_codes_core_function_pack_ = "core-function-pack"
    cfp_common_status_codes_severity_type_base = 228232433
    cfp_common_status_codes_severity_type_base_ = "severity-type-base"
    cfp_common_status_codes_ERROR = 2110492722
    cfp_common_status_codes_ERROR_ = "ERROR"
    cfp_common_status_codes_status_code_enum_path = 1835523920
    cfp_common_status_codes_status_code_enum_path_ = "status-code-enum-path"
    cfp_common_status_codes_reason = 565156039
    cfp_common_status_codes_reason_ = "reason"
    cfp_common_status_codes_INFO = 1021731163
    cfp_common_status_codes_INFO_ = "INFO"
    cfp_common_status_codes_name = 1998270519
    cfp_common_status_codes_name_ = "name"
    cfp_common_status_codes_category = 2142289646
    cfp_common_status_codes_category_ = "category"
    cfp_common_status_codes_status_code = 573879470
    cfp_common_status_codes_status_code_ = "status-code"
    cfp_common_status_codes_severity = 483607279
    cfp_common_status_codes_severity_ = "severity"
    cfp_common_status_codes_status_code_cfp = 1532631475
    cfp_common_status_codes_status_code_cfp_ = "status-code-cfp"
    cfp_common_status_codes_FATAL = 54493095
    cfp_common_status_codes_FATAL_ = "FATAL"
    validate_status_code_validation = "status-code-validation"
    validate_status_code_validation_py = "status-code-validation-py"
