#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/core-fp-common.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module core-fp-common.yang


class ns(object):
    hash = 1396750557

    id = "http://com/cisco/corefpcommon"

    uri = "http://com/cisco/corefpcommon"

    prefix = "core-fp-common"

    core_fp_common_dispatch_map_events = 693957350
    core_fp_common_dispatch_map_events_ = "dispatch-map-events"
    core_fp_common_path = 1002915403
    core_fp_common_path_ = "path"
    core_fp_common_rfs_node = 1384821200
    core_fp_common_rfs_node_ = "rfs-node"
    core_fp_common_cfp_common_actions = 2087901694
    core_fp_common_cfp_common_actions_ = "cfp-common-actions"
    core_fp_common_operation = 1037011282
    core_fp_common_operation_ = "operation"
    core_fp_common_valtype = 98092268
    core_fp_common_valtype_ = "valtype"
    core_fp_common_var = 2007560533
    core_fp_common_var_ = "var"
    core_fp_common_device = 617911018
    core_fp_common_device_ = "device"
    core_fp_common_device_deleted = 2
    core_fp_common_device_deleted_ = "deleted"
    core_fp_common_global_var = 255059789
    core_fp_common_global_var_ = "global-var"
    core_fp_common_value = 864367181
    core_fp_common_value_ = "value"
    core_fp_common_device_modified = 1
    core_fp_common_device_modified_ = "modified"
    core_fp_common_tenant_infrastructure = 1757718876
    core_fp_common_tenant_infrastructure_ = "tenant-infrastructure"
    core_fp_common_provider_infrastructure = 764587948
    core_fp_common_provider_infrastructure_ = "provider-infrastructure"
    core_fp_common_detail = 984599342
    core_fp_common_detail_ = "detail"
    core_fp_common_dispatch_map = 1257427000
    core_fp_common_dispatch_map_ = "dispatch-map"
    core_fp_common_device_created = 0
    core_fp_common_device_created_ = "created"
    core_fp_common_kicker_id = 1615011589
    core_fp_common_kicker_id_ = "kicker-id"
    core_fp_common_tenant = 967868883
    core_fp_common_tenant_ = "tenant"
    core_fp_common_tid = 805616318
    core_fp_common_tid_ = "tid"
    core_fp_common_ned_id = 1774190712
    core_fp_common_ned_id_ = "ned-id"
    core_fp_common_cfp_local_user = 616556511
    core_fp_common_cfp_local_user_ = "cfp-local-user"
    core_fp_common_name = 1998270519
    core_fp_common_name_ = "name"
    core_fp_common_sync_dispatch_map = 247646197
    core_fp_common_sync_dispatch_map_ = "sync-dispatch-map"
    core_fp_common_encrypted_value = 920496590
    core_fp_common_encrypted_value_ = "encrypted-value"
    core_fp_common_provider = 837826676
    core_fp_common_provider_ = "provider"
    core_fp_common_success = 87922769
    core_fp_common_success_ = "success"
    core_fp_common_rfs_dispatch_map_netconf_notification_handler = 100524093
    core_fp_common_rfs_dispatch_map_netconf_notification_handler_ = "rfs-dispatch-map-netconf-notification-handler"
    core_fp_common_auto_populate_dispatch_map = 1788365662
    core_fp_common_auto_populate_dispatch_map_ = "auto-populate-dispatch-map"
    actionpoint_rfs_dispatch_map_netconf_notification_handler = "rfs-dispatch-map-netconf-notification-handler"
    actionpoint_sync_dispatch_map = "sync-dispatch-map"
