#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/core-fp-common-template-mapper.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module core-fp-common-template-mapper.yang


class ns(object):
    hash = 1299831000

    id = "http://com/cisco/cfp-common-temp-mapper"

    uri = "http://com/cisco/cfp-common-temp-mapper"

    prefix = "cfp-common-temp-mapper"

    cfp_common_temp_mapper_service_template = 7202507
    cfp_common_temp_mapper_service_template_ = "service-template"
    cfp_common_temp_mapper_override_template = 1618824398
    cfp_common_temp_mapper_override_template_ = "override-template"
    cfp_common_temp_mapper_ignore_override_settings = 64952547
    cfp_common_temp_mapper_ignore_override_settings_ = "ignore-override-settings"
    cfp_common_temp_mapper_service_template_mapper = 1281109754
    cfp_common_temp_mapper_service_template_mapper_ = "service-template-mapper"
    cfp_common_temp_mapper_per_tenant = 2051589647
    cfp_common_temp_mapper_per_tenant_ = "per-tenant"
    cfp_common_temp_mapper_tenant = 967868883
    cfp_common_temp_mapper_tenant_ = "tenant"
    cfp_common_temp_mapper_provider = 837826676
    cfp_common_temp_mapper_provider_ = "provider"
    cfp_common_temp_mapper_per_provider = 1258956421
    cfp_common_temp_mapper_per_provider_ = "per-provider"
