#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/core-fp-release.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module core-fp-release.yang


class ns(object):
    hash = 1701587574

    id = "http://cisco.com/ns/corefp-release"

    uri = "http://cisco.com/ns/corefp-release"

    prefix = "corefp-release"

    corefp_release_git = 1023471063
    corefp_release_git_ = "git"
    corefp_release_java_version = 1246353831
    corefp_release_java_version_ = "java-version"
    corefp_release_function_pack_store = 42294361
    corefp_release_function_pack_store_ = "function-pack-store"
    corefp_release_branch = 347240058
    corefp_release_branch_ = "branch"
    corefp_release_user = 1529217067
    corefp_release_user_ = "user"
    corefp_release_host = 1711485895
    corefp_release_host_ = "host"
    corefp_release_hostname = 840214230
    corefp_release_hostname_ = "hostname"
    corefp_release_version = 1714291735
    corefp_release_version_ = "version"
    corefp_release_revision = 1794066410
    corefp_release_revision_ = "revision"
    corefp_release_depends_on_function = 585051204
    corefp_release_depends_on_function_ = "depends-on-function"
    corefp_release_date_time = 1340198733
    corefp_release_date_time_ = "date-time"
    corefp_release_ref_count = 1570024794
    corefp_release_ref_count_ = "ref-count"
    corefp_release_number = 146471600
    corefp_release_number_ = "number"
    corefp_release_package_version = 1348193950
    corefp_release_package_version_ = "package-version"
    corefp_release_build = 463955894
    corefp_release_build_ = "build"
    corefp_release_uname = 915327512
    corefp_release_uname_ = "uname"
    corefp_release_package = 1915468916
    corefp_release_package_ = "package"
    corefp_release_name = 1998270519
    corefp_release_name_ = "name"
    corefp_release_fp_installed_packages = 1082176501
    corefp_release_fp_installed_packages_ = "fp-installed-packages"
    corefp_release_file_name = 1824330763
    corefp_release_file_name_ = "file-name"
    corefp_release_nso_version = 1846849211
    corefp_release_nso_version_ = "nso-version"
    corefp_release_release = 1325681236
    corefp_release_release_ = "release"
    corefp_release_core_fp_release = 1266241932
    corefp_release_core_fp_release_ = "core-fp-release"
    corefp_release_function_pack_name = 1132003177
    corefp_release_function_pack_name_ = "function-pack-name"
    corefp_release_python_version = 492995137
    corefp_release_python_version_ = "python-version"
    corefp_release_common_packages = 654003127
    corefp_release_common_packages_ = "common-packages"
