/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/iana-crypt-hash.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.onftapi.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module iana-crypt-hash.yang */
public class ianaCryptHash extends ConfNamespace {
    public static final int hash = 1545491576;
    public int hash() {
        return ianaCryptHash.hash;
    }

    public static final String id = "_onf-tapi-nc-2.0:onf-tapi-nc-2.0#urn:ietf:params:xml:ns:yang:iana-crypt-hash";
    public String id() {
        return ianaCryptHash.id;
    }

    public static final String uri = "_onf-tapi-nc-2.0:onf-tapi-nc-2.0#urn:ietf:params:xml:ns:yang:iana-crypt-hash";
    public String uri() {
        return ianaCryptHash.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(ianaCryptHash.uri);
    }

    public static final String prefix = "ianach";
    public String prefix() {
        return ianaCryptHash.prefix;
    }

    public ianaCryptHash() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

}
