/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/ietf-ip.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.onftapi.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module ietf-ip.yang */
public class ietfIp extends ConfNamespace {
    public static final int hash = 554567954;
    public int hash() {
        return ietfIp.hash;
    }

    public static final String id = "_onf-tapi-nc-2.0:onf-tapi-nc-2.0#urn:ietf:params:xml:ns:yang:ietf-ip";
    public String id() {
        return ietfIp.id;
    }

    public static final String uri = "_onf-tapi-nc-2.0:onf-tapi-nc-2.0#urn:ietf:params:xml:ns:yang:ietf-ip";
    public String uri() {
        return ietfIp.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(ietfIp.uri);
    }

    public static final String prefix = "ip";
    public String prefix() {
        return ietfIp.prefix;
    }

    public ietfIp() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _temporary_preferred_lifetime = 1399830185;
    public static final String _temporary_preferred_lifetime_ = "temporary-preferred-lifetime";
    public static final int    _neighbor = 81789621;
    public static final String _neighbor_ = "neighbor";
    public static final int    _ipv4 = 268057062;
    public static final String _ipv4_ = "ipv4";
    public static final int    _forwarding = 1238173057;
    public static final String _forwarding_ = "forwarding";
    public static final int    _autoconf = 78817100;
    public static final String _autoconf_ = "autoconf";
    public static final int    _enabled = 197426095;
    public static final String _enabled_ = "enabled";
    public static final int    _create_global_addresses = 1061463433;
    public static final String _create_global_addresses_ = "create-global-addresses";
    public static final int    _status = 1950810920;
    public static final String _status_ = "status";
    public static final int    _state = 630973766;
    public static final String _state_ = "state";
    public static final int    _dup_addr_detect_transmits = 53367116;
    public static final String _dup_addr_detect_transmits_ = "dup-addr-detect-transmits";
    public static final int    _temporary_valid_lifetime = 710688618;
    public static final String _temporary_valid_lifetime_ = "temporary-valid-lifetime";
    public static final int    _ipv6 = 1228132394;
    public static final String _ipv6_ = "ipv6";
    public static final int    _origin = 2002579816;
    public static final String _origin_ = "origin";
    public static final int    _mtu = 1751455506;
    public static final String _mtu_ = "mtu";
    public static final int    _create_temporary_addresses = 575599870;
    public static final String _create_temporary_addresses_ = "create-temporary-addresses";
    public static final int    _is_router = 1891156201;
    public static final String _is_router_ = "is-router";
    public static final int    _subnet = 1544472008;
    public static final String _subnet_ = "subnet";
    public static final int    _ip = 1643785435;
    public static final String _ip_ = "ip";
    public static final int    _address = 1266954393;
    public static final String _address_ = "address";
    public static final int    _link_layer_address = 2084100809;
    public static final String _link_layer_address_ = "link-layer-address";
    public static final int    _prefix_length = 524393771;
    public static final String _prefix_length_ = "prefix-length";
    public static final int    _netmask = 240292132;
    public static final String _netmask_ = "netmask";
}
