/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/ietf-netconf-partial-lock.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.onftapi.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module ietf-netconf-partial-lock.yang */
public class ietfNetconfPartialLock extends ConfNamespace {
    public static final int hash = 1427669119;
    public int hash() {
        return ietfNetconfPartialLock.hash;
    }

    public static final String id = "_onf-tapi-nc-2.0:onf-tapi-nc-2.0#urn:ietf:params:xml:ns:netconf:partial-lock:1.0";
    public String id() {
        return ietfNetconfPartialLock.id;
    }

    public static final String uri = "_onf-tapi-nc-2.0:onf-tapi-nc-2.0#urn:ietf:params:xml:ns:netconf:partial-lock:1.0";
    public String uri() {
        return ietfNetconfPartialLock.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(ietfNetconfPartialLock.uri);
    }

    public static final String prefix = "pl";
    public String prefix() {
        return ietfNetconfPartialLock.prefix;
    }

    public ietfNetconfPartialLock() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _rpc_partial_lock = 1082551773;
    public static final String _rpc_partial_lock_ = "rpc-partial-lock";
    public static final int    _info = 2062105651;
    public static final String _info_ = "info";
    public static final int    _lock_id = 1218349718;
    public static final String _lock_id_ = "lock-id";
    public static final int    _result = 401396173;
    public static final String _result_ = "result";
    public static final int    _device = 617911018;
    public static final String _device_ = "device";
    public static final int    _locked_node = 228482246;
    public static final String _locked_node_ = "locked-node";
    public static final int    _rpc_partial_unlock = 101804136;
    public static final String _rpc_partial_unlock_ = "rpc-partial-unlock";
    public static final int    _name = 1998270519;
    public static final String _name_ = "name";
    public static final int    _select = 1473597411;
    public static final String _select_ = "select";
    public static final int    _partial_lock = 957776378;
    public static final String _partial_lock_ = "partial-lock";
    public static final int    _partial_unlock = 1242097148;
    public static final String _partial_unlock_ = "partial-unlock";
}
