/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/ietf-yang-push.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.onftapi.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module ietf-yang-push.yang */
public class ietfYangPush extends ConfNamespace {
    public static final int hash = 351233928;
    public int hash() {
        return ietfYangPush.hash;
    }

    public static final String id = "_onf-tapi-nc-2.0:onf-tapi-nc-2.0#urn:ietf:params:xml:ns:yang:ietf-yang-push";
    public String id() {
        return ietfYangPush.id;
    }

    public static final String uri = "_onf-tapi-nc-2.0:onf-tapi-nc-2.0#urn:ietf:params:xml:ns:yang:ietf-yang-push";
    public String uri() {
        return ietfYangPush.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(ietfYangPush.uri);
    }

    public static final String prefix = "yp";
    public String prefix() {
        return ietfYangPush.prefix;
    }

    public ietfYangPush() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _push_update = 2128440115;
    public static final String _push_update_ = "push-update";
    public static final int    _selection_filter_ref = 1041300164;
    public static final String _selection_filter_ref_ = "selection-filter-ref";
    public static final int    _excluded_change = 74302329;
    public static final String _excluded_change_ = "excluded-change";
    public static final int    _filter_failure_hint = 293424073;
    public static final String _filter_failure_hint_ = "filter-failure-hint";
    public static final int    _object_count_limit = 2075417373;
    public static final String _object_count_limit_ = "object-count-limit";
    public static final int    _on_change_sync_unsupported = 1173345710;
    public static final String _on_change_sync_unsupported_ = "on-change-sync-unsupported";
    public static final int    _update_too_big = 2146683486;
    public static final String _update_too_big_ = "update-too-big";
    public static final int    _rpc_resync_subscription = 144231830;
    public static final String _rpc_resync_subscription_ = "rpc-resync-subscription";
    public static final int    _resync_subscription = 1499347311;
    public static final String _resync_subscription_ = "resync-subscription";
    public static final int    _establish_subscription_datastore_error_info = 1301495104;
    public static final String _establish_subscription_datastore_error_info_ = "establish-subscription-datastore-error-info";
    public static final int    _kilobytes_estimate = 236910935;
    public static final String _kilobytes_estimate_ = "kilobytes-estimate";
    public static final int    _within_subscription = 1926240005;
    public static final String _within_subscription_ = "within-subscription";
    public static final int    _incomplete_update = 2095665544;
    public static final String _incomplete_update_ = "incomplete-update";
    public static final int    _target = 1914145912;
    public static final String _target_ = "target";
    public static final int    _selection_filter = 1853185168;
    public static final String _selection_filter_ = "selection-filter";
    public static final int    _operation = 1037011282;
    public static final String _operation_ = "operation";
    public static final int    _modify_subscription_datastore_error_info = 855400698;
    public static final String _modify_subscription_datastore_error_info_ = "modify-subscription-datastore-error-info";
    public static final int    _value = 864367181;
    public static final String _value_ = "value";
    public static final int    _cant_exclude = 1998745783;
    public static final String _cant_exclude_ = "cant-exclude";
    public static final int    _point = 1540270895;
    public static final String _point_ = "point";
    public static final int    _patch_id = 1325519292;
    public static final String _patch_id_ = "patch-id";
    public static final int    _no_such_subscription_resync = 985944552;
    public static final String _no_such_subscription_resync_ = "no-such-subscription-resync";
    public static final int    _periodic = 538465825;
    public static final String _periodic_ = "periodic";
    public static final int    _by_reference = 1956288752;
    public static final String _by_reference_ = "by-reference";
    public static final int    _datastore = 449538578;
    public static final String _datastore_ = "datastore";
    public static final int    _sync_too_big = 545964838;
    public static final String _sync_too_big_ = "sync-too-big";
    public static final int    _filter_id = 1126015794;
    public static final String _filter_id_ = "filter-id";
    public static final int    _datastore_contents = 1539332235;
    public static final String _datastore_contents_ = "datastore-contents";
    public static final int    _kilobytes_limit = 515966394;
    public static final String _kilobytes_limit_ = "kilobytes-limit";
    public static final int    _datastore_not_subscribable = 1154615031;
    public static final String _datastore_not_subscribable_ = "datastore-not-subscribable";
    public static final int    _object_count_estimate = 781918496;
    public static final String _object_count_estimate_ = "object-count-estimate";
    public static final int    _yang_patch = 1853535404;
    public static final String _yang_patch_ = "yang-patch";
    public static final int    _dampening_period = 1195792556;
    public static final String _dampening_period_ = "dampening-period";
    public static final int    _period_unsupported = 829940114;
    public static final String _period_unsupported_ = "period-unsupported";
    public static final int    _unchanging_selection = 917989223;
    public static final String _unchanging_selection_ = "unchanging-selection";
    public static final int    _on_change = 2098028622;
    public static final String _on_change_ = "on-change";
    public static final int    _anchor_time = 1074015300;
    public static final String _anchor_time_ = "anchor-time";
    public static final int    _edit = 1716487530;
    public static final String _edit_ = "edit";
    public static final int    _comment = 452863039;
    public static final String _comment_ = "comment";
    public static final int    _filter_spec = 354841189;
    public static final String _filter_spec_ = "filter-spec";
    public static final int    _push_change_update = 1609217786;
    public static final String _push_change_update_ = "push-change-update";
    public static final int    _reason = 565156039;
    public static final String _reason_ = "reason";
    public static final int    _period_hint = 278441174;
    public static final String _period_hint_ = "period-hint";
    public static final int    _datastore_changes = 2074868284;
    public static final String _datastore_changes_ = "datastore-changes";
    public static final int    _on_change_unsupported = 248219053;
    public static final String _on_change_unsupported_ = "on-change-unsupported";
    public static final int    _period = 1135208285;
    public static final String _period_ = "period";
    public static final int    _resync_subscription_error = 2105489835;
    public static final String _resync_subscription_error_ = "resync-subscription-error";
    public static final int    _where = 121913774;
    public static final String _where_ = "where";
    public static final int    _edit_id = 2090794113;
    public static final String _edit_id_ = "edit-id";
    public static final int    _id = 1279252765;
    public static final String _id_ = "id";
    public static final int    _datastore_subtree_filter = 91341864;
    public static final String _datastore_subtree_filter_ = "datastore-subtree-filter";
    public static final int    _update_trigger = 400709998;
    public static final String _update_trigger_ = "update-trigger";
    public static final int    _datastore_xpath_filter = 2038188293;
    public static final String _datastore_xpath_filter_ = "datastore-xpath-filter";
    public static final int    _sync_on_start = 303588629;
    public static final String _sync_on_start_ = "sync-on-start";
}
