/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/ietf-yang-metadata.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.onftapi.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module ietf-yang-metadata.yang */
public class ietfYangMetadata extends ConfNamespace {
    public static final int hash = 803647978;
    public int hash() {
        return ietfYangMetadata.hash;
    }

    public static final String id = "_onf-tapi-nc-2.0:onf-tapi-nc-2.0#urn:ietf:params:xml:ns:yang:ietf-yang-metadata";
    public String id() {
        return ietfYangMetadata.id;
    }

    public static final String uri = "_onf-tapi-nc-2.0:onf-tapi-nc-2.0#urn:ietf:params:xml:ns:yang:ietf-yang-metadata";
    public String uri() {
        return ietfYangMetadata.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(ietfYangMetadata.uri);
    }

    public static final String prefix = "md";
    public String prefix() {
        return ietfYangMetadata.prefix;
    }

    public ietfYangMetadata() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

}
