/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/ietf-netconf-with-defaults.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.onftapi.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module ietf-netconf-with-defaults.yang */
public class ietfNetconfWithDefaults extends ConfNamespace {
    public static final int hash = 1978391419;
    public int hash() {
        return ietfNetconfWithDefaults.hash;
    }

    public static final String id = "_onf-tapi-nc-2.0:onf-tapi-nc-2.0#urn:ietf:params:xml:ns:yang:ietf-netconf-with-defaults";
    public String id() {
        return ietfNetconfWithDefaults.id;
    }

    public static final String uri = "_onf-tapi-nc-2.0:onf-tapi-nc-2.0#urn:ietf:params:xml:ns:yang:ietf-netconf-with-defaults";
    public String uri() {
        return ietfNetconfWithDefaults.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(ietfNetconfWithDefaults.uri);
    }

    public static final String prefix = "ncwd";
    public String prefix() {
        return ietfNetconfWithDefaults.prefix;
    }

    public ietfNetconfWithDefaults() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _with_defaults = 951957594;
    public static final String _with_defaults_ = "with-defaults";
}
