/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/ietf-x509-cert-to-name.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.onftapi.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module ietf-x509-cert-to-name.yang */
public class ietfX509CertToName extends ConfNamespace {
    public static final int hash = 1679991348;
    public int hash() {
        return ietfX509CertToName.hash;
    }

    public static final String id = "_onf-tapi-nc-2.0:onf-tapi-nc-2.0#urn:ietf:params:xml:ns:yang:ietf-x509-cert-to-name";
    public String id() {
        return ietfX509CertToName.id;
    }

    public static final String uri = "_onf-tapi-nc-2.0:onf-tapi-nc-2.0#urn:ietf:params:xml:ns:yang:ietf-x509-cert-to-name";
    public String uri() {
        return ietfX509CertToName.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(ietfX509CertToName.uri);
    }

    public static final String prefix = "x509c2n";
    public String prefix() {
        return ietfX509CertToName.prefix;
    }

    public ietfX509CertToName() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _san_dns_name = 1792132267;
    public static final String _san_dns_name_ = "san-dns-name";
    public static final int    _specified = 983606037;
    public static final String _specified_ = "specified";
    public static final int    _common_name = 1305223065;
    public static final String _common_name_ = "common-name";
    public static final int    _cert_to_name = 1378664366;
    public static final String _cert_to_name_ = "cert-to-name";
    public static final int    _san_any = 1849606202;
    public static final String _san_any_ = "san-any";
    public static final int    _san_ip_address = 830893531;
    public static final String _san_ip_address_ = "san-ip-address";
    public static final int    _san_rfc822_name = 880194234;
    public static final String _san_rfc822_name_ = "san-rfc822-name";
}
