/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/ietf-restconf-monitoring.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.onftapi.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module ietf-restconf-monitoring.yang */
public class ietfRestconfMonitoring extends ConfNamespace {
    public static final int hash = 1533498192;
    public int hash() {
        return ietfRestconfMonitoring.hash;
    }

    public static final String id = "_onf-tapi-nc-2.0:onf-tapi-nc-2.0#urn:ietf:params:xml:ns:yang:ietf-restconf-monitoring";
    public String id() {
        return ietfRestconfMonitoring.id;
    }

    public static final String uri = "_onf-tapi-nc-2.0:onf-tapi-nc-2.0#urn:ietf:params:xml:ns:yang:ietf-restconf-monitoring";
    public String uri() {
        return ietfRestconfMonitoring.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(ietfRestconfMonitoring.uri);
    }

    public static final String prefix = "rcmon";
    public String prefix() {
        return ietfRestconfMonitoring.prefix;
    }

    public ietfRestconfMonitoring() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _stream = 1561687317;
    public static final String _stream_ = "stream";
    public static final int    _replay_support = 1991147815;
    public static final String _replay_support_ = "replay-support";
    public static final int    _streams = 1043459567;
    public static final String _streams_ = "streams";
    public static final int    _location = 1827424758;
    public static final String _location_ = "location";
    public static final int    _encoding = 180862443;
    public static final String _encoding_ = "encoding";
    public static final int    _access = 304644663;
    public static final String _access_ = "access";
    public static final int    _capabilities = 1381570067;
    public static final String _capabilities_ = "capabilities";
    public static final int    _capability = 1251322185;
    public static final String _capability_ = "capability";
    public static final int    _restconf_state = 1557343351;
    public static final String _restconf_state_ = "restconf-state";
    public static final int    _name = 1998270519;
    public static final String _name_ = "name";
    public static final int    _description = 202559156;
    public static final String _description_ = "description";
    public static final int    _replay_log_creation_time = 896118574;
    public static final String _replay_log_creation_time_ = "replay-log-creation-time";
}
