/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/ietf-restconf.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.onftapi.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module ietf-restconf.yang */
public class ietfRestconf extends ConfNamespace {
    public static final int hash = 748488482;
    public int hash() {
        return ietfRestconf.hash;
    }

    public static final String id = "_onf-tapi-nc-2.0:onf-tapi-nc-2.0#urn:ietf:params:xml:ns:yang:ietf-restconf";
    public String id() {
        return ietfRestconf.id;
    }

    public static final String uri = "_onf-tapi-nc-2.0:onf-tapi-nc-2.0#urn:ietf:params:xml:ns:yang:ietf-restconf";
    public String uri() {
        return ietfRestconf.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(ietfRestconf.uri);
    }

    public static final String prefix = "rc";
    public String prefix() {
        return ietfRestconf.prefix;
    }

    public ietfRestconf() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _error_app_tag = 174711818;
    public static final String _error_app_tag_ = "error-app-tag";
    public static final int    _error = 126243105;
    public static final String _error_ = "error";
    public static final int    _error_tag = 1676431963;
    public static final String _error_tag_ = "error-tag";
    public static final int    _error_message = 174234492;
    public static final String _error_message_ = "error-message";
    public static final int    _restconf = 1660138980;
    public static final String _restconf_ = "restconf";
    public static final int    _errors = 1226221644;
    public static final String _errors_ = "errors";
    public static final int    _error_info = 1461021182;
    public static final String _error_info_ = "error-info";
    public static final int    _error_type = 1687973556;
    public static final String _error_type_ = "error-type";
    public static final int    _data = 535242711;
    public static final String _data_ = "data";
    public static final int    _operations = 1455304325;
    public static final String _operations_ = "operations";
    public static final int    _error_path = 1862370029;
    public static final String _error_path_ = "error-path";
}
