/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/ietf-network-instance.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.onftapi.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module ietf-network-instance.yang */
public class ietfNetworkInstance extends ConfNamespace {
    public static final int hash = 472161184;
    public int hash() {
        return ietfNetworkInstance.hash;
    }

    public static final String id = "_onf-tapi-nc-2.0:onf-tapi-nc-2.0#urn:ietf:params:xml:ns:yang:ietf-network-instance";
    public String id() {
        return ietfNetworkInstance.id;
    }

    public static final String uri = "_onf-tapi-nc-2.0:onf-tapi-nc-2.0#urn:ietf:params:xml:ns:yang:ietf-network-instance";
    public String uri() {
        return ietfNetworkInstance.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(ietfNetworkInstance.uri);
    }

    public static final String prefix = "ni";
    public String prefix() {
        return ietfNetworkInstance.prefix;
    }

    public ietfNetworkInstance() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _ipv4 = 268057062;
    public static final String _ipv4_ = "ipv4";
    public static final int    _bind_ni_name = 1051667450;
    public static final String _bind_ni_name_ = "bind-ni-name";
    public static final int    _enabled = 197426095;
    public static final String _enabled_ = "enabled";
    public static final int    _vrf_root = 779580575;
    public static final String _vrf_root_ = "vrf-root";
    public static final int    _network_instance = 1958697851;
    public static final String _network_instance_ = "network-instance";
    public static final int    _error_info = 1461021182;
    public static final String _error_info_ = "error-info";
    public static final int    _ni_type = 771026435;
    public static final String _ni_type_ = "ni-type";
    public static final int    _ipv6 = 1228132394;
    public static final String _ipv6_ = "ipv6";
    public static final int    _network_instances = 1258508407;
    public static final String _network_instances_ = "network-instances";
    public static final int    _vsi_root = 2099859672;
    public static final String _vsi_root_ = "vsi-root";
    public static final int    _name = 1998270519;
    public static final String _name_ = "name";
    public static final int    _vv_root = 1535194783;
    public static final String _vv_root_ = "vv-root";
    public static final int    _bind_ni_name_failed = 197464432;
    public static final String _bind_ni_name_failed_ = "bind-ni-name-failed";
    public static final int    _interface = 221572658;
    public static final String _interface_ = "interface";
    public static final int    _root_type = 699849197;
    public static final String _root_type_ = "root-type";
    public static final int    _description = 202559156;
    public static final String _description_ = "description";
}
