/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/ietf-yang-patch.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.onftapi.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module ietf-yang-patch.yang */
public class ietfYangPatch extends ConfNamespace {
    public static final int hash = 638884508;
    public int hash() {
        return ietfYangPatch.hash;
    }

    public static final String id = "_onf-tapi-nc-2.0:onf-tapi-nc-2.0#urn:ietf:params:xml:ns:yang:ietf-yang-patch";
    public String id() {
        return ietfYangPatch.id;
    }

    public static final String uri = "_onf-tapi-nc-2.0:onf-tapi-nc-2.0#urn:ietf:params:xml:ns:yang:ietf-yang-patch";
    public String uri() {
        return ietfYangPatch.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(ietfYangPatch.uri);
    }

    public static final String prefix = "ypatch";
    public String prefix() {
        return ietfYangPatch.prefix;
    }

    public ietfYangPatch() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _error_app_tag = 174711818;
    public static final String _error_app_tag_ = "error-app-tag";
    public static final int    _error = 126243105;
    public static final String _error_ = "error";
    public static final int    _target = 1914145912;
    public static final String _target_ = "target";
    public static final int    _operation = 1037011282;
    public static final String _operation_ = "operation";
    public static final int    _edit_status_choice = 799887093;
    public static final String _edit_status_choice_ = "edit-status-choice";
    public static final int    _error_tag = 1676431963;
    public static final String _error_tag_ = "error-tag";
    public static final int    _error_message = 174234492;
    public static final String _error_message_ = "error-message";
    public static final int    _value = 864367181;
    public static final String _value_ = "value";
    public static final int    _point = 1540270895;
    public static final String _point_ = "point";
    public static final int    _patch_id = 1325519292;
    public static final String _patch_id_ = "patch-id";
    public static final int    _global_errors = 1444755275;
    public static final String _global_errors_ = "global-errors";
    public static final int    _ok = 410023581;
    public static final String _ok_ = "ok";
    public static final int    _yang_patch_status = 401006991;
    public static final String _yang_patch_status_ = "yang-patch-status";
    public static final int    _errors = 1226221644;
    public static final String _errors_ = "errors";
    public static final int    _error_info = 1461021182;
    public static final String _error_info_ = "error-info";
    public static final int    _error_type = 1687973556;
    public static final String _error_type_ = "error-type";
    public static final int    _yang_patch = 1853535404;
    public static final String _yang_patch_ = "yang-patch";
    public static final int    _global_status = 1673083135;
    public static final String _global_status_ = "global-status";
    public static final int    _edit = 1716487530;
    public static final String _edit_ = "edit";
    public static final int    _comment = 452863039;
    public static final String _comment_ = "comment";
    public static final int    _where = 121913774;
    public static final String _where_ = "where";
    public static final int    _edit_id = 2090794113;
    public static final String _edit_id_ = "edit-id";
    public static final int    _error_path = 1862370029;
    public static final String _error_path_ = "error-path";
    public static final int    _edit_status = 702369480;
    public static final String _edit_status_ = "edit-status";
}
