/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/ietf-netconf-nmda.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.onftapi.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module ietf-netconf-nmda.yang */
public class ietfNetconfNmda extends ConfNamespace {
    public static final int hash = 1844783890;
    public int hash() {
        return ietfNetconfNmda.hash;
    }

    public static final String id = "_onf-tapi-nc-2.0:onf-tapi-nc-2.0#urn:ietf:params:xml:ns:yang:ietf-netconf-nmda";
    public String id() {
        return ietfNetconfNmda.id;
    }

    public static final String uri = "_onf-tapi-nc-2.0:onf-tapi-nc-2.0#urn:ietf:params:xml:ns:yang:ietf-netconf-nmda";
    public String uri() {
        return ietfNetconfNmda.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(ietfNetconfNmda.uri);
    }

    public static final String prefix = "ncds";
    public String prefix() {
        return ietfNetconfNmda.prefix;
    }

    public ietfNetconfNmda() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _info = 2062105651;
    public static final String _info_ = "info";
    public static final int    _with_origin = 916967366;
    public static final String _with_origin_ = "with-origin";
    public static final int    _origin_filters = 621060453;
    public static final String _origin_filters_ = "origin-filters";
    public static final int    _url = 1560781157;
    public static final String _url_ = "url";
    public static final int    _result = 401396173;
    public static final String _result_ = "result";
    public static final int    _rpc_edit_data = 802788069;
    public static final String _rpc_edit_data_ = "rpc-edit-data";
    public static final int    _device = 617911018;
    public static final String _device_ = "device";
    public static final int    _origin_filter = 1819823532;
    public static final String _origin_filter_ = "origin-filter";
    public static final int    _with_defaults = 951957594;
    public static final String _with_defaults_ = "with-defaults";
    public static final int    _datastore = 449538578;
    public static final String _datastore_ = "datastore";
    public static final int    _config_filter = 629654061;
    public static final String _config_filter_ = "config-filter";
    public static final int    _default_operation = 1003120352;
    public static final String _default_operation_ = "default-operation";
    public static final int    _max_depth = 727061923;
    public static final String _max_depth_ = "max-depth";
    public static final int    _negated_origin_filter = 913057017;
    public static final String _negated_origin_filter_ = "negated-origin-filter";
    public static final int    _config = 2105663071;
    public static final String _config_ = "config";
    public static final int    _edit_data = 78643628;
    public static final String _edit_data_ = "edit-data";
    public static final int    _filter_spec = 354841189;
    public static final String _filter_spec_ = "filter-spec";
    public static final int    _name = 1998270519;
    public static final String _name_ = "name";
    public static final int    _edit_content = 417982512;
    public static final String _edit_content_ = "edit-content";
    public static final int    _get_data = 1422478860;
    public static final String _get_data_ = "get-data";
    public static final int    _data = 535242711;
    public static final String _data_ = "data";
    public static final int    _subtree_filter = 519763503;
    public static final String _subtree_filter_ = "subtree-filter";
    public static final int    _xpath_filter = 113610718;
    public static final String _xpath_filter_ = "xpath-filter";
    public static final int    _rpc_get_data = 541517833;
    public static final String _rpc_get_data_ = "rpc-get-data";
}
