/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/tailf-confd-progress.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.onftapi.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module tailf-confd-progress.yang */
public class tailfConfdProgress extends ConfNamespace {
    public static final int hash = 440762200;
    public int hash() {
        return tailfConfdProgress.hash;
    }

    public static final String id = "_onf-tapi-nc-2.0:onf-tapi-nc-2.0#http://tail-f.com/ns/confd-progress";
    public String id() {
        return tailfConfdProgress.id;
    }

    public static final String uri = "_onf-tapi-nc-2.0:onf-tapi-nc-2.0#http://tail-f.com/ns/confd-progress";
    public String uri() {
        return tailfConfdProgress.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(tailfConfdProgress.uri);
    }

    public static final String prefix = "confd-progress";
    public String prefix() {
        return tailfConfdProgress.prefix;
    }

    public tailfConfdProgress() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _debug = 189210324;
    public static final String _debug_ = "debug";
}
