/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/tailf-netconf-monitoring.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.onftapi.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module tailf-netconf-monitoring.yang */
public class tailfNetconfMonitoring extends ConfNamespace {
    public static final int hash = 587467833;
    public int hash() {
        return tailfNetconfMonitoring.hash;
    }

    public static final String id = "_onf-tapi-nc-2.0:onf-tapi-nc-2.0#http://tail-f.com/yang/netconf-monitoring";
    public String id() {
        return tailfNetconfMonitoring.id;
    }

    public static final String uri = "_onf-tapi-nc-2.0:onf-tapi-nc-2.0#http://tail-f.com/yang/netconf-monitoring";
    public String uri() {
        return tailfNetconfMonitoring.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(tailfNetconfMonitoring.uri);
    }

    public static final String prefix = "tncm";
    public String prefix() {
        return tailfNetconfMonitoring.prefix;
    }

    public tailfNetconfMonitoring() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _webui_https = 2141346136;
    public static final String _webui_https_ = "webui-https";
    public static final int    _stream = 1561687317;
    public static final String _stream_ = "stream";
    public static final int    _requested = 1485944170;
    public static final String _requested_ = "requested";
    public static final int    _replay_support = 1991147815;
    public static final String _replay_support_ = "replay-support";
    public static final int    _mode = 575893728;
    public static final String _mode_ = "mode";
    public static final int    _streams = 1043459567;
    public static final String _streams_ = "streams";
    public static final int    _locked_by_session = 916935714;
    public static final String _locked_by_session_ = "locked-by-session";
    public static final int    _created = 315396526;
    public static final String _created_ = "created";
    public static final int    _subscriber = 1781907650;
    public static final String _subscriber_ = "subscriber";
    public static final int    _rest_http = 972237299;
    public static final String _rest_http_ = "rest-http";
    public static final int    _creator = 110891526;
    public static final String _creator_ = "creator";
    public static final int    _rest_https = 468351302;
    public static final String _rest_https_ = "rest-https";
    public static final int    _files = 1813401332;
    public static final String _files_ = "files";
    public static final int    _status = 1950810920;
    public static final String _status_ = "status";
    public static final int    _transaction_id = 1239501533;
    public static final String _transaction_id_ = "transaction-id";
    public static final int    _snmp_udp = 246778175;
    public static final String _snmp_udp_ = "snmp-udp";
    public static final int    _transaction = 343661117;
    public static final String _transaction_ = "transaction";
    public static final int    _session_id = 372565948;
    public static final String _session_id_ = "session-id";
    public static final int    _context = 1600175075;
    public static final String _context_ = "context";
    public static final int    _cli_console = 2066699732;
    public static final String _cli_console_ = "cli-console";
    public static final int    _netconf_tcp = 75382026;
    public static final String _netconf_tcp_ = "netconf-tcp";
    public static final int    _lock = 95781586;
    public static final String _lock_ = "lock";
    public static final int    _transaction_lock = 1008558907;
    public static final String _transaction_lock_ = "transaction-lock";
    public static final int    _webui_http = 1877250135;
    public static final String _webui_http_ = "webui-http";
    public static final int    _cli_ssh = 1141106648;
    public static final String _cli_ssh_ = "cli-ssh";
    public static final int    _acquired = 1582012411;
    public static final String _acquired_ = "acquired";
    public static final int    _replay_log_aged_time = 1588166633;
    public static final String _replay_log_aged_time_ = "replay-log-aged-time";
    public static final int    _name = 1998270519;
    public static final String _name_ = "name";
    public static final int    _cli_tcp = 1883924901;
    public static final String _cli_tcp_ = "cli-tcp";
    public static final int    _file = 867066344;
    public static final String _file_ = "file";
    public static final int    _start_time = 84038180;
    public static final String _start_time_ = "start-time";
    public static final int    _db = 1891760492;
    public static final String _db_ = "db";
    public static final int    _id = 1279252765;
    public static final String _id_ = "id";
    public static final int    _stop_time = 397011733;
    public static final String _stop_time_ = "stop-time";
    public static final int    _description = 202559156;
    public static final String _description_ = "description";
    public static final int    _config_mode = 1428013043;
    public static final String _config_mode_ = "config-mode";
    public static final int    _replay_log_creation_time = 896118574;
    public static final String _replay_log_creation_time_ = "replay-log-creation-time";
}
