/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/tailf-netconf-with-transaction-id.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.onftapi.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module tailf-netconf-with-transaction-id.yang */
public class tailfNetconfWithTransactionId extends ConfNamespace {
    public static final int hash = 905571072;
    public int hash() {
        return tailfNetconfWithTransactionId.hash;
    }

    public static final String id = "_onf-tapi-nc-2.0:onf-tapi-nc-2.0#http://tail-f.com/ns/netconf/with-transaction-id";
    public String id() {
        return tailfNetconfWithTransactionId.id;
    }

    public static final String uri = "_onf-tapi-nc-2.0:onf-tapi-nc-2.0#http://tail-f.com/ns/netconf/with-transaction-id";
    public String uri() {
        return tailfNetconfWithTransactionId.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(tailfNetconfWithTransactionId.uri);
    }

    public static final String prefix = "wtxid";
    public String prefix() {
        return tailfNetconfWithTransactionId.prefix;
    }

    public tailfNetconfWithTransactionId() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _transaction_id = 1239501533;
    public static final String _transaction_id_ = "transaction-id";
    public static final int    _with_transaction_id = 1402897322;
    public static final String _with_transaction_id_ = "with-transaction-id";
}
