/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/tailf-netconf-transactions.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.onftapi.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module tailf-netconf-transactions.yang */
public class tailfNetconfTransactions extends ConfNamespace {
    public static final int hash = 122222200;
    public int hash() {
        return tailfNetconfTransactions.hash;
    }

    public static final String id = "_onf-tapi-nc-2.0:onf-tapi-nc-2.0#http://tail-f.com/ns/netconf/transactions/1.0";
    public String id() {
        return tailfNetconfTransactions.id;
    }

    public static final String uri = "_onf-tapi-nc-2.0:onf-tapi-nc-2.0#http://tail-f.com/ns/netconf/transactions/1.0";
    public String uri() {
        return tailfNetconfTransactions.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(tailfNetconfTransactions.uri);
    }

    public static final String prefix = "tr";
    public String prefix() {
        return tailfNetconfTransactions.prefix;
    }

    public tailfNetconfTransactions() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _start_transaction = 770915272;
    public static final String _start_transaction_ = "start-transaction";
    public static final int    _abort_transaction = 1282652494;
    public static final String _abort_transaction_ = "abort-transaction";
    public static final int    _target = 1914145912;
    public static final String _target_ = "target";
    public static final int    _rpc_commit_transaction = 979803984;
    public static final String _rpc_commit_transaction_ = "rpc-commit-transaction";
    public static final int    _prepare_transaction = 2049539308;
    public static final String _prepare_transaction_ = "prepare-transaction";
    public static final int    _rpc_start_transaction = 1354312511;
    public static final String _rpc_start_transaction_ = "rpc-start-transaction";
    public static final int    _candidate = 1374401854;
    public static final String _candidate_ = "candidate";
    public static final int    _rpc_abort_transaction = 915338716;
    public static final String _rpc_abort_transaction_ = "rpc-abort-transaction";
    public static final int    _startup = 1476781227;
    public static final String _startup_ = "startup";
    public static final int    _running = 59151599;
    public static final String _running_ = "running";
    public static final int    _commit_transaction = 1058820311;
    public static final String _commit_transaction_ = "commit-transaction";
    public static final int    _rpc_prepare_transaction = 1892808563;
    public static final String _rpc_prepare_transaction_ = "rpc-prepare-transaction";
}
