/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/tailf-common-query.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.onftapi.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module tailf-common-query.yang */
public class tailfCommonQuery extends ConfNamespace {
    public static final int hash = 2119206410;
    public int hash() {
        return tailfCommonQuery.hash;
    }

    public static final String id = "_onf-tapi-nc-2.0:onf-tapi-nc-2.0#http://tail-f.com/ns/common/query";
    public String id() {
        return tailfCommonQuery.id;
    }

    public static final String uri = "_onf-tapi-nc-2.0:onf-tapi-nc-2.0#http://tail-f.com/ns/common/query";
    public String uri() {
        return tailfCommonQuery.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(tailfCommonQuery.uri);
    }

    public static final String prefix = "tfcq";
    public String prefix() {
        return tailfCommonQuery.prefix;
    }

    public tailfCommonQuery() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

}
