/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/tailf-tls.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.onftapi.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module tailf-tls.yang */
public class tailfTls extends ConfNamespace {
    public static final int hash = 1263973932;
    public int hash() {
        return tailfTls.hash;
    }

    public static final String id = "_onf-tapi-nc-2.0:onf-tapi-nc-2.0#http://tail-f.com/ns/tls";
    public String id() {
        return tailfTls.id;
    }

    public static final String uri = "_onf-tapi-nc-2.0:onf-tapi-nc-2.0#http://tail-f.com/ns/tls";
    public String uri() {
        return tailfTls.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(tailfTls.uri);
    }

    public static final String prefix = "tls";
    public String prefix() {
        return tailfTls.prefix;
    }

    public tailfTls() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _fingerprint = 108417654;
    public static final String _fingerprint_ = "fingerprint";
    public static final int    _key_data = 569544672;
    public static final String _key_data_ = "key-data";
    public static final int    _cacert_data = 1945638180;
    public static final String _cacert_data_ = "cacert-data";
    public static final int    _private_key = 1861699066;
    public static final String _private_key_ = "private-key";
    public static final int    _cert_data = 1172136175;
    public static final String _cert_data_ = "cert-data";
    public static final int    _certificate = 929395308;
    public static final String _certificate_ = "certificate";
    public static final int    _ca_certificates = 1128068089;
    public static final String _ca_certificates_ = "ca-certificates";
    public static final int    _passphrase = 1150200592;
    public static final String _passphrase_ = "passphrase";
    public static final int    _tls_container = 1160896511;
    public static final String _tls_container_ = "tls";
    public static final int    _name = 1998270519;
    public static final String _name_ = "name";
}
