/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/tailf-rollback.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.onftapi.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module tailf-rollback.yang */
public class tailfRollback extends ConfNamespace {
    public static final int hash = 1497214267;
    public int hash() {
        return tailfRollback.hash;
    }

    public static final String id = "_onf-tapi-nc-2.0:onf-tapi-nc-2.0#http://tail-f.com/ns/rollback";
    public String id() {
        return tailfRollback.id;
    }

    public static final String uri = "_onf-tapi-nc-2.0:onf-tapi-nc-2.0#http://tail-f.com/ns/rollback";
    public String uri() {
        return tailfRollback.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(tailfRollback.uri);
    }

    public static final String prefix = "rollback";
    public String prefix() {
        return tailfRollback.prefix;
    }

    public tailfRollback() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _path = 1002915403;
    public static final String _path_ = "path";
    public static final int    _creator = 110891526;
    public static final String _creator_ = "creator";
    public static final int    _rollback = 1666440862;
    public static final String _rollback_ = "rollback";
    public static final int    _rollback_files = 110392016;
    public static final String _rollback_files_ = "rollback-files";
    public static final int    _content = 1400276169;
    public static final String _content_ = "content";
    public static final int    _selective = 573448511;
    public static final String _selective_ = "selective";
    public static final int    _apply_rollback_file = 1958997142;
    public static final String _apply_rollback_file_ = "apply-rollback-file";
    public static final int    _comment = 452863039;
    public static final String _comment_ = "comment";
    public static final int    _get_rollback_file = 1216164084;
    public static final String _get_rollback_file_ = "get-rollback-file";
    public static final int    _date = 2125704837;
    public static final String _date_ = "date";
    public static final int    _via = 1211954281;
    public static final String _via_ = "via";
    public static final int    _name = 1998270519;
    public static final String _name_ = "name";
    public static final int    _fixed_number = 1086290328;
    public static final String _fixed_number_ = "fixed-number";
    public static final int    _file = 867066344;
    public static final String _file_ = "file";
    public static final int    _id = 1279252765;
    public static final String _id_ = "id";
    public static final int    _label = 1570796500;
    public static final String _label_ = "label";
}
