/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/tailf-netconf-inactive.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.onftapi.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module tailf-netconf-inactive.yang */
public class tailfNetconfInactive extends ConfNamespace {
    public static final int hash = 952939550;
    public int hash() {
        return tailfNetconfInactive.hash;
    }

    public static final String id = "_onf-tapi-nc-2.0:onf-tapi-nc-2.0#http://tail-f.com/ns/netconf/inactive/1.0";
    public String id() {
        return tailfNetconfInactive.id;
    }

    public static final String uri = "_onf-tapi-nc-2.0:onf-tapi-nc-2.0#http://tail-f.com/ns/netconf/inactive/1.0";
    public String uri() {
        return tailfNetconfInactive.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(tailfNetconfInactive.uri);
    }

    public static final String prefix = "in";
    public String prefix() {
        return tailfNetconfInactive.prefix;
    }

    public tailfNetconfInactive() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _with_inactive = 439733113;
    public static final String _with_inactive_ = "with-inactive";
}
