/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/tailf-netconf-extensions.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.onftapi.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module tailf-netconf-extensions.yang */
public class tailfNetconfExtensions extends ConfNamespace {
    public static final int hash = 1335581562;
    public int hash() {
        return tailfNetconfExtensions.hash;
    }

    public static final String id = "_onf-tapi-nc-2.0:onf-tapi-nc-2.0#http://tail-f.com/ns/netconf/extensions";
    public String id() {
        return tailfNetconfExtensions.id;
    }

    public static final String uri = "_onf-tapi-nc-2.0:onf-tapi-nc-2.0#http://tail-f.com/ns/netconf/extensions";
    public String uri() {
        return tailfNetconfExtensions.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(tailfNetconfExtensions.uri);
    }

    public static final String prefix = "tfnce";
    public String prefix() {
        return tailfNetconfExtensions.prefix;
    }

    public tailfNetconfExtensions() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _has_children = 907427716;
    public static final String _has_children_ = "has-children";
    public static final int    _path = 1002915403;
    public static final String _path_ = "path";
    public static final int    _info = 2062105651;
    public static final String _info_ = "info";
    public static final int    _rpc_has_children = 980578736;
    public static final String _rpc_has_children_ = "rpc-has-children";
    public static final int    _trace_id = 1065151221;
    public static final String _trace_id_ = "trace-id";
    public static final int    _result = 401396173;
    public static final String _result_ = "result";
    public static final int    _device = 617911018;
    public static final String _device_ = "device";
    public static final int    _get_attributes = 1707479010;
    public static final String _get_attributes_ = "get-attributes";
    public static final int    _rpc_get_attributes = 1107808283;
    public static final String _rpc_get_attributes_ = "rpc-get-attributes";
    public static final int    _name = 1998270519;
    public static final String _name_ = "name";
    public static final int    _wait_time = 67539421;
    public static final String _wait_time_ = "wait-time";
}
