/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/tailf-aaa.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.onftapi.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module tailf-aaa.yang */
public class tailfAaa extends ConfNamespace {
    public static final int hash = 78910849;
    public int hash() {
        return tailfAaa.hash;
    }

    public static final String id = "_onf-tapi-nc-2.0:onf-tapi-nc-2.0#http://tail-f.com/ns/aaa/1.1";
    public String id() {
        return tailfAaa.id;
    }

    public static final String uri = "_onf-tapi-nc-2.0:onf-tapi-nc-2.0#http://tail-f.com/ns/aaa/1.1";
    public String uri() {
        return tailfAaa.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(tailfAaa.uri);
    }

    public static final String prefix = "aaa";
    public String prefix() {
        return tailfAaa.prefix;
    }

    public tailfAaa() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _prompt1 = 629040938;
    public static final String _prompt1_ = "prompt1";
    public static final int    _authentication = 838318934;
    public static final String _authentication_ = "authentication";
    public static final int    _complete_on_space = 1202435066;
    public static final String _complete_on_space_ = "complete-on-space";
    public static final int    _aaa = 2073600231;
    public static final String _aaa_ = "aaa";
    public static final int    _mode = 575893728;
    public static final String _mode_ = "mode";
    public static final int    _prompt2 = 513332017;
    public static final String _prompt2_ = "prompt2";
    public static final int    _change_password = 387358815;
    public static final String _change_password_ = "change-password";
    public static final int    _new_password = 842025097;
    public static final String _new_password_ = "new-password";
    public static final int    _command = 36215204;
    public static final String _command_ = "command";
    public static final int    _user = 1529217067;
    public static final String _user_ = "user";
    public static final int    _users = 987101583;
    public static final String _users_ = "users";
    public static final int    _display_level = 125770194;
    public static final String _display_level_ = "display-level";
    public static final int    _uid = 1587813883;
    public static final String _uid_ = "uid";
    public static final int    _password = 880727685;
    public static final String _password_ = "password";
    public static final int    _show_defaults = 1036396876;
    public static final String _show_defaults_ = "show-defaults";
    public static final int    _ios = 937667110;
    public static final String _ios_ = "ios";
    public static final int    _confirm_password = 2124963869;
    public static final String _confirm_password_ = "confirm-password";
    public static final int    _prompt = 1796253006;
    public static final String _prompt_ = "prompt";
    public static final int    _autowizard = 1810157643;
    public static final String _autowizard_ = "autowizard";
    public static final int    _homedir = 1609979376;
    public static final String _homedir_ = "homedir";
    public static final int    _devtools = 898584616;
    public static final String _devtools_ = "devtools";
    public static final int    _alias = 159608788;
    public static final String _alias_ = "alias";
    public static final int    _old_password = 945833963;
    public static final String _old_password_ = "old-password";
    public static final int    _idle_timeout = 1670649975;
    public static final String _idle_timeout_ = "idle-timeout";
    public static final int    _expansion = 1432673402;
    public static final String _expansion_ = "expansion";
    public static final int    _ssh_keydir = 825792753;
    public static final String _ssh_keydir_ = "ssh_keydir";
    public static final int    _history = 919502929;
    public static final String _history_ = "history";
    public static final int    _name = 1998270519;
    public static final String _name_ = "name";
    public static final int    _paginate = 570813703;
    public static final String _paginate_ = "paginate";
    public static final int    _session = 1896174846;
    public static final String _session_ = "session";
    public static final int    _gid = 1021704153;
    public static final String _gid_ = "gid";
    public static final int    _nr = 1926304974;
    public static final String _nr_ = "nr";
    public static final int    _privilege = 280620355;
    public static final String _privilege_ = "privilege";
    public static final int    _secret = 1322085478;
    public static final String _secret_ = "secret";
    public static final int    _level = 2112619197;
    public static final String _level_ = "level";
    public static final int    _description = 202559156;
    public static final String _description_ = "description";
    public static final int    _ignore_leading_space = 372367741;
    public static final String _ignore_leading_space_ = "ignore-leading-space";
}
