/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/tailf-ned-id-onf-tapi-nc-2.0.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.onftapi.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module tailf-ned-id-onf-tapi-nc-2.0.yang */
public class tailfNedIdOnfTapiNc2_0 extends ConfNamespace {
    public static final int hash = 1779461127;
    public int hash() {
        return tailfNedIdOnfTapiNc2_0.hash;
    }

    public static final String id = "http://tail-f.com/ns/ned-id/onf-tapi-nc-2.0";
    public String id() {
        return tailfNedIdOnfTapiNc2_0.id;
    }

    public static final String uri = "http://tail-f.com/ns/ned-id/onf-tapi-nc-2.0";
    public String uri() {
        return tailfNedIdOnfTapiNc2_0.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(tailfNedIdOnfTapiNc2_0.uri);
    }

    public static final String prefix = "onf-tapi-nc-2.0";
    public String prefix() {
        return tailfNedIdOnfTapiNc2_0.prefix;
    }

    public tailfNedIdOnfTapiNc2_0() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _onf_tapi_nc_20x2e0 = 2118563282;
    public static final String _onf_tapi_nc_20x2e0_ = "onf-tapi-nc-2.0";
}
