/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/tailf-netconf-query.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.onftapi.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module tailf-netconf-query.yang */
public class tailfNetconfQuery extends ConfNamespace {
    public static final int hash = 1226912411;
    public int hash() {
        return tailfNetconfQuery.hash;
    }

    public static final String id = "_onf-tapi-nc-2.0:onf-tapi-nc-2.0#http://tail-f.com/ns/netconf/query";
    public String id() {
        return tailfNetconfQuery.id;
    }

    public static final String uri = "_onf-tapi-nc-2.0:onf-tapi-nc-2.0#http://tail-f.com/ns/netconf/query";
    public String uri() {
        return tailfNetconfQuery.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(tailfNetconfQuery.uri);
    }

    public static final String prefix = "tfncq";
    public String prefix() {
        return tailfNetconfQuery.prefix;
    }

    public tailfNetconfQuery() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _rpc_immediate_query = 1217725246;
    public static final String _rpc_immediate_query_ = "rpc-immediate-query";
    public static final int    _path = 1002915403;
    public static final String _path_ = "path";
    public static final int    _info = 2062105651;
    public static final String _info_ = "info";
    public static final int    _result = 401396173;
    public static final String _result_ = "result";
    public static final int    _rpc_start_query = 1753216580;
    public static final String _rpc_start_query_ = "rpc-start-query";
    public static final int    _reset_query = 1223114487;
    public static final String _reset_query_ = "reset-query";
    public static final int    _device = 617911018;
    public static final String _device_ = "device";
    public static final int    _timeout = 614210192;
    public static final String _timeout_ = "timeout";
    public static final int    _value = 864367181;
    public static final String _value_ = "value";
    public static final int    _stop_query = 1335172000;
    public static final String _stop_query_ = "stop-query";
    public static final int    _foreach = 2052892262;
    public static final String _foreach_ = "foreach";
    public static final int    _fetch_query_result = 1276818724;
    public static final String _fetch_query_result_ = "fetch-query-result";
    public static final int    _rpc_reset_query = 1232203757;
    public static final String _rpc_reset_query_ = "rpc-reset-query";
    public static final int    _query_handle = 144584952;
    public static final String _query_handle_ = "query-handle";
    public static final int    _result_type = 565147987;
    public static final String _result_type_ = "result-type";
    public static final int    _query_result = 1542295748;
    public static final String _query_result_ = "query-result";
    public static final int    _limit = 1553282341;
    public static final String _limit_ = "limit";
    public static final int    _inline = 1987224790;
    public static final String _inline_ = "inline";
    public static final int    _rpc_fetch_query_result = 484654965;
    public static final String _rpc_fetch_query_result_ = "rpc-fetch-query-result";
    public static final int    _name = 1998270519;
    public static final String _name_ = "name";
    public static final int    _select = 1473597411;
    public static final String _select_ = "select";
    public static final int    _rpc_stop_query = 1755959753;
    public static final String _rpc_stop_query_ = "rpc-stop-query";
    public static final int    _data = 535242711;
    public static final String _data_ = "data";
    public static final int    _immediate_query = 1062477817;
    public static final String _immediate_query_ = "immediate-query";
    public static final int    _start_query = 1194651801;
    public static final String _start_query_ = "start-query";
    public static final int    _path_value = 480213734;
    public static final String _path_value_ = "path-value";
    public static final int    _sort_by = 2079244141;
    public static final String _sort_by_ = "sort-by";
    public static final int    _select_result = 1142952441;
    public static final String _select_result_ = "select-result";
    public static final int    _expression = 196994102;
    public static final String _expression_ = "expression";
    public static final int    _label = 1570796500;
    public static final String _label_ = "label";
    public static final int    _offset = 1966490361;
    public static final String _offset_ = "offset";
}
