/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/tailf-webui.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.onftapi.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module tailf-webui.yang */
public class tailfWebui extends ConfNamespace {
    public static final int hash = 1212412867;
    public int hash() {
        return tailfWebui.hash;
    }

    public static final String id = "_onf-tapi-nc-2.0:onf-tapi-nc-2.0#http://tail-f.com/ns/webui";
    public String id() {
        return tailfWebui.id;
    }

    public static final String uri = "_onf-tapi-nc-2.0:onf-tapi-nc-2.0#http://tail-f.com/ns/webui";
    public String uri() {
        return tailfWebui.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(tailfWebui.uri);
    }

    public static final String prefix = "webui";
    public String prefix() {
        return tailfWebui.prefix;
    }

    public tailfWebui() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _list_path = 847214750;
    public static final String _list_path_ = "list-path";
    public static final int    _z_index = 602022078;
    public static final String _z_index_ = "z-index";
    public static final int    _profile = 1538168517;
    public static final String _profile_ = "profile";
    public static final int    _data_store = 340295689;
    public static final String _data_store_ = "data-store";
    public static final int    _value = 864367181;
    public static final String _value_ = "value";
    public static final int    _asset_type = 753992187;
    public static final String _asset_type_ = "asset-type";
    public static final int    _width = 1724310388;
    public static final String _width_ = "width";
    public static final int    _data_stores = 943355165;
    public static final String _data_stores_ = "data-stores";
    public static final int    _type = 2040883914;
    public static final String _type_ = "type";
    public static final int    _username = 870658415;
    public static final String _username_ = "username";
    public static final int    _component_type = 1275398985;
    public static final String _component_type_ = "component-type";
    public static final int    _left = 1845064683;
    public static final String _left_ = "left";
    public static final int    _height = 721582793;
    public static final String _height_ = "height";
    public static final int    _assets = 2007970714;
    public static final String _assets_ = "assets";
    public static final int    _key = 1348858669;
    public static final String _key_ = "key";
    public static final int    _base_64_image = 1234075651;
    public static final String _base_64_image_ = "base-64-image";
    public static final int    _components = 962606743;
    public static final String _components_ = "components";
    public static final int    _asset = 37078947;
    public static final String _asset_ = "asset";
    public static final int    _text = 361183530;
    public static final String _text_ = "text";
    public static final int    _properties = 1953873399;
    public static final String _properties_ = "properties";
    public static final int    _name = 1998270519;
    public static final String _name_ = "name";
    public static final int    _title = 110890495;
    public static final String _title_ = "title";
    public static final int    _user_profile = 1502841590;
    public static final String _user_profile_ = "user-profile";
    public static final int    _component = 1543026623;
    public static final String _component_ = "component";
    public static final int    _top = 703743881;
    public static final String _top_ = "top";
    public static final int    _link = 481374722;
    public static final String _link_ = "link";
    public static final int    _serialized_query = 345701342;
    public static final String _serialized_query_ = "serialized-query";
    public static final int    _panel = 2033856956;
    public static final String _panel_ = "panel";
    public static final int    _saved_query = 1451816574;
    public static final String _saved_query_ = "saved-query";
    public static final int    _panels = 915136013;
    public static final String _panels_ = "panels";
    public static final int    _id = 1279252765;
    public static final String _id_ = "id";
    public static final int    _webui = 1476667922;
    public static final String _webui_ = "webui";
    public static final int    _image = 1283093902;
    public static final String _image_ = "image";
    public static final int    _description = 202559156;
    public static final String _description_ = "description";
    public static final int    _schematics = 766670971;
    public static final String _schematics_ = "schematics";
}
