/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/tailf-netconf-forward.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.onftapi.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module tailf-netconf-forward.yang */
public class tailfNetconfForward extends ConfNamespace {
    public static final int hash = 655662875;
    public int hash() {
        return tailfNetconfForward.hash;
    }

    public static final String id = "_onf-tapi-nc-2.0:onf-tapi-nc-2.0#http://tail-f.com/ns/netconf/forward/1.0";
    public String id() {
        return tailfNetconfForward.id;
    }

    public static final String uri = "_onf-tapi-nc-2.0:onf-tapi-nc-2.0#http://tail-f.com/ns/netconf/forward/1.0";
    public String uri() {
        return tailfNetconfForward.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(tailfNetconfForward.uri);
    }

    public static final String prefix = "fwd";
    public String prefix() {
        return tailfNetconfForward.prefix;
    }

    public tailfNetconfForward() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _rpc_forward = 1214942383;
    public static final String _rpc_forward_ = "rpc-forward";
    public static final int    _info = 2062105651;
    public static final String _info_ = "info";
    public static final int    _temporary_auth_failure = 944734092;
    public static final String _temporary_auth_failure_ = "temporary-auth-failure";
    public static final int    _forward = 228029135;
    public static final String _forward_ = "forward";
    public static final int    _challenge_response = 876635225;
    public static final String _challenge_response_ = "challenge-response";
    public static final int    _rpc_challenge_response = 206872506;
    public static final String _rpc_challenge_response_ = "rpc-challenge-response";
    public static final int    _error = 126243105;
    public static final String _error_ = "error";
    public static final int    _mechanism = 2003451367;
    public static final String _mechanism_ = "mechanism";
    public static final int    _connection_failure = 603012695;
    public static final String _connection_failure_ = "connection-failure";
    public static final int    _result = 401396173;
    public static final String _result_ = "result";
    public static final int    _invalid_mechanism = 1338074409;
    public static final String _invalid_mechanism_ = "invalid-mechanism";
    public static final int    _target = 1914145912;
    public static final String _target_ = "target";
    public static final int    _device = 617911018;
    public static final String _device_ = "device";
    public static final int    _not_authorized = 613918215;
    public static final String _not_authorized_ = "not-authorized";
    public static final int    _challenge = 1414041551;
    public static final String _challenge_ = "challenge";
    public static final int    _incorrect_encoding = 853274989;
    public static final String _incorrect_encoding_ = "incorrect-encoding";
    public static final int    _capabilities = 1381570067;
    public static final String _capabilities_ = "capabilities";
    public static final int    _capability = 1251322185;
    public static final String _capability_ = "capability";
    public static final int    _initial_response = 890592954;
    public static final String _initial_response_ = "initial-response";
    public static final int    _mechanism_too_weak = 882081729;
    public static final String _mechanism_too_weak_ = "mechanism-too-weak";
    public static final int    _response = 1363637576;
    public static final String _response_ = "response";
    public static final int    _reason = 565156039;
    public static final String _reason_ = "reason";
    public static final int    _connected = 1024392365;
    public static final String _connected_ = "connected";
    public static final int    _invalid_authzid = 1294980980;
    public static final String _invalid_authzid_ = "invalid-authzid";
    public static final int    _name = 1998270519;
    public static final String _name_ = "name";
    public static final int    _sasl_failure = 766737558;
    public static final String _sasl_failure_ = "sasl-failure";
    public static final int    _sasl_authentication_needed = 1978663406;
    public static final String _sasl_authentication_needed_ = "sasl-authentication-needed";
    public static final int    _mechanisms = 145873396;
    public static final String _mechanisms_ = "mechanisms";
    public static final int    _auth = 2093501109;
    public static final String _auth_ = "auth";
    public static final int    _failure = 1833033127;
    public static final String _failure_ = "failure";
}
