/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/tailf-netconf-with-rollback-id.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.onftapi.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module tailf-netconf-with-rollback-id.yang */
public class tailfNetconfWithRollbackId extends ConfNamespace {
    public static final int hash = 1894472223;
    public int hash() {
        return tailfNetconfWithRollbackId.hash;
    }

    public static final String id = "_onf-tapi-nc-2.0:onf-tapi-nc-2.0#http://tail-f.com/ns/netconf/with-rollback-id";
    public String id() {
        return tailfNetconfWithRollbackId.id;
    }

    public static final String uri = "_onf-tapi-nc-2.0:onf-tapi-nc-2.0#http://tail-f.com/ns/netconf/with-rollback-id";
    public String uri() {
        return tailfNetconfWithRollbackId.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(tailfNetconfWithRollbackId.uri);
    }

    public static final String prefix = "wrbid";
    public String prefix() {
        return tailfNetconfWithRollbackId.prefix;
    }

    public tailfNetconfWithRollbackId() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _with_rollback_id = 607504166;
    public static final String _with_rollback_id_ = "with-rollback-id";
    public static final int    _rollback = 1666440862;
    public static final String _rollback_ = "rollback";
    public static final int    _fixed_number = 1086290328;
    public static final String _fixed_number_ = "fixed-number";
    public static final int    _id = 1279252765;
    public static final String _id_ = "id";
}
