/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/tailf-acm.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.onftapi.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module tailf-acm.yang */
public class tailfAcm extends ConfNamespace {
    public static final int hash = 1747215326;
    public int hash() {
        return tailfAcm.hash;
    }

    public static final String id = "_onf-tapi-nc-2.0:onf-tapi-nc-2.0#http://tail-f.com/yang/acm";
    public String id() {
        return tailfAcm.id;
    }

    public static final String uri = "_onf-tapi-nc-2.0:onf-tapi-nc-2.0#http://tail-f.com/yang/acm";
    public String uri() {
        return tailfAcm.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(tailfAcm.uri);
    }

    public static final String prefix = "tacm";
    public String prefix() {
        return tailfAcm.prefix;
    }

    public tailfAcm() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _access_operations = 1622834780;
    public static final String _access_operations_ = "access-operations";
    public static final int    _command = 36215204;
    public static final String _command_ = "command";
    public static final int    _cmd_exec_default = 311962167;
    public static final String _cmd_exec_default_ = "cmd-exec-default";
    public static final int    _context = 1600175075;
    public static final String _context_ = "context";
    public static final int    _comment = 452863039;
    public static final String _comment_ = "comment";
    public static final int    _cmdrule = 367587804;
    public static final String _cmdrule_ = "cmdrule";
    public static final int    _name = 1998270519;
    public static final String _name_ = "name";
    public static final int    _gid = 1021704153;
    public static final String _gid_ = "gid";
    public static final int    _log_if_permit = 825727182;
    public static final String _log_if_permit_ = "log-if-permit";
    public static final int    _cmd_read_default = 1843143316;
    public static final String _cmd_read_default_ = "cmd-read-default";
    public static final int    _action = 571883887;
    public static final String _action_ = "action";
    public static final int    _log_if_default_permit = 977181334;
    public static final String _log_if_default_permit_ = "log-if-default-permit";
}
