/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/tailf-common-monitoring.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.onftapi.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module tailf-common-monitoring.yang */
public class tailfCommonMonitoring extends ConfNamespace {
    public static final int hash = 1302859148;
    public int hash() {
        return tailfCommonMonitoring.hash;
    }

    public static final String id = "_onf-tapi-nc-2.0:onf-tapi-nc-2.0#http://tail-f.com/yang/common-monitoring";
    public String id() {
        return tailfCommonMonitoring.id;
    }

    public static final String uri = "_onf-tapi-nc-2.0:onf-tapi-nc-2.0#http://tail-f.com/yang/common-monitoring";
    public String uri() {
        return tailfCommonMonitoring.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(tailfCommonMonitoring.uri);
    }

    public static final String prefix = "tfcg";
    public String prefix() {
        return tailfCommonMonitoring.prefix;
    }

    public tailfCommonMonitoring() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

}
