/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/tailf-ned-id-onf-tapi-nc.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.onftapi.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module tailf-ned-id-onf-tapi-nc.yang */
public class tailfNedIdOnfTapiNc extends ConfNamespace {
    public static final int hash = 719297921;
    public int hash() {
        return tailfNedIdOnfTapiNc.hash;
    }

    public static final String id = "http://tail-f.com/ns/ned-id/onf-tapi-nc";
    public String id() {
        return tailfNedIdOnfTapiNc.id;
    }

    public static final String uri = "http://tail-f.com/ns/ned-id/onf-tapi-nc";
    public String uri() {
        return tailfNedIdOnfTapiNc.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(tailfNedIdOnfTapiNc.uri);
    }

    public static final String prefix = "onf-tapi-nc";
    public String prefix() {
        return tailfNedIdOnfTapiNc.prefix;
    }

    public tailfNedIdOnfTapiNc() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    ned_id = 1509293339;
    public static final String ned_id_ = "onf-tapi-nc:onf-tapi-nc";
    public static final int    _onf_tapi_nc = 1509293339;
    public static final String _onf_tapi_nc_ = "onf-tapi-nc";
}
