/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/tailf-last-login.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.onftapi.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module tailf-last-login.yang */
public class tailfLastLogin extends ConfNamespace {
    public static final int hash = 2058770883;
    public int hash() {
        return tailfLastLogin.hash;
    }

    public static final String id = "_onf-tapi-nc-2.0:onf-tapi-nc-2.0#http://tail-f.com/yang/last-login";
    public String id() {
        return tailfLastLogin.id;
    }

    public static final String uri = "_onf-tapi-nc-2.0:onf-tapi-nc-2.0#http://tail-f.com/yang/last-login";
    public String uri() {
        return tailfLastLogin.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(tailfLastLogin.uri);
    }

    public static final String prefix = "last";
    public String prefix() {
        return tailfLastLogin.prefix;
    }

    public tailfLastLogin() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _user = 1529217067;
    public static final String _user_ = "user";
    public static final int    _num_of_failed_logins = 990687426;
    public static final String _num_of_failed_logins_ = "num-of-failed-logins";
    public static final int    _login_time = 56217328;
    public static final String _login_time_ = "login-time";
    public static final int    _name = 1998270519;
    public static final String _name_ = "name";
    public static final int    _transport = 514190987;
    public static final String _transport_ = "transport";
    public static final int    _login = 1704196980;
    public static final String _login_ = "login";
    public static final int    _last_failed = 920339004;
    public static final String _last_failed_ = "last-failed";
    public static final int    _last_logins = 1946722611;
    public static final String _last_logins_ = "last-logins";
    public static final int    _client_host = 857297659;
    public static final String _client_host_ = "client-host";
    public static final int    _authenticating_host = 2140774720;
    public static final String _authenticating_host_ = "authenticating-host";
}
