/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/tapi-common.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.onftapi.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module tapi-common.yang */
public class tapiCommon extends ConfNamespace {
    public static final int hash = 1017430508;
    public int hash() {
        return tapiCommon.hash;
    }

    public static final String id = "_onf-tapi-nc-2.0:onf-tapi-nc-2.0#urn:onf:otcc:yang:tapi-common";
    public String id() {
        return tapiCommon.id;
    }

    public static final String uri = "_onf-tapi-nc-2.0:onf-tapi-nc-2.0#urn:onf:otcc:yang:tapi-common";
    public String uri() {
        return tapiCommon.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(tapiCommon.uri);
    }

    public static final String prefix = "tapi-common";
    public String prefix() {
        return tapiCommon.prefix;
    }

    public tapiCommon() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _rpc_update_service_interface_point = 2012533247;
    public static final String _rpc_update_service_interface_point_ = "rpc-update-service-interface-point";
    public static final int    _info = 2062105651;
    public static final String _info_ = "info";
    public static final int    _administrative_state = 1048557234;
    public static final String _administrative_state_ = "administrative-state";
    public static final int    _total_size = 2093478719;
    public static final String _total_size_ = "total-size";
    public static final int    _LAYER_PROTOCOL_QUALIFIER_UNSPECIFIED = 1389330591;
    public static final String _LAYER_PROTOCOL_QUALIFIER_UNSPECIFIED_ = "LAYER_PROTOCOL_QUALIFIER_UNSPECIFIED";
    public static final int    _LAYER_PROTOCOL_QUALIFIER = 2030973950;
    public static final String _LAYER_PROTOCOL_QUALIFIER_ = "LAYER_PROTOCOL_QUALIFIER";
    public static final int    _supported_layer_protocol_qualifier = 1339473754;
    public static final String _supported_layer_protocol_qualifier_ = "supported-layer-protocol-qualifier";
    public static final int    _get_service_interface_point_details = 1183132048;
    public static final String _get_service_interface_point_details_ = "get-service-interface-point-details";
    public static final int    _peak_information_rate = 433582594;
    public static final String _peak_information_rate_ = "peak-information-rate";
    public static final int    _result = 401396173;
    public static final String _result_ = "result";
    public static final int    _rpc_get_service_interface_point_details = 961409121;
    public static final String _rpc_get_service_interface_point_details_ = "rpc-get-service-interface-point-details";
    public static final int    _uuid = 328053038;
    public static final String _uuid_ = "uuid";
    public static final int    _device = 617911018;
    public static final String _device_ = "device";
    public static final int    _value = 864367181;
    public static final String _value_ = "value";
    public static final int    _state = 630973766;
    public static final String _state_ = "state";
    public static final int    _value_name = 1213415047;
    public static final String _value_name_ = "value-name";
    public static final int    _sip_id_or_name = 1848539771;
    public static final String _sip_id_or_name_ = "sip-id-or-name";
    public static final int    _operational_state = 1839284571;
    public static final String _operational_state_ = "operational-state";
    public static final int    _get_service_interface_point_list = 1264420499;
    public static final String _get_service_interface_point_list_ = "get-service-interface-point-list";
    public static final int    _context = 1600175075;
    public static final String _context_ = "context";
    public static final int    _sip = 289213200;
    public static final String _sip_ = "sip";
    public static final int    _update_service_interface_point = 562396133;
    public static final String _update_service_interface_point_ = "update-service-interface-point";
    public static final int    _direction = 1468062370;
    public static final String _direction_ = "direction";
    public static final int    _total_potential_capacity = 1584610644;
    public static final String _total_potential_capacity_ = "total-potential-capacity";
    public static final int    _peak_burst_size = 42505974;
    public static final String _peak_burst_size_ = "peak-burst-size";
    public static final int    _bw_profile_type = 649759263;
    public static final String _bw_profile_type_ = "bw-profile-type";
    public static final int    _service_interface_point = 189732751;
    public static final String _service_interface_point_ = "service-interface-point";
    public static final int    _available_capacity = 428510579;
    public static final String _available_capacity_ = "available-capacity";
    public static final int    _rpc_get_service_interface_point_list = 353051322;
    public static final String _rpc_get_service_interface_point_list_ = "rpc-get-service-interface-point-list";
    public static final int    _name = 1998270519;
    public static final String _name_ = "name";
    public static final int    _committed_information_rate = 1688165216;
    public static final String _committed_information_rate_ = "committed-information-rate";
    public static final int    _layer_protocol_name = 1201135583;
    public static final String _layer_protocol_name_ = "layer-protocol-name";
    public static final int    _bandwidth_profile = 1783571670;
    public static final String _bandwidth_profile_ = "bandwidth-profile";
    public static final int    _color_aware = 112024138;
    public static final String _color_aware_ = "color-aware";
    public static final int    _committed_burst_size = 128698928;
    public static final String _committed_burst_size_ = "committed-burst-size";
    public static final int    _unit = 1638458042;
    public static final String _unit_ = "unit";
    public static final int    _coupling_flag = 236387716;
    public static final String _coupling_flag_ = "coupling-flag";
    public static final int    _lifecycle_state = 1569301757;
    public static final String _lifecycle_state_ = "lifecycle-state";
}
