/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/tapi-oam.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.onftapi.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module tapi-oam.yang */
public class tapiOam extends ConfNamespace {
    public static final int hash = 1409124497;
    public int hash() {
        return tapiOam.hash;
    }

    public static final String id = "_onf-tapi-nc-2.0:onf-tapi-nc-2.0#urn:onf:otcc:yang:tapi-oam";
    public String id() {
        return tapiOam.id;
    }

    public static final String uri = "_onf-tapi-nc-2.0:onf-tapi-nc-2.0#urn:onf:otcc:yang:tapi-oam";
    public String uri() {
        return tapiOam.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(tapiOam.uri);
    }

    public static final String prefix = "tapi-oam";
    public String prefix() {
        return tapiOam.prefix;
    }

    public tapiOam() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _meg_identifier = 589453790;
    public static final String _meg_identifier_ = "meg-identifier";
    public static final int    _oam_context = 1151450661;
    public static final String _oam_context_ = "oam-context";
    public static final int    _get_oam_service_end_point = 1659859084;
    public static final String _get_oam_service_end_point_ = "get-oam-service-end-point";
    public static final int    _is_transient = 1352801782;
    public static final String _is_transient_ = "is-transient";
    public static final int    _info = 2062105651;
    public static final String _info_ = "info";
    public static final int    _pm_history_data = 1115692016;
    public static final String _pm_history_data_ = "pm-history-data";
    public static final int    _create_oam_service_end_point = 307038166;
    public static final String _create_oam_service_end_point_ = "create-oam-service-end-point";
    public static final int    _mep = 723575678;
    public static final String _mep_ = "mep";
    public static final int    _rpc_create_oam_service = 1376034373;
    public static final String _rpc_create_oam_service_ = "rpc-create-oam-service";
    public static final int    _administrative_state = 1048557234;
    public static final String _administrative_state_ = "administrative-state";
    public static final int    _meg = 67773323;
    public static final String _meg_ = "meg";
    public static final int    _suspect_interval_flag = 1284355977;
    public static final String _suspect_interval_flag_ = "suspect-interval-flag";
    public static final int    _get_oam_job = 1377246603;
    public static final String _get_oam_job_ = "get-oam-job";
    public static final int    _mep_mip_list = 1444211210;
    public static final String _mep_mip_list_ = "mep-mip-list";
    public static final int    _creation_time = 1207883865;
    public static final String _creation_time_ = "creation-time";
    public static final int    _result = 401396173;
    public static final String _result_ = "result";
    public static final int    _uuid = 328053038;
    public static final String _uuid_ = "uuid";
    public static final int    _meg_level = 1263338374;
    public static final String _meg_level_ = "meg-level";
    public static final int    _device = 617911018;
    public static final String _device_ = "device";
    public static final int    _period_end_time = 683626802;
    public static final String _period_end_time_ = "period-end-time";
    public static final int    _value = 864367181;
    public static final String _value_ = "value";
    public static final int    _state = 630973766;
    public static final String _state_ = "state";
    public static final int    _end_point = 935030957;
    public static final String _end_point_ = "end-point";
    public static final int    _value_name = 1213415047;
    public static final String _value_name_ = "value-name";
    public static final int    _service_interface_point_uuid = 1780718047;
    public static final String _service_interface_point_uuid_ = "service-interface-point-uuid";
    public static final int    _update_oam_service_end_point = 865163241;
    public static final String _update_oam_service_end_point_ = "update-oam-service-end-point";
    public static final int    _delete_oam_service = 1271512736;
    public static final String _delete_oam_service_ = "delete-oam-service";
    public static final int    _operational_state = 1839284571;
    public static final String _operational_state_ = "operational-state";
    public static final int    _get_oam_service = 237922978;
    public static final String _get_oam_service_ = "get-oam-service";
    public static final int    _rpc_get_oam_service_list = 927146293;
    public static final String _rpc_get_oam_service_list_ = "rpc-get-oam-service-list";
    public static final int    _create_oam_job = 1358485994;
    public static final String _create_oam_job_ = "create-oam-job";
    public static final int    _mip = 805461894;
    public static final String _mip_ = "mip";
    public static final int    _connectivity_service_uuid = 84309521;
    public static final String _connectivity_service_uuid_ = "connectivity-service-uuid";
    public static final int    _update_oam_service = 861652458;
    public static final String _update_oam_service_ = "update-oam-service";
    public static final int    _rpc_delete_oam_job = 1392211258;
    public static final String _rpc_delete_oam_job_ = "rpc-delete-oam-job";
    public static final int    _oam_constraint = 1917746953;
    public static final String _oam_constraint_ = "oam-constraint";
    public static final int    _mip_local_id = 2137471309;
    public static final String _mip_local_id_ = "mip-local-id";
    public static final int    _oam_service = 748886102;
    public static final String _oam_service_ = "oam-service";
    public static final int    _connectivity_service_end_point_local_id = 742907263;
    public static final String _connectivity_service_end_point_local_id_ = "connectivity-service-end-point-local-id";
    public static final int    _connectivity_service_end_point = 774187858;
    public static final String _connectivity_service_end_point_ = "connectivity-service-end-point";
    public static final int    _oam_service_end_point_local_id = 84265115;
    public static final String _oam_service_end_point_local_id_ = "oam-service-end-point-local-id";
    public static final int    _rpc_update_oam_service = 1524445627;
    public static final String _rpc_update_oam_service_ = "rpc-update-oam-service";
    public static final int    _rpc_get_meg = 1688568637;
    public static final String _rpc_get_meg_ = "rpc-get-meg";
    public static final int    _rpc_get_oam_service = 1324875915;
    public static final String _rpc_get_oam_service_ = "rpc-get-oam-service";
    public static final int    _rpc_delete_oam_service_end_point = 1637655186;
    public static final String _rpc_delete_oam_service_end_point_ = "rpc-delete-oam-service-end-point";
    public static final int    _OAM_JOB_TYPE = 567201043;
    public static final String _OAM_JOB_TYPE_ = "OAM_JOB_TYPE";
    public static final int    _direction = 1468062370;
    public static final String _direction_ = "direction";
    public static final int    _mep_local_id = 1560169550;
    public static final String _mep_local_id_ = "mep-local-id";
    public static final int    _pm_bin_data = 594149401;
    public static final String _pm_bin_data_ = "pm-bin-data";
    public static final int    _oam_service_uuid = 1761442318;
    public static final String _oam_service_uuid_ = "oam-service-uuid";
    public static final int    _service = 855380710;
    public static final String _service_ = "service";
    public static final int    _oam_profile = 791913443;
    public static final String _oam_profile_ = "oam-profile";
    public static final int    _oam_job = 1546033506;
    public static final String _oam_job_ = "oam-job";
    public static final int    _delete_oam_job = 1266887503;
    public static final String _delete_oam_job_ = "delete-oam-job";
    public static final int    _get_oam_service_list = 1817506316;
    public static final String _get_oam_service_list_ = "get-oam-service-list";
    public static final int    _mep_identifier = 296157285;
    public static final String _mep_identifier_ = "mep-identifier";
    public static final int    _service_interface_point = 189732751;
    public static final String _service_interface_point_ = "service-interface-point";
    public static final int    _service_id = 1973115602;
    public static final String _service_id_ = "service-id";
    public static final int    _timestamp = 35058824;
    public static final String _timestamp_ = "timestamp";
    public static final int    _schedule = 1642863984;
    public static final String _schedule_ = "schedule";
    public static final int    _o_sep_id = 1104262326;
    public static final String _o_sep_id_ = "o-sep-id";
    public static final int    _meg_uuid = 1076806388;
    public static final String _meg_uuid_ = "meg-uuid";
    public static final int    _name = 1998270519;
    public static final String _name_ = "name";
    public static final int    _job_id = 1787667438;
    public static final String _job_id_ = "job-id";
    public static final int    _rpc_get_oam_job = 1696571275;
    public static final String _rpc_get_oam_job_ = "rpc-get-oam-job";
    public static final int    _period = 1135208285;
    public static final String _period_ = "period";
    public static final int    _layer = 47422788;
    public static final String _layer_ = "layer";
    public static final int    _update_oam_job = 752834023;
    public static final String _update_oam_job_ = "update-oam-job";
    public static final int    _oam_service_end_point = 1238211754;
    public static final String _oam_service_end_point_ = "oam-service-end-point";
    public static final int    _create_oam_service = 278147059;
    public static final String _create_oam_service_ = "create-oam-service";
    public static final int    _rpc_delete_oam_service = 730287162;
    public static final String _rpc_delete_oam_service_ = "rpc-delete-oam-service";
    public static final int    _rpc_update_oam_job = 565640322;
    public static final String _rpc_update_oam_job_ = "rpc-update-oam-job";
    public static final int    _get_meg = 121844453;
    public static final String _get_meg_ = "get-meg";
    public static final int    _start_time = 84038180;
    public static final String _start_time_ = "start-time";
    public static final int    _delete_oam_service_end_point = 1534742923;
    public static final String _delete_oam_service_end_point_ = "delete-oam-service-end-point";
    public static final int    _c_sep_id = 2060815604;
    public static final String _c_sep_id_ = "c-sep-id";
    public static final int    _layer_protocol_name = 1201135583;
    public static final String _layer_protocol_name_ = "layer-protocol-name";
    public static final int    _sip_id = 680876821;
    public static final String _sip_id_ = "sip-id";
    public static final int    _rpc_get_oam_service_end_point = 677006377;
    public static final String _rpc_get_oam_service_end_point_ = "rpc-get-oam-service-end-point";
    public static final int    _pm_threshold_data = 230194068;
    public static final String _pm_threshold_data_ = "pm-threshold-data";
    public static final int    _rpc_update_oam_service_end_point = 702432690;
    public static final String _rpc_update_oam_service_end_point_ = "rpc-update-oam-service-end-point";
    public static final int    _oam_profile_uuid = 891178976;
    public static final String _oam_profile_uuid_ = "oam-profile-uuid";
    public static final int    _unit = 1638458042;
    public static final String _unit_ = "unit";
    public static final int    _rpc_create_oam_job = 1338186274;
    public static final String _rpc_create_oam_job_ = "rpc-create-oam-job";
    public static final int    _local_id = 1656047607;
    public static final String _local_id_ = "local-id";
    public static final int    _elapsed_time = 1571653474;
    public static final String _elapsed_time_ = "elapsed-time";
    public static final int    _granularity_period = 989460458;
    public static final String _granularity_period_ = "granularity-period";
    public static final int    _pm_current_data = 619577320;
    public static final String _pm_current_data_ = "pm-current-data";
    public static final int    _peer_mep_identifier = 1549175118;
    public static final String _peer_mep_identifier_ = "peer-mep-identifier";
    public static final int    _rpc_create_oam_service_end_point = 203559519;
    public static final String _rpc_create_oam_service_end_point_ = "rpc-create-oam-service-end-point";
    public static final int    _end_time = 1935053864;
    public static final String _end_time_ = "end-time";
    public static final int    _lifecycle_state = 1569301757;
    public static final String _lifecycle_state_ = "lifecycle-state";
    public static final int    _oam_job_type = 698014606;
    public static final String _oam_job_type_ = "oam-job-type";
}
