/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/tapi-odu.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.onftapi.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module tapi-odu.yang */
public class tapiOdu extends ConfNamespace {
    public static final int hash = 577302930;
    public int hash() {
        return tapiOdu.hash;
    }

    public static final String id = "_onf-tapi-nc-2.0:onf-tapi-nc-2.0#urn:onf:otcc:yang:tapi-odu";
    public String id() {
        return tapiOdu.id;
    }

    public static final String uri = "_onf-tapi-nc-2.0:onf-tapi-nc-2.0#urn:onf:otcc:yang:tapi-odu";
    public String uri() {
        return tapiOdu.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(tapiOdu.uri);
    }

    public static final String prefix = "tapi-odu";
    public String prefix() {
        return tapiOdu.prefix;
    }

    public tapiOdu() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _opu_tributary_slot_size = 301659106;
    public static final String _opu_tributary_slot_size_ = "opu-tributary-slot-size";
    public static final int    _odu_term_and_adapter = 1466106493;
    public static final String _odu_term_and_adapter_ = "odu-term-and-adapter";
    public static final int    _odu_mip = 51649282;
    public static final String _odu_mip_ = "odu-mip";
    public static final int    _odu_mip_spec = 1114186453;
    public static final String _odu_mip_spec_ = "odu-mip-spec";
    public static final int    _odu_pm = 440685755;
    public static final String _odu_pm_ = "odu-pm";
    public static final int    _lck = 588645314;
    public static final String _lck_ = "lck";
    public static final int    _tributary_port_number = 888429772;
    public static final String _tributary_port_number_ = "tributary-port-number";
    public static final int    _ODU_TYPE_ODU2 = 734279483;
    public static final String _ODU_TYPE_ODU2_ = "ODU_TYPE_ODU2";
    public static final int    _configured_mapping_type = 1542423912;
    public static final String _configured_mapping_type_ = "configured-mapping-type";
    public static final int    _odu_ctp = 1347908710;
    public static final String _odu_ctp_ = "odu-ctp";
    public static final int    _ODU_TYPE_ODU4 = 1182061561;
    public static final String _ODU_TYPE_ODU4_ = "ODU_TYPE_ODU4";
    public static final int    _odu_connection_end_point_spec = 1145759191;
    public static final String _odu_connection_end_point_spec_ = "odu-connection-end-point-spec";
    public static final int    _deg_thr_value = 235653695;
    public static final String _deg_thr_value_ = "deg-thr-value";
    public static final int    _named_payload_type = 1755864590;
    public static final String _named_payload_type_ = "named-payload-type";
    public static final int    _ODU_TYPE_ODU0 = 440207705;
    public static final String _ODU_TYPE_ODU0_ = "ODU_TYPE_ODU0";
    public static final int    _tcm_fields_in_use = 17193881;
    public static final String _tcm_fields_in_use_ = "tcm-fields-in-use";
    public static final int    _ex_sapi = 1255278393;
    public static final String _ex_sapi_ = "ex-sapi";
    public static final int    _odu_rate = 788489938;
    public static final String _odu_rate_ = "odu-rate";
    public static final int    _ODU_TYPE_ODU1 = 188675897;
    public static final String _ODU_TYPE_ODU1_ = "ODU_TYPE_ODU1";
    public static final int    _tim = 1985651200;
    public static final String _tim_ = "tim";
    public static final int    _tim_det_mode = 263461650;
    public static final String _tim_det_mode_ = "tim-det-mode";
    public static final int    _odu_csep_ttp_pac = 1452034103;
    public static final String _odu_csep_ttp_pac_ = "odu-csep-ttp-pac";
    public static final int    _ssf = 1936885959;
    public static final String _ssf_ = "ssf";
    public static final int    _odu_cn_effective_time_slot_list = 836962315;
    public static final String _odu_cn_effective_time_slot_list_ = "odu-cn-effective-time-slot-list";
    public static final int    _odu_csep_common_pac = 1372235489;
    public static final String _odu_csep_common_pac_ = "odu-csep-common-pac";
    public static final int    _pre_fec_ber = 930828535;
    public static final String _pre_fec_ber_ = "pre-fec-ber";
    public static final int    _ODU_TYPE_ODU_FLEX = 961794655;
    public static final String _ODU_TYPE_ODU_FLEX_ = "ODU_TYPE_ODU_FLEX";
    public static final int    _uas = 1325375758;
    public static final String _uas_ = "uas";
    public static final int    _auto_payload_type = 1191988452;
    public static final String _auto_payload_type_ = "auto-payload-type";
    public static final int    _odu_protection = 1173855368;
    public static final String _odu_protection_ = "odu-protection";
    public static final int    _ODU_TYPE = 171910941;
    public static final String _ODU_TYPE_ = "ODU_TYPE";
    public static final int    _acti = 1792773935;
    public static final String _acti_ = "acti";
    public static final int    _max_client_size = 1840931397;
    public static final String _max_client_size_ = "max-client-size";
    public static final int    _odu_csep_ctp_pac = 674768868;
    public static final String _odu_csep_ctp_pac_ = "odu-csep-ctp-pac";
    public static final int    _odu_common = 2041440137;
    public static final String _odu_common_ = "odu-common";
    public static final int    _tributary_slot_list = 1970502350;
    public static final String _tributary_slot_list_ = "tributary-slot-list";
    public static final int    _accepted_msi = 1865878099;
    public static final String _accepted_msi_ = "accepted-msi";
    public static final int    _deg = 2048618051;
    public static final String _deg_ = "deg";
    public static final int    _ODU_TYPE_ODU2E = 1640714830;
    public static final String _ODU_TYPE_ODU2E_ = "ODU_TYPE_ODU2E";
    public static final int    _fec_parameters = 1442909908;
    public static final String _fec_parameters_ = "fec-parameters";
    public static final int    _n_ses = 1464728136;
    public static final String _n_ses_ = "n-ses";
    public static final int    _oci = 273884546;
    public static final String _oci_ = "oci";
    public static final int    _uncorrectable_bits = 1057261617;
    public static final String _uncorrectable_bits_ = "uncorrectable-bits";
    public static final int    _odu_ncm = 1915707113;
    public static final String _odu_ncm_ = "odu-ncm";
    public static final int    _odu_tcm = 813116638;
    public static final String _odu_tcm_ = "odu-tcm";
    public static final int    _post_fec_ber = 1498085913;
    public static final String _post_fec_ber_ = "post-fec-ber";
    public static final int    _tcm_field = 1503402785;
    public static final String _tcm_field_ = "tcm-field";
    public static final int    _corrected_bytes = 1104495784;
    public static final String _corrected_bytes_ = "corrected-bytes";
    public static final int    _client_capacity = 364516477;
    public static final String _client_capacity_ = "client-capacity";
    public static final int    _bdi = 466337092;
    public static final String _bdi_ = "bdi";
    public static final int    _configured_client_type = 1520706214;
    public static final String _configured_client_type_ = "configured-client-type";
    public static final int    _ODU_TYPE_ODU3 = 918935877;
    public static final String _ODU_TYPE_ODU3_ = "ODU_TYPE_ODU3";
    public static final int    _fuas = 938893402;
    public static final String _fuas_ = "fuas";
    public static final int    _odu_rate_tolerance = 37318023;
    public static final String _odu_rate_tolerance_ = "odu-rate-tolerance";
    public static final int    _odu_defect = 1319287374;
    public static final String _odu_defect_ = "odu-defect";
    public static final int    _tim_act_disabled = 404385631;
    public static final String _tim_act_disabled_ = "tim-act-disabled";
    public static final int    _n_bbe = 2107071839;
    public static final String _n_bbe_ = "n-bbe";
    public static final int    _uncorrectable_bytes = 38468256;
    public static final String _uncorrectable_bytes_ = "uncorrectable-bytes";
    public static final int    _deg_thr_type = 64855458;
    public static final String _deg_thr_type_ = "deg-thr-type";
    public static final int    _ODU_TYPE_ODU_CN = 1401752070;
    public static final String _ODU_TYPE_ODU_CN_ = "ODU_TYPE_ODU_CN";
    public static final int    _odu_pool = 1017496406;
    public static final String _odu_pool_ = "odu-pool";
    public static final int    _ex_dapi = 818940791;
    public static final String _ex_dapi_ = "ex-dapi";
    public static final int    _max_client_instances = 848773038;
    public static final String _max_client_instances_ = "max-client-instances";
    public static final int    _f_ses = 1055279976;
    public static final String _f_ses_ = "f-ses";
    public static final int    _deg_m = 102609576;
    public static final String _deg_m_ = "deg-m";
    public static final int    _f_bbe = 2044713852;
    public static final String _f_bbe_ = "f-bbe";
    public static final int    _odu_connectivity_service_end_point_spec = 1066419729;
    public static final String _odu_connectivity_service_end_point_spec_ = "odu-connectivity-service-end-point-spec";
    public static final int    _aps_enable = 250541385;
    public static final String _aps_enable_ = "aps-enable";
    public static final int    _nuas = 955982089;
    public static final String _nuas_ = "nuas";
    public static final int    _hex_payload_type = 167346139;
    public static final String _hex_payload_type_ = "hex-payload-type";
    public static final int    _bidirectional = 2096818457;
    public static final String _bidirectional_ = "bidirectional";
    public static final int    _aps_level = 866037819;
    public static final String _aps_level_ = "aps-level";
    public static final int    _corrected_bits = 768476781;
    public static final String _corrected_bits_ = "corrected-bits";
    public static final int    _deg_thr = 794839069;
    public static final String _deg_thr_ = "deg-thr";
    public static final int    _percentage_granularity = 486368403;
    public static final String _percentage_granularity_ = "percentage-granularity";
    public static final int    _accepted_payload_type = 10683622;
    public static final String _accepted_payload_type_ = "accepted-payload-type";
    public static final int    _odu_type = 1369974531;
    public static final String _odu_type_ = "odu-type";
    public static final int    _number_of_odu_c = 1375922948;
    public static final String _number_of_odu_c_ = "number-of-odu-c";
    public static final int    _odu_node_edge_point_spec = 1989797857;
    public static final String _odu_node_edge_point_spec_ = "odu-node-edge-point-spec";
}
