/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/tapi-path-computation.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.onftapi.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module tapi-path-computation.yang */
public class tapiPathComputation extends ConfNamespace {
    public static final int hash = 669305512;
    public int hash() {
        return tapiPathComputation.hash;
    }

    public static final String id = "_onf-tapi-nc-2.0:onf-tapi-nc-2.0#urn:onf:otcc:yang:tapi-path-computation";
    public String id() {
        return tapiPathComputation.id;
    }

    public static final String uri = "_onf-tapi-nc-2.0:onf-tapi-nc-2.0#urn:onf:otcc:yang:tapi-path-computation";
    public String uri() {
        return tapiPathComputation.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(tapiPathComputation.uri);
    }

    public static final String prefix = "tapi-path-computation";
    public String prefix() {
        return tapiPathComputation.prefix;
    }

    public tapiPathComputation() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _traffic_interruption = 640122380;
    public static final String _traffic_interruption_ = "traffic-interruption";
    public static final int    _jitter_characteristic = 1298437386;
    public static final String _jitter_characteristic_ = "jitter-characteristic";
    public static final int    _path = 1002915403;
    public static final String _path_ = "path";
    public static final int    _risk_identifier_list = 2008723404;
    public static final String _risk_identifier_list_ = "risk-identifier-list";
    public static final int    _info = 2062105651;
    public static final String _info_ = "info";
    public static final int    _exclude_link = 1374901490;
    public static final String _exclude_link_ = "exclude-link";
    public static final int    _path_id_or_name = 826931364;
    public static final String _path_id_or_name_ = "path-id-or-name";
    public static final int    _resource_sharing = 1592637019;
    public static final String _resource_sharing_ = "resource-sharing";
    public static final int    _cost_value = 932572282;
    public static final String _cost_value_ = "cost-value";
    public static final int    _total_size = 2093478719;
    public static final String _total_size_ = "total-size";
    public static final int    _objective_function = 2086743919;
    public static final String _objective_function_ = "objective-function";
    public static final int    _link_utilization = 1744621198;
    public static final String _link_utilization_ = "link-utilization";
    public static final int    _peak_information_rate = 433582594;
    public static final String _peak_information_rate_ = "peak-information-rate";
    public static final int    _result = 401396173;
    public static final String _result_ = "result";
    public static final int    _risk_characteristic_name = 299163717;
    public static final String _risk_characteristic_name_ = "risk-characteristic-name";
    public static final int    _uuid = 328053038;
    public static final String _uuid_ = "uuid";
    public static final int    _path_computation_context = 18341004;
    public static final String _path_computation_context_ = "path-computation-context";
    public static final int    _rpc_compute_p_2_p_path = 358199307;
    public static final String _rpc_compute_p_2_p_path_ = "rpc-compute-p-2-p-path";
    public static final int    _max_allowed_cost = 1829033660;
    public static final String _max_allowed_cost_ = "max-allowed-cost";
    public static final int    _route_objective_function = 793232331;
    public static final String _route_objective_function_ = "route-objective-function";
    public static final int    _max_allowed_hops = 887915494;
    public static final String _max_allowed_hops_ = "max-allowed-hops";
    public static final int    _device = 617911018;
    public static final String _device_ = "device";
    public static final int    _cost_characteristic = 1763202494;
    public static final String _cost_characteristic_ = "cost-characteristic";
    public static final int    _layer_protocol_qualifier = 1786424353;
    public static final String _layer_protocol_qualifier_ = "layer-protocol-qualifier";
    public static final int    _include_path = 380731610;
    public static final String _include_path_ = "include-path";
    public static final int    _diversity_policy = 1456042363;
    public static final String _diversity_policy_ = "diversity-policy";
    public static final int    _value = 864367181;
    public static final String _value_ = "value";
    public static final int    _end_point = 935030957;
    public static final String _end_point_ = "end-point";
    public static final int    _sep = 1919146393;
    public static final String _sep_ = "sep";
    public static final int    _value_name = 1213415047;
    public static final String _value_name_ = "value-name";
    public static final int    _fixed_latency_characteristic = 2135091342;
    public static final String _fixed_latency_characteristic_ = "fixed-latency-characteristic";
    public static final int    _include_node = 135054715;
    public static final String _include_node_ = "include-node";
    public static final int    _service_interface_point_uuid = 1780718047;
    public static final String _service_interface_point_uuid_ = "service-interface-point-uuid";
    public static final int    _role = 1297556411;
    public static final String _role_ = "role";
    public static final int    _optimize_p_2_ppath = 1659968165;
    public static final String _optimize_p_2_ppath_ = "optimize-p-2-ppath";
    public static final int    _latency_characteristic = 256624057;
    public static final String _latency_characteristic_ = "latency-characteristic";
    public static final int    _rpc_optimize_p_2_ppath = 761806035;
    public static final String _rpc_optimize_p_2_ppath_ = "rpc-optimize-p-2-ppath";
    public static final int    _max_allowed_delay = 359766776;
    public static final String _max_allowed_delay_ = "max-allowed-delay";
    public static final int    _rpc_delete_p_2_p_path = 1687157209;
    public static final String _rpc_delete_p_2_p_path_ = "rpc-delete-p-2-p-path";
    public static final int    _cost_name = 1738788381;
    public static final String _cost_name_ = "cost-name";
    public static final int    _capacity = 191070892;
    public static final String _capacity_ = "capacity";
    public static final int    _link_uuid = 1302256528;
    public static final String _link_uuid_ = "link-uuid";
    public static final int    _priority = 1346277862;
    public static final String _priority_ = "priority";
    public static final int    _direction = 1468062370;
    public static final String _direction_ = "direction";
    public static final int    _traffic_property_name = 2080339994;
    public static final String _traffic_property_name_ = "traffic-property-name";
    public static final int    _is_exclusive = 1138353436;
    public static final String _is_exclusive_ = "is-exclusive";
    public static final int    _peak_burst_size = 42505974;
    public static final String _peak_burst_size_ = "peak-burst-size";
    public static final int    _service = 855380710;
    public static final String _service_ = "service";
    public static final int    _exclude_node = 1827238916;
    public static final String _exclude_node_ = "exclude-node";
    public static final int    _bw_profile_type = 649759263;
    public static final String _bw_profile_type_ = "bw-profile-type";
    public static final int    _service_interface_point = 189732751;
    public static final String _service_interface_point_ = "service-interface-point";
    public static final int    _cost_algorithm = 1731447885;
    public static final String _cost_algorithm_ = "cost-algorithm";
    public static final int    _topology_uuid = 403232376;
    public static final String _topology_uuid_ = "topology-uuid";
    public static final int    _routing_constraint = 509371891;
    public static final String _routing_constraint_ = "routing-constraint";
    public static final int    _include_link = 1583952687;
    public static final String _include_link_ = "include-link";
    public static final int    _name = 1998270519;
    public static final String _name_ = "name";
    public static final int    _compute_p_2_p_path = 1353384421;
    public static final String _compute_p_2_p_path_ = "compute-p-2-p-path";
    public static final int    _exclude_path = 1821453932;
    public static final String _exclude_path_ = "exclude-path";
    public static final int    _concurrent_paths = 1863649909;
    public static final String _concurrent_paths_ = "concurrent-paths";
    public static final int    _link = 481374722;
    public static final String _link_ = "link";
    public static final int    _path_uuid = 1486856354;
    public static final String _path_uuid_ = "path-uuid";
    public static final int    _cost_optimization = 137065085;
    public static final String _cost_optimization_ = "cost-optimization";
    public static final int    _committed_information_rate = 1688165216;
    public static final String _committed_information_rate_ = "committed-information-rate";
    public static final int    _layer_protocol_name = 1201135583;
    public static final String _layer_protocol_name_ = "layer-protocol-name";
    public static final int    _delete_p_2_p_path = 1364531242;
    public static final String _delete_p_2_p_path_ = "delete-p-2-p-path";
    public static final int    _avoid_topology = 1384990573;
    public static final String _avoid_topology_ = "avoid-topology";
    public static final int    _bandwidth_profile = 1783571670;
    public static final String _bandwidth_profile_ = "bandwidth-profile";
    public static final int    _risk_diversity_characteristic = 1203357821;
    public static final String _risk_diversity_characteristic_ = "risk-diversity-characteristic";
    public static final int    _color_aware = 112024138;
    public static final String _color_aware_ = "color-aware";
    public static final int    _committed_burst_size = 128698928;
    public static final String _committed_burst_size_ = "committed-burst-size";
    public static final int    _optimization_constraint = 1512844545;
    public static final String _optimization_constraint_ = "optimization-constraint";
    public static final int    _unit = 1638458042;
    public static final String _unit_ = "unit";
    public static final int    _bandwidth_optimization = 1994847136;
    public static final String _bandwidth_optimization_ = "bandwidth-optimization";
    public static final int    _path_comp_service = 298352609;
    public static final String _path_comp_service_ = "path-comp-service";
    public static final int    _queing_latency_characteristic = 2128069169;
    public static final String _queing_latency_characteristic_ = "queing-latency-characteristic";
    public static final int    _coupling_flag = 236387716;
    public static final String _coupling_flag_ = "coupling-flag";
    public static final int    _local_id = 1656047607;
    public static final String _local_id_ = "local-id";
    public static final int    _include_topology = 1510447090;
    public static final String _include_topology_ = "include-topology";
    public static final int    _preferred_transport_layer = 579298257;
    public static final String _preferred_transport_layer_ = "preferred-transport-layer";
    public static final int    _wander_characteristic = 266620206;
    public static final String _wander_characteristic_ = "wander-characteristic";
    public static final int    _route_direction = 1279222294;
    public static final String _route_direction_ = "route-direction";
    public static final int    _topology_constraint = 1259154739;
    public static final String _topology_constraint_ = "topology-constraint";
}
