/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/tapi-equipment.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.onftapi.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module tapi-equipment.yang */
public class tapiEquipment extends ConfNamespace {
    public static final int hash = 1104950801;
    public int hash() {
        return tapiEquipment.hash;
    }

    public static final String id = "_onf-tapi-nc-2.0:onf-tapi-nc-2.0#urn:onf:otcc:yang:tapi-equipment";
    public String id() {
        return tapiEquipment.id;
    }

    public static final String uri = "_onf-tapi-nc-2.0:onf-tapi-nc-2.0#urn:onf:otcc:yang:tapi-equipment";
    public String uri() {
        return tapiEquipment.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(tapiEquipment.uri);
    }

    public static final String prefix = "tapi-equipment";
    public String prefix() {
        return tapiEquipment.prefix;
    }

    public tapiEquipment() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _access_port = 1291738110;
    public static final String _access_port_ = "access-port";
    public static final int    _rpc_get_physical_span = 523950015;
    public static final String _rpc_get_physical_span_ = "rpc-get-physical-span";
    public static final int    _EQUIPMENT_CATEGORY = 265381782;
    public static final String _EQUIPMENT_CATEGORY_ = "EQUIPMENT_CATEGORY";
    public static final int    _equipment_location = 207395722;
    public static final String _equipment_location_ = "equipment-location";
    public static final int    _physical_span = 19302623;
    public static final String _physical_span_ = "physical-span";
    public static final int    _info = 2062105651;
    public static final String _info_ = "info";
    public static final int    _spliced_strand = 2032251334;
    public static final String _spliced_strand_ = "spliced-strand";
    public static final int    _asset_instance_identifier = 191280396;
    public static final String _asset_instance_identifier_ = "asset-instance-identifier";
    public static final int    _EQUIPMENT_OBJECT_TYPE_ABSTRACT_STRAND = 2027231072;
    public static final String _EQUIPMENT_OBJECT_TYPE_ABSTRACT_STRAND_ = "EQUIPMENT_OBJECT_TYPE_ABSTRACT_STRAND";
    public static final int    _get_physical_span = 528482680;
    public static final String _get_physical_span_ = "get-physical-span";
    public static final int    _access_port_uuid = 71422905;
    public static final String _access_port_uuid_ = "access-port-uuid";
    public static final int    _EQUIPMENT_OBJECT_TYPE = 372984004;
    public static final String _EQUIPMENT_OBJECT_TYPE_ = "EQUIPMENT_OBJECT_TYPE";
    public static final int    _rpc_get_physical_span_list = 869262788;
    public static final String _rpc_get_physical_span_list_ = "rpc-get-physical-span-list";
    public static final int    _expected_non_field_replaceable_module = 900320911;
    public static final String _expected_non_field_replaceable_module_ = "expected-non-field-replaceable-module";
    public static final int    _physical_context = 614221505;
    public static final String _physical_context_ = "physical-context";
    public static final int    _manufacturer_identifier = 1767289632;
    public static final String _manufacturer_identifier_ = "manufacturer-identifier";
    public static final int    _result = 401396173;
    public static final String _result_ = "result";
    public static final int    _uuid = 328053038;
    public static final String _uuid_ = "uuid";
    public static final int    _EQUIPMENT_OBJECT_TYPE_DEVICE = 1167589155;
    public static final String _EQUIPMENT_OBJECT_TYPE_DEVICE_ = "EQUIPMENT_OBJECT_TYPE_DEVICE";
    public static final int    _rpc_get_device_list = 1127799748;
    public static final String _rpc_get_device_list_ = "rpc-get-device-list";
    public static final int    _device = 617911018;
    public static final String _device_ = "device";
    public static final int    _pin_identification = 2081323034;
    public static final String _pin_identification_ = "pin-identification";
    public static final int    _EQUIPMENT_OBJECT_TYPE_HOLDER = 2052700247;
    public static final String _EQUIPMENT_OBJECT_TYPE_HOLDER_ = "EQUIPMENT_OBJECT_TYPE_HOLDER";
    public static final int    _EQUIPMENT_CATEGORY_SMALL_FORMFACTOR_PLUGGABLE = 1035807643;
    public static final String _EQUIPMENT_CATEGORY_SMALL_FORMFACTOR_PLUGGABLE_ = "EQUIPMENT_CATEGORY_SMALL_FORMFACTOR_PLUGGABLE";
    public static final int    _value = 864367181;
    public static final String _value_ = "value";
    public static final int    _pin_role = 1400384887;
    public static final String _pin_role_ = "pin-role";
    public static final int    _value_name = 1213415047;
    public static final String _value_name_ = "value-name";
    public static final int    _EQUIPMENT_OBJECT_TYPE_PHYSICAL_SPAN = 211889143;
    public static final String _EQUIPMENT_OBJECT_TYPE_PHYSICAL_SPAN_ = "EQUIPMENT_OBJECT_TYPE_PHYSICAL_SPAN";
    public static final int    _EQUIPMENT_CATEGORY_SUBRACK = 1684933019;
    public static final String _EQUIPMENT_CATEGORY_SUBRACK_ = "EQUIPMENT_CATEGORY_SUBRACK";
    public static final int    _holder_category = 1266370610;
    public static final String _holder_category_ = "holder-category";
    public static final int    _rpc_get_device = 1359502424;
    public static final String _rpc_get_device_ = "rpc-get-device";
    public static final int    _supporting_access_port = 1626479180;
    public static final String _supporting_access_port_ = "supporting-access-port";
    public static final int    _is_guided = 1213607859;
    public static final String _is_guided_ = "is-guided";
    public static final int    _EQUIPMENT_OBJECT_TYPE_EQUIPMENT = 65091806;
    public static final String _EQUIPMENT_OBJECT_TYPE_EQUIPMENT_ = "EQUIPMENT_OBJECT_TYPE_EQUIPMENT";
    public static final int    _CONNECTOR_AND_PIN_ORIENTATION_FEMALE = 1685722195;
    public static final String _CONNECTOR_AND_PIN_ORIENTATION_FEMALE_ = "CONNECTOR_AND_PIN_ORIENTATION_FEMALE";
    public static final int    _pin_and_role = 734376558;
    public static final String _pin_and_role_ = "pin-and-role";
    public static final int    _CONNECTOR_AND_PIN_ORIENTATION = 264487441;
    public static final String _CONNECTOR_AND_PIN_ORIENTATION_ = "CONNECTOR_AND_PIN_ORIENTATION";
    public static final int    _serial_number = 544353266;
    public static final String _serial_number_ = "serial-number";
    public static final int    _abstract_strand = 941467630;
    public static final String _abstract_strand_ = "abstract-strand";
    public static final int    _supporting_physical_span = 1254981455;
    public static final String _supporting_physical_span_ = "supporting-physical-span";
    public static final int    _equipment = 247143830;
    public static final String _equipment_ = "equipment";
    public static final int    _get_physical_span_list = 884917784;
    public static final String _get_physical_span_list_ = "get-physical-span-list";
    public static final int    _actual_holder = 296950565;
    public static final String _actual_holder_ = "actual-holder";
    public static final int    _pin_name = 794163600;
    public static final String _pin_name_ = "pin-name";
    public static final int    _connector_pin = 61609682;
    public static final String _connector_pin_ = "connector-pin";
    public static final int    _get_device = 291017468;
    public static final String _get_device_ = "get-device";
    public static final int    _HOLDER_CATEGORY_SLOT = 1786366391;
    public static final String _HOLDER_CATEGORY_SLOT_ = "HOLDER_CATEGORY_SLOT";
    public static final int    _common_holder_properties = 1748496908;
    public static final String _common_holder_properties_ = "common-holder-properties";
    public static final int    _strand_media_characteristics = 221787768;
    public static final String _strand_media_characteristics_ = "strand-media-characteristics";
    public static final int    _location_in_connector = 683298558;
    public static final String _location_in_connector_ = "location-in-connector";
    public static final int    _equipment_type_description = 53804419;
    public static final String _equipment_type_description_ = "equipment-type-description";
    public static final int    _physical_span_uuid = 815284772;
    public static final String _physical_span_uuid_ = "physical-span-uuid";
    public static final int    _common_equipment_properties = 878455519;
    public static final String _common_equipment_properties_ = "common-equipment-properties";
    public static final int    _is_expected_actual_mismatch = 833752902;
    public static final String _is_expected_actual_mismatch_ = "is-expected-actual-mismatch";
    public static final int    _CONNECTOR_AND_PIN_ORIENTATION_SYMMETRIC_NEUTRAL = 2045061743;
    public static final String _CONNECTOR_AND_PIN_ORIENTATION_SYMMETRIC_NEUTRAL_ = "CONNECTOR_AND_PIN_ORIENTATION_SYMMETRIC_NEUTRAL";
    public static final int    _equipment_type_version = 317575587;
    public static final String _equipment_type_version_ = "equipment-type-version";
    public static final int    _abstract_strand_local_id = 2070354459;
    public static final String _abstract_strand_local_id_ = "abstract-strand-local-id";
    public static final int    _name = 1998270519;
    public static final String _name_ = "name";
    public static final int    _expected_holder = 673068742;
    public static final String _expected_holder_ = "expected-holder";
    public static final int    _category = 2142289646;
    public static final String _category_ = "category";
    public static final int    _occupying_fru = 506309072;
    public static final String _occupying_fru_ = "occupying-fru";
    public static final int    _common_actual_properties = 704137927;
    public static final String _common_actual_properties_ = "common-actual-properties";
    public static final int    _holder_location = 1588384659;
    public static final String _holder_location_ = "holder-location";
    public static final int    _equipment_uuid = 414391056;
    public static final String _equipment_uuid_ = "equipment-uuid";
    public static final int    _actual_equipment = 1712215360;
    public static final String _actual_equipment_ = "actual-equipment";
    public static final int    _asset_type_identifier = 1656454823;
    public static final String _asset_type_identifier_ = "asset-type-identifier";
    public static final int    _HOLDER_CATEGORY = 1037167650;
    public static final String _HOLDER_CATEGORY_ = "HOLDER_CATEGORY";
    public static final int    _CONNECTOR_AND_PIN_ORIENTATION_MALE = 903733222;
    public static final String _CONNECTOR_AND_PIN_ORIENTATION_MALE_ = "CONNECTOR_AND_PIN_ORIENTATION_MALE";
    public static final int    _adjacent_strand = 807081828;
    public static final String _adjacent_strand_ = "adjacent-strand";
    public static final int    _EQUIPMENT_CATEGORY_STAND_ALONE_UNIT = 1081147983;
    public static final String _EQUIPMENT_CATEGORY_STAND_ALONE_UNIT_ = "EQUIPMENT_CATEGORY_STAND_ALONE_UNIT";
    public static final int    _EQUIPMENT_CATEGORY_RACK = 2082071258;
    public static final String _EQUIPMENT_CATEGORY_RACK_ = "EQUIPMENT_CATEGORY_RACK";
    public static final int    _device_uuid = 343261981;
    public static final String _device_uuid_ = "device-uuid";
    public static final int    _get_device_list = 1827066535;
    public static final String _get_device_list_ = "get-device-list";
    public static final int    _manufacture_date = 1632784566;
    public static final String _manufacture_date_ = "manufacture-date";
    public static final int    _expected_equipment = 1816790769;
    public static final String _expected_equipment_ = "expected-equipment";
    public static final int    _geographical_location = 1744182488;
    public static final String _geographical_location_ = "geographical-location";
    public static final int    _manufacturer_name = 735557708;
    public static final String _manufacturer_name_ = "manufacturer-name";
    public static final int    _is_powered = 1089705935;
    public static final String _is_powered_ = "is-powered";
    public static final int    _equipment_type_identifier = 168602850;
    public static final String _equipment_type_identifier_ = "equipment-type-identifier";
    public static final int    _contained_holder = 428011779;
    public static final String _contained_holder_ = "contained-holder";
    public static final int    _actual_non_field_replaceable_module = 1719818082;
    public static final String _actual_non_field_replaceable_module_ = "actual-non-field-replaceable-module";
    public static final int    _local_id = 1656047607;
    public static final String _local_id_ = "local-id";
    public static final int    _equipment_type_name = 553124351;
    public static final String _equipment_type_name_ = "equipment-type-name";
    public static final int    _EQUIPMENT_CATEGORY_CIRCUIT_PACK = 1037044674;
    public static final String _EQUIPMENT_CATEGORY_CIRCUIT_PACK_ = "EQUIPMENT_CATEGORY_CIRCUIT_PACK";
    public static final int    _connector_identification = 1549163213;
    public static final String _connector_identification_ = "connector-identification";
    public static final int    _temperature = 362670904;
    public static final String _temperature_ = "temperature";
    public static final int    _EQUIPMENT_OBJECT_TYPE_ACCESS_PORT = 321421341;
    public static final String _EQUIPMENT_OBJECT_TYPE_ACCESS_PORT_ = "EQUIPMENT_OBJECT_TYPE_ACCESS_PORT";
}
