/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/tapi-photonic-media-cisco-extn.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.onftapi.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module tapi-photonic-media-cisco-extn.yang */
public class tapiPhotonicMediaCiscoExtn extends ConfNamespace {
    public static final int hash = 445288683;
    public int hash() {
        return tapiPhotonicMediaCiscoExtn.hash;
    }

    public static final String id = "_onf-tapi-nc-2.0:onf-tapi-nc-2.0#http://cisco.com/yang/conc/tapi/photonic-media-extn";
    public String id() {
        return tapiPhotonicMediaCiscoExtn.id;
    }

    public static final String uri = "_onf-tapi-nc-2.0:onf-tapi-nc-2.0#http://cisco.com/yang/conc/tapi/photonic-media-extn";
    public String uri() {
        return tapiPhotonicMediaCiscoExtn.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(tapiPhotonicMediaCiscoExtn.uri);
    }

    public static final String prefix = "tapi-photonic-media-cisco-extn";
    public String prefix() {
        return tapiPhotonicMediaCiscoExtn.prefix;
    }

    public tapiPhotonicMediaCiscoExtn() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _measured_power_egress = 249858064;
    public static final String _measured_power_egress_ = "measured-power-egress";
    public static final int    _suspect_interval_flag = 1284355977;
    public static final String _suspect_interval_flag_ = "suspect-interval-flag";
    public static final int    _get_live_power_data = 1962834368;
    public static final String _get_live_power_data_ = "get-live-power-data";
    public static final int    _ots_media_channel_pm_history_data = 688136616;
    public static final String _ots_media_channel_pm_history_data_ = "ots-media-channel-pm-history-data";
    public static final int    _c_band = 461813499;
    public static final String _c_band_ = "c-band";
    public static final int    _period_end_time = 683626802;
    public static final String _period_end_time_ = "period-end-time";
    public static final int    _ots_media_channel = 1703572004;
    public static final String _ots_media_channel_ = "ots-media-channel";
    public static final int    _history_power_ingress = 1064267582;
    public static final String _history_power_ingress_ = "history-power-ingress";
    public static final int    _avg_power = 1925262402;
    public static final String _avg_power_ = "avg-power";
    public static final int    _period_start_time = 109643003;
    public static final String _period_start_time_ = "period-start-time";
    public static final int    _max_power = 243894008;
    public static final String _max_power_ = "max-power";
    public static final int    _min_power = 1395750998;
    public static final String _min_power_ = "min-power";
    public static final int    _power_spectral_density = 1432508232;
    public static final String _power_spectral_density_ = "power-spectral-density";
    public static final int    _total_power = 1322562114;
    public static final String _total_power_ = "total-power";
    public static final int    _history_power_egress = 1225125480;
    public static final String _history_power_egress_ = "history-power-egress";
    public static final int    _media_channel = 1003958371;
    public static final String _media_channel_ = "media-channel";
    public static final int    _live_power_data = 60521799;
    public static final String _live_power_data_ = "live-power-data";
    public static final int    _measured_power_ingress = 192737794;
    public static final String _measured_power_ingress_ = "measured-power-ingress";
    public static final int    _media_channel_pm_history_data = 520521820;
    public static final String _media_channel_pm_history_data_ = "media-channel-pm-history-data";
}
