/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/tapi-dsr.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.onftapi.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module tapi-dsr.yang */
public class tapiDsr extends ConfNamespace {
    public static final int hash = 39695294;
    public int hash() {
        return tapiDsr.hash;
    }

    public static final String id = "_onf-tapi-nc-2.0:onf-tapi-nc-2.0#urn:onf:otcc:yang:tapi-dsr";
    public String id() {
        return tapiDsr.id;
    }

    public static final String uri = "_onf-tapi-nc-2.0:onf-tapi-nc-2.0#urn:onf:otcc:yang:tapi-dsr";
    public String uri() {
        return tapiDsr.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(tapiDsr.uri);
    }

    public static final String prefix = "tapi-dsr";
    public String prefix() {
        return tapiDsr.prefix;
    }

    public tapiDsr() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _DIGITAL_SIGNAL_TYPE_IB_QDR = 1301799558;
    public static final String _DIGITAL_SIGNAL_TYPE_IB_QDR_ = "DIGITAL_SIGNAL_TYPE_IB_QDR";
    public static final int    _DIGITAL_SIGNAL_TYPE_OTU_2E = 2139618941;
    public static final String _DIGITAL_SIGNAL_TYPE_OTU_2E_ = "DIGITAL_SIGNAL_TYPE_OTU_2E";
    public static final int    _DIGITAL_SIGNAL_TYPE_SDI_3G = 1683202668;
    public static final String _DIGITAL_SIGNAL_TYPE_SDI_3G_ = "DIGITAL_SIGNAL_TYPE_SDI_3G";
    public static final int    _DIGITAL_SIGNAL_TYPE_DVB_ASI = 1145737168;
    public static final String _DIGITAL_SIGNAL_TYPE_DVB_ASI_ = "DIGITAL_SIGNAL_TYPE_DVB_ASI";
    public static final int    _DIGITAL_SIGNAL_TYPE_100_GigE = 1503009947;
    public static final String _DIGITAL_SIGNAL_TYPE_100_GigE_ = "DIGITAL_SIGNAL_TYPE_100_GigE";
    public static final int    _DIGITAL_SIGNAL_TYPE_40_GigE = 873416031;
    public static final String _DIGITAL_SIGNAL_TYPE_40_GigE_ = "DIGITAL_SIGNAL_TYPE_40_GigE";
    public static final int    _DIGITAL_SIGNAL_TYPE_OC_192 = 1780575663;
    public static final String _DIGITAL_SIGNAL_TYPE_OC_192_ = "DIGITAL_SIGNAL_TYPE_OC_192";
    public static final int    _DIGITAL_SIGNAL_TYPE_10_GigE_LAN = 1135684615;
    public static final String _DIGITAL_SIGNAL_TYPE_10_GigE_LAN_ = "DIGITAL_SIGNAL_TYPE_10_GigE_LAN";
    public static final int    _DIGITAL_SIGNAL_TYPE_OC_3 = 1704994511;
    public static final String _DIGITAL_SIGNAL_TYPE_OC_3_ = "DIGITAL_SIGNAL_TYPE_OC_3";
    public static final int    _DIGITAL_SIGNAL_TYPE_OC_48 = 101552872;
    public static final String _DIGITAL_SIGNAL_TYPE_OC_48_ = "DIGITAL_SIGNAL_TYPE_OC_48";
    public static final int    _DIGITAL_SIGNAL_TYPE_FC_200 = 1879203882;
    public static final String _DIGITAL_SIGNAL_TYPE_FC_200_ = "DIGITAL_SIGNAL_TYPE_FC_200";
    public static final int    _DIGITAL_SIGNAL_TYPE_IB_SDR = 1843857672;
    public static final String _DIGITAL_SIGNAL_TYPE_IB_SDR_ = "DIGITAL_SIGNAL_TYPE_IB_SDR";
    public static final int    _DIGITAL_SIGNAL_TYPE_FC_400 = 1522990216;
    public static final String _DIGITAL_SIGNAL_TYPE_FC_400_ = "DIGITAL_SIGNAL_TYPE_FC_400";
    public static final int    _DIGITAL_SIGNAL_TYPE_OTU_3 = 1535414814;
    public static final String _DIGITAL_SIGNAL_TYPE_OTU_3_ = "DIGITAL_SIGNAL_TYPE_OTU_3";
    public static final int    _DIGITAL_SIGNAL_TYPE_OC_12 = 185909104;
    public static final String _DIGITAL_SIGNAL_TYPE_OC_12_ = "DIGITAL_SIGNAL_TYPE_OC_12";
    public static final int    _DIGITAL_SIGNAL_TYPE_10_GigE_WAN = 114186678;
    public static final String _DIGITAL_SIGNAL_TYPE_10_GigE_WAN_ = "DIGITAL_SIGNAL_TYPE_10_GigE_WAN";
    public static final int    _DIGITAL_SIGNAL_TYPE_XGPON = 1312661896;
    public static final String _DIGITAL_SIGNAL_TYPE_XGPON_ = "DIGITAL_SIGNAL_TYPE_XGPON";
    public static final int    _DIGITAL_SIGNAL_TYPE_FC_1200 = 702518682;
    public static final String _DIGITAL_SIGNAL_TYPE_FC_1200_ = "DIGITAL_SIGNAL_TYPE_FC_1200";
    public static final int    _DIGITAL_SIGNAL_TYPE_OTU_2 = 482484387;
    public static final String _DIGITAL_SIGNAL_TYPE_OTU_2_ = "DIGITAL_SIGNAL_TYPE_OTU_2";
    public static final int    _DIGITAL_SIGNAL_TYPE = 177993747;
    public static final String _DIGITAL_SIGNAL_TYPE_ = "DIGITAL_SIGNAL_TYPE";
    public static final int    _DIGITAL_SIGNAL_TYPE_STM_4 = 459340244;
    public static final String _DIGITAL_SIGNAL_TYPE_STM_4_ = "DIGITAL_SIGNAL_TYPE_STM_4";
    public static final int    _DIGITAL_SIGNAL_TYPE_GigE = 865947985;
    public static final String _DIGITAL_SIGNAL_TYPE_GigE_ = "DIGITAL_SIGNAL_TYPE_GigE";
    public static final int    _DIGITAL_SIGNAL_TYPE_OC_768 = 2073484126;
    public static final String _DIGITAL_SIGNAL_TYPE_OC_768_ = "DIGITAL_SIGNAL_TYPE_OC_768";
    public static final int    _DIGITAL_SIGNAL_TYPE_STM_256 = 992886415;
    public static final String _DIGITAL_SIGNAL_TYPE_STM_256_ = "DIGITAL_SIGNAL_TYPE_STM_256";
    public static final int    _DIGITAL_SIGNAL_TYPE_OTU_1 = 1511935773;
    public static final String _DIGITAL_SIGNAL_TYPE_OTU_1_ = "DIGITAL_SIGNAL_TYPE_OTU_1";
    public static final int    _DIGITAL_SIGNAL_TYPE_FC_100 = 1816089985;
    public static final String _DIGITAL_SIGNAL_TYPE_FC_100_ = "DIGITAL_SIGNAL_TYPE_FC_100";
    public static final int    _DIGITAL_SIGNAL_TYPE_SDI_1G5 = 671038335;
    public static final String _DIGITAL_SIGNAL_TYPE_SDI_1G5_ = "DIGITAL_SIGNAL_TYPE_SDI_1G5";
    public static final int    _DIGITAL_SIGNAL_TYPE_SDI = 1866076056;
    public static final String _DIGITAL_SIGNAL_TYPE_SDI_ = "DIGITAL_SIGNAL_TYPE_SDI";
    public static final int    _DIGITAL_SIGNAL_TYPE_FC_3200 = 2119812674;
    public static final String _DIGITAL_SIGNAL_TYPE_FC_3200_ = "DIGITAL_SIGNAL_TYPE_FC_3200";
    public static final int    _DIGITAL_SIGNAL_TYPE_OTU_4 = 1411413588;
    public static final String _DIGITAL_SIGNAL_TYPE_OTU_4_ = "DIGITAL_SIGNAL_TYPE_OTU_4";
    public static final int    _DIGITAL_SIGNAL_TYPE_SBCON_ESCON = 505860746;
    public static final String _DIGITAL_SIGNAL_TYPE_SBCON_ESCON_ = "DIGITAL_SIGNAL_TYPE_SBCON_ESCON";
    public static final int    _DIGITAL_SIGNAL_TYPE_FC_800 = 906512116;
    public static final String _DIGITAL_SIGNAL_TYPE_FC_800_ = "DIGITAL_SIGNAL_TYPE_FC_800";
    public static final int    _DIGITAL_SIGNAL_TYPE_STM_16 = 520421086;
    public static final String _DIGITAL_SIGNAL_TYPE_STM_16_ = "DIGITAL_SIGNAL_TYPE_STM_16";
    public static final int    _DIGITAL_SIGNAL_TYPE_GPON = 1813923070;
    public static final String _DIGITAL_SIGNAL_TYPE_GPON_ = "DIGITAL_SIGNAL_TYPE_GPON";
    public static final int    _DIGITAL_SIGNAL_TYPE_FC_1600 = 918848199;
    public static final String _DIGITAL_SIGNAL_TYPE_FC_1600_ = "DIGITAL_SIGNAL_TYPE_FC_1600";
    public static final int    _DIGITAL_SIGNAL_TYPE_IB_DDR = 1335959567;
    public static final String _DIGITAL_SIGNAL_TYPE_IB_DDR_ = "DIGITAL_SIGNAL_TYPE_IB_DDR";
    public static final int    _DIGITAL_SIGNAL_TYPE_STM_1 = 619769271;
    public static final String _DIGITAL_SIGNAL_TYPE_STM_1_ = "DIGITAL_SIGNAL_TYPE_STM_1";
    public static final int    _DIGITAL_SIGNAL_TYPE_STM_64 = 1764531440;
    public static final String _DIGITAL_SIGNAL_TYPE_STM_64_ = "DIGITAL_SIGNAL_TYPE_STM_64";
}
