/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/tapi-virtual-network.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.onftapi.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module tapi-virtual-network.yang */
public class tapiVirtualNetwork extends ConfNamespace {
    public static final int hash = 1635128252;
    public int hash() {
        return tapiVirtualNetwork.hash;
    }

    public static final String id = "_onf-tapi-nc-2.0:onf-tapi-nc-2.0#urn:onf:otcc:yang:tapi-virtual-network";
    public String id() {
        return tapiVirtualNetwork.id;
    }

    public static final String uri = "_onf-tapi-nc-2.0:onf-tapi-nc-2.0#urn:onf:otcc:yang:tapi-virtual-network";
    public String uri() {
        return tapiVirtualNetwork.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(tapiVirtualNetwork.uri);
    }

    public static final String prefix = "tapi-virtual-network";
    public String prefix() {
        return tapiVirtualNetwork.prefix;
    }

    public tapiVirtualNetwork() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _requested_capacity = 1494104319;
    public static final String _requested_capacity_ = "requested-capacity";
    public static final int    _jitter_characteristic = 1298437386;
    public static final String _jitter_characteristic_ = "jitter-characteristic";
    public static final int    _info = 2062105651;
    public static final String _info_ = "info";
    public static final int    _service_level = 407325380;
    public static final String _service_level_ = "service-level";
    public static final int    _administrative_state = 1048557234;
    public static final String _administrative_state_ = "administrative-state";
    public static final int    _service_layer = 1525259740;
    public static final String _service_layer_ = "service-layer";
    public static final int    _service_id_or_name = 306695823;
    public static final String _service_id_or_name_ = "service-id-or-name";
    public static final int    _cost_value = 932572282;
    public static final String _cost_value_ = "cost-value";
    public static final int    _total_size = 2093478719;
    public static final String _total_size_ = "total-size";
    public static final int    _virtual_nw_service_uuid = 1953981026;
    public static final String _virtual_nw_service_uuid_ = "virtual-nw-service-uuid";
    public static final int    _peak_information_rate = 433582594;
    public static final String _peak_information_rate_ = "peak-information-rate";
    public static final int    _result = 401396173;
    public static final String _result_ = "result";
    public static final int    _uuid = 328053038;
    public static final String _uuid_ = "uuid";
    public static final int    _src_service_end_point = 1504221107;
    public static final String _src_service_end_point_ = "src-service-end-point";
    public static final int    _device = 617911018;
    public static final String _device_ = "device";
    public static final int    _cost_characteristic = 1763202494;
    public static final String _cost_characteristic_ = "cost-characteristic";
    public static final int    _get_virtual_network_service_list = 1158537721;
    public static final String _get_virtual_network_service_list_ = "get-virtual-network-service-list";
    public static final int    _delete_virtual_network_service = 1503348724;
    public static final String _delete_virtual_network_service_ = "delete-virtual-network-service";
    public static final int    _value = 864367181;
    public static final String _value_ = "value";
    public static final int    _state = 630973766;
    public static final String _state_ = "state";
    public static final int    _end_point = 935030957;
    public static final String _end_point_ = "end-point";
    public static final int    _sep = 1919146393;
    public static final String _sep_ = "sep";
    public static final int    _value_name = 1213415047;
    public static final String _value_name_ = "value-name";
    public static final int    _fixed_latency_characteristic = 2135091342;
    public static final String _fixed_latency_characteristic_ = "fixed-latency-characteristic";
    public static final int    _service_interface_point_uuid = 1780718047;
    public static final String _service_interface_point_uuid_ = "service-interface-point-uuid";
    public static final int    _role = 1297556411;
    public static final String _role_ = "role";
    public static final int    _operational_state = 1839284571;
    public static final String _operational_state_ = "operational-state";
    public static final int    _latency_characteristic = 256624057;
    public static final String _latency_characteristic_ = "latency-characteristic";
    public static final int    _virtual_nw_service = 1537863917;
    public static final String _virtual_nw_service_ = "virtual-nw-service";
    public static final int    _virtual_network_context = 1293330227;
    public static final String _virtual_network_context_ = "virtual-network-context";
    public static final int    _rpc_get_virtual_network_service_details = 2068260541;
    public static final String _rpc_get_virtual_network_service_details_ = "rpc-get-virtual-network-service-details";
    public static final int    _topology = 333175635;
    public static final String _topology_ = "topology";
    public static final int    _cost_name = 1738788381;
    public static final String _cost_name_ = "cost-name";
    public static final int    _vnw_constraint = 36585476;
    public static final String _vnw_constraint_ = "vnw-constraint";
    public static final int    _direction = 1468062370;
    public static final String _direction_ = "direction";
    public static final int    _traffic_property_name = 2080339994;
    public static final String _traffic_property_name_ = "traffic-property-name";
    public static final int    _create_virtual_network_service = 803488552;
    public static final String _create_virtual_network_service_ = "create-virtual-network-service";
    public static final int    _peak_burst_size = 42505974;
    public static final String _peak_burst_size_ = "peak-burst-size";
    public static final int    _service = 855380710;
    public static final String _service_ = "service";
    public static final int    _bw_profile_type = 649759263;
    public static final String _bw_profile_type_ = "bw-profile-type";
    public static final int    _service_interface_point = 189732751;
    public static final String _service_interface_point_ = "service-interface-point";
    public static final int    _get_virtual_network_service_details = 1298090443;
    public static final String _get_virtual_network_service_details_ = "get-virtual-network-service-details";
    public static final int    _cost_algorithm = 1731447885;
    public static final String _cost_algorithm_ = "cost-algorithm";
    public static final int    _topology_uuid = 403232376;
    public static final String _topology_uuid_ = "topology-uuid";
    public static final int    _rpc_get_virtual_network_service_list = 1267742266;
    public static final String _rpc_get_virtual_network_service_list_ = "rpc-get-virtual-network-service-list";
    public static final int    _schedule = 1642863984;
    public static final String _schedule_ = "schedule";
    public static final int    _name = 1998270519;
    public static final String _name_ = "name";
    public static final int    _sink_service_end_point = 764821335;
    public static final String _sink_service_end_point_ = "sink-service-end-point";
    public static final int    _conn_schedule = 1284911648;
    public static final String _conn_schedule_ = "conn-schedule";
    public static final int    _start_time = 84038180;
    public static final String _start_time_ = "start-time";
    public static final int    _committed_information_rate = 1688165216;
    public static final String _committed_information_rate_ = "committed-information-rate";
    public static final int    _rpc_delete_virtual_network_service = 803842301;
    public static final String _rpc_delete_virtual_network_service_ = "rpc-delete-virtual-network-service";
    public static final int    _layer_protocol_name = 1201135583;
    public static final String _layer_protocol_name_ = "layer-protocol-name";
    public static final int    _bandwidth_profile = 1783571670;
    public static final String _bandwidth_profile_ = "bandwidth-profile";
    public static final int    _diversity_exclusion = 52504632;
    public static final String _diversity_exclusion_ = "diversity-exclusion";
    public static final int    _color_aware = 112024138;
    public static final String _color_aware_ = "color-aware";
    public static final int    _committed_burst_size = 128698928;
    public static final String _committed_burst_size_ = "committed-burst-size";
    public static final int    _unit = 1638458042;
    public static final String _unit_ = "unit";
    public static final int    _queing_latency_characteristic = 2128069169;
    public static final String _queing_latency_characteristic_ = "queing-latency-characteristic";
    public static final int    _coupling_flag = 236387716;
    public static final String _coupling_flag_ = "coupling-flag";
    public static final int    _local_id = 1656047607;
    public static final String _local_id_ = "local-id";
    public static final int    _wander_characteristic = 266620206;
    public static final String _wander_characteristic_ = "wander-characteristic";
    public static final int    _end_time = 1935053864;
    public static final String _end_time_ = "end-time";
    public static final int    _lifecycle_state = 1569301757;
    public static final String _lifecycle_state_ = "lifecycle-state";
    public static final int    _rpc_create_virtual_network_service = 1611747221;
    public static final String _rpc_create_virtual_network_service_ = "rpc-create-virtual-network-service";
}
