/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/tapi-notification.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.onftapi.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module tapi-notification.yang */
public class tapiNotification extends ConfNamespace {
    public static final int hash = 775148353;
    public int hash() {
        return tapiNotification.hash;
    }

    public static final String id = "_onf-tapi-nc-2.0:onf-tapi-nc-2.0#urn:onf:otcc:yang:tapi-notification";
    public String id() {
        return tapiNotification.id;
    }

    public static final String uri = "_onf-tapi-nc-2.0:onf-tapi-nc-2.0#urn:onf:otcc:yang:tapi-notification";
    public String uri() {
        return tapiNotification.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(tapiNotification.uri);
    }

    public static final String prefix = "tapi-notification";
    public String prefix() {
        return tapiNotification.prefix;
    }

    public tapiNotification() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _rpc_get_supported_notification_types = 1056573729;
    public static final String _rpc_get_supported_notification_types_ = "rpc-get-supported-notification-types";
    public static final int    _is_transient = 1352801782;
    public static final String _is_transient_ = "is-transient";
    public static final int    _info = 2062105651;
    public static final String _info_ = "info";
    public static final int    _rpc_update_notification_subscription_service = 606577620;
    public static final String _rpc_update_notification_subscription_service_ = "rpc-update-notification-subscription-service";
    public static final int    _old_value = 1071493427;
    public static final String _old_value_ = "old-value";
    public static final int    _probable_cause = 1241890965;
    public static final String _probable_cause_ = "probable-cause";
    public static final int    _additional_info = 530540559;
    public static final String _additional_info_ = "additional-info";
    public static final int    _threshold_crossing = 816004232;
    public static final String _threshold_crossing_ = "threshold-crossing";
    public static final int    _event_time_stamp = 1710958470;
    public static final String _event_time_stamp_ = "event-time-stamp";
    public static final int    _notification_type = 396353504;
    public static final String _notification_type_ = "notification-type";
    public static final int    _rpc_create_notification_subscription_service = 1486976820;
    public static final String _rpc_create_notification_subscription_service_ = "rpc-create-notification-subscription-service";
    public static final int    _suspect_interval_flag = 1284355977;
    public static final String _suspect_interval_flag_ = "suspect-interval-flag";
    public static final int    _delete_notification_subscription_service = 1970368169;
    public static final String _delete_notification_subscription_service_ = "delete-notification-subscription-service";
    public static final int    _target_object_identifier = 1647813660;
    public static final String _target_object_identifier_ = "target-object-identifier";
    public static final int    _additional_text = 1484324691;
    public static final String _additional_text_ = "additional-text";
    public static final int    _result = 401396173;
    public static final String _result_ = "result";
    public static final int    _rpc_delete_notification_subscription_service = 1364266422;
    public static final String _rpc_delete_notification_subscription_service_ = "rpc-delete-notification-subscription-service";
    public static final int    _uuid = 328053038;
    public static final String _uuid_ = "uuid";
    public static final int    _device = 617911018;
    public static final String _device_ = "device";
    public static final int    _next_sequence_no = 2086145531;
    public static final String _next_sequence_no_ = "next-sequence-no";
    public static final int    _requested_notification_types = 1804139154;
    public static final String _requested_notification_types_ = "requested-notification-types";
    public static final int    _value = 864367181;
    public static final String _value_ = "value";
    public static final int    _value_name = 1213415047;
    public static final String _value_name_ = "value-name";
    public static final int    _tca_info = 1406432831;
    public static final String _tca_info_ = "tca-info";
    public static final int    _rpc_get_notification_subscription_service_details = 1747185662;
    public static final String _rpc_get_notification_subscription_service_details_ = "rpc-get-notification-subscription-service-details";
    public static final int    _rpc_get_notification_subscription_service_list = 797953779;
    public static final String _rpc_get_notification_subscription_service_list_ = "rpc-get-notification-subscription-service-list";
    public static final int    _requested_object_types = 524856336;
    public static final String _requested_object_types_ = "requested-object-types";
    public static final int    _update_notification_subscription_service = 463206927;
    public static final String _update_notification_subscription_service_ = "update-notification-subscription-service";
    public static final int    _supported_notification_types = 1240171085;
    public static final String _supported_notification_types_ = "supported-notification-types";
    public static final int    _perceived_severity = 1194414666;
    public static final String _perceived_severity_ = "perceived-severity";
    public static final int    _subscription_service = 694536128;
    public static final String _subscription_service_ = "subscription-service";
    public static final int    _target_object_type = 1894238495;
    public static final String _target_object_type_ = "target-object-type";
    public static final int    _subscription_state = 995841602;
    public static final String _subscription_state_ = "subscription-state";
    public static final int    _requested_layer_protocols = 205432308;
    public static final String _requested_layer_protocols_ = "requested-layer-protocols";
    public static final int    _notification = 232240424;
    public static final String _notification_ = "notification";
    public static final int    _source_indicator = 1141980204;
    public static final String _source_indicator_ = "source-indicator";
    public static final int    _subscription_filter = 723356419;
    public static final String _subscription_filter_ = "subscription-filter";
    public static final int    _notif_subscription = 1611600938;
    public static final String _notif_subscription_ = "notif-subscription";
    public static final int    _notification_context = 1483439381;
    public static final String _notification_context_ = "notification-context";
    public static final int    _threshold_value = 1520366978;
    public static final String _threshold_value_ = "threshold-value";
    public static final int    _get_notification_subscription_service_details = 739927294;
    public static final String _get_notification_subscription_service_details_ = "get-notification-subscription-service-details";
    public static final int    _rpc_get_notification_list = 709078519;
    public static final String _rpc_get_notification_list_ = "rpc-get-notification-list";
    public static final int    _target_object_name = 1199945035;
    public static final String _target_object_name_ = "target-object-name";
    public static final int    _threshold_parameter = 1056138929;
    public static final String _threshold_parameter_ = "threshold-parameter";
    public static final int    _get_notification_list = 1217021554;
    public static final String _get_notification_list_ = "get-notification-list";
    public static final int    _sequence_number = 996433488;
    public static final String _sequence_number_ = "sequence-number";
    public static final int    _get_notification_subscription_service_list = 155531374;
    public static final String _get_notification_subscription_service_list_ = "get-notification-subscription-service-list";
    public static final int    _changed_attributes = 156001748;
    public static final String _changed_attributes_ = "changed-attributes";
    public static final int    _supported_object_types = 80313752;
    public static final String _supported_object_types_ = "supported-object-types";
    public static final int    _name = 1998270519;
    public static final String _name_ = "name";
    public static final int    _new_value = 1772954341;
    public static final String _new_value_ = "new-value";
    public static final int    _stream_address = 412960947;
    public static final String _stream_address_ = "stream-address";
    public static final int    _requested_object_identifier = 348803646;
    public static final String _requested_object_identifier_ = "requested-object-identifier";
    public static final int    _subscription_id_or_name = 696193138;
    public static final String _subscription_id_or_name_ = "subscription-id-or-name";
    public static final int    _layer_protocol_name = 1201135583;
    public static final String _layer_protocol_name_ = "layer-protocol-name";
    public static final int    _measurement_interval = 1103021035;
    public static final String _measurement_interval_ = "measurement-interval";
    public static final int    _service_affecting = 8569410;
    public static final String _service_affecting_ = "service-affecting";
    public static final int    _time_period = 834271090;
    public static final String _time_period_ = "time-period";
    public static final int    _create_notification_subscription_service = 567731662;
    public static final String _create_notification_subscription_service_ = "create-notification-subscription-service";
    public static final int    _alarm_info = 1737377107;
    public static final String _alarm_info_ = "alarm-info";
    public static final int    _get_supported_notification_types = 1027849817;
    public static final String _get_supported_notification_types_ = "get-supported-notification-types";
    public static final int    _local_id = 1656047607;
    public static final String _local_id_ = "local-id";
    public static final int    _notification_channel = 1158685225;
    public static final String _notification_channel_ = "notification-channel";
    public static final int    _include_content = 760111561;
    public static final String _include_content_ = "include-content";
}
