/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/tapi-topology.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.onftapi.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module tapi-topology.yang */
public class tapiTopology extends ConfNamespace {
    public static final int hash = 1685510783;
    public int hash() {
        return tapiTopology.hash;
    }

    public static final String id = "_onf-tapi-nc-2.0:onf-tapi-nc-2.0#urn:onf:otcc:yang:tapi-topology";
    public String id() {
        return tapiTopology.id;
    }

    public static final String uri = "_onf-tapi-nc-2.0:onf-tapi-nc-2.0#urn:onf:otcc:yang:tapi-topology";
    public String uri() {
        return tapiTopology.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(tapiTopology.uri);
    }

    public static final String prefix = "tapi-topology";
    public String prefix() {
        return tapiTopology.prefix;
    }

    public tapiTopology() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _SIGNAL_PROPERTY_VALUE_RULE_NOT_VALUE = 1413833720;
    public static final String _SIGNAL_PROPERTY_VALUE_RULE_NOT_VALUE_ = "SIGNAL_PROPERTY_VALUE_RULE_NOT_VALUE";
    public static final int    _PORT_ROLE_RULE_OPTION_DIFFERENT_ROLE = 1210967554;
    public static final String _PORT_ROLE_RULE_OPTION_DIFFERENT_ROLE_ = "PORT_ROLE_RULE_OPTION_DIFFERENT_ROLE";
    public static final int    _jitter_characteristic = 1298437386;
    public static final String _jitter_characteristic_ = "jitter-characteristic";
    public static final int    _get_node_edge_point_details = 1563526070;
    public static final String _get_node_edge_point_details_ = "get-node-edge-point-details";
    public static final int    _node_edge_point_uuid = 529992441;
    public static final String _node_edge_point_uuid_ = "node-edge-point-uuid";
    public static final int    _risk_identifier_list = 2008723404;
    public static final String _risk_identifier_list_ = "risk-identifier-list";
    public static final int    _info = 2062105651;
    public static final String _info_ = "info";
    public static final int    _error_characteristic = 266158978;
    public static final String _error_characteristic_ = "error-characteristic";
    public static final int    _get_node_details = 1642920668;
    public static final String _get_node_details_ = "get-node-details";
    public static final int    _node_edge_point = 174790718;
    public static final String _node_edge_point_ = "node-edge-point";
    public static final int    _rule = 661146188;
    public static final String _rule_ = "rule";
    public static final int    _transitioned_layer_protocol_name = 1482911679;
    public static final String _transitioned_layer_protocol_name_ = "transitioned-layer-protocol-name";
    public static final int    _rpc_get_node_details = 546709313;
    public static final String _rpc_get_node_details_ = "rpc-get-node-details";
    public static final int    _node_id_or_name = 1235196316;
    public static final String _node_id_or_name_ = "node-id-or-name";
    public static final int    _nw_topology_service = 817742818;
    public static final String _nw_topology_service_ = "nw-topology-service";
    public static final int    _validation_robustness = 1325810355;
    public static final String _validation_robustness_ = "validation-robustness";
    public static final int    _cep_port_role = 1476330252;
    public static final String _cep_port_role_ = "cep-port-role";
    public static final int    _PORT_ROLE_RULE_OPTION_NOT_ROLE = 39605451;
    public static final String _PORT_ROLE_RULE_OPTION_NOT_ROLE_ = "PORT_ROLE_RULE_OPTION_NOT_ROLE";
    public static final int    _administrative_state = 1048557234;
    public static final String _administrative_state_ = "administrative-state";
    public static final int    _cost_value = 932572282;
    public static final String _cost_value_ = "cost-value";
    public static final int    _total_size = 2093478719;
    public static final String _total_size_ = "total-size";
    public static final int    _connection_spec_reference = 975106418;
    public static final String _connection_spec_reference_ = "connection-spec-reference";
    public static final int    _rpc_get_topology_list = 1025884936;
    public static final String _rpc_get_topology_list_ = "rpc-get-topology-list";
    public static final int    _inter_rule_group = 1719013189;
    public static final String _inter_rule_group_ = "inter-rule-group";
    public static final int    _protection_type = 832029373;
    public static final String _protection_type_ = "protection-type";
    public static final int    _connection_spec_id = 1098416816;
    public static final String _connection_spec_id_ = "connection-spec-id";
    public static final int    _peak_information_rate = 433582594;
    public static final String _peak_information_rate_ = "peak-information-rate";
    public static final int    _result = 401396173;
    public static final String _result_ = "result";
    public static final int    _risk_characteristic_name = 299163717;
    public static final String _risk_characteristic_name_ = "risk-characteristic-name";
    public static final int    _rpc_get_topology_details = 1510919556;
    public static final String _rpc_get_topology_details_ = "rpc-get-topology-details";
    public static final int    _uuid = 328053038;
    public static final String _uuid_ = "uuid";
    public static final int    _signal_property_value_rule = 288141587;
    public static final String _signal_property_value_rule_ = "signal-property-value-rule";
    public static final int    _device = 617911018;
    public static final String _device_ = "device";
    public static final int    _signal_property_name = 1478037760;
    public static final String _signal_property_name_ = "signal-property-name";
    public static final int    _cost_characteristic = 1763202494;
    public static final String _cost_characteristic_ = "cost-characteristic";
    public static final int    _layer_protocol_qualifier = 1786424353;
    public static final String _layer_protocol_qualifier_ = "layer-protocol-qualifier";
    public static final int    _value = 864367181;
    public static final String _value_ = "value";
    public static final int    _port_role_rule = 6301143;
    public static final String _port_role_rule_ = "port-role-rule";
    public static final int    _applicable_signal_value = 1102993349;
    public static final String _applicable_signal_value_ = "applicable-signal-value";
    public static final int    _value_name = 1213415047;
    public static final String _value_name_ = "value-name";
    public static final int    _fixed_latency_characteristic = 2135091342;
    public static final String _fixed_latency_characteristic_ = "fixed-latency-characteristic";
    public static final int    _signal_property = 32537951;
    public static final String _signal_property_ = "signal-property";
    public static final int    _topology_context = 116781293;
    public static final String _topology_context_ = "topology-context";
    public static final int    _service_interface_point_uuid = 1780718047;
    public static final String _service_interface_point_uuid_ = "service-interface-point-uuid";
    public static final int    _ep_id_or_name = 1182912974;
    public static final String _ep_id_or_name_ = "ep-id-or-name";
    public static final int    _number_of_signal_values = 1583484172;
    public static final String _number_of_signal_values_ = "number-of-signal-values";
    public static final int    _restoration_policy = 1641434548;
    public static final String _restoration_policy_ = "restoration-policy";
    public static final int    _operational_state = 1839284571;
    public static final String _operational_state_ = "operational-state";
    public static final int    _termination_state = 1429446187;
    public static final String _termination_state_ = "termination-state";
    public static final int    _aggregated_node_edge_point = 2121362652;
    public static final String _aggregated_node_edge_point_ = "aggregated-node-edge-point";
    public static final int    _topology_id_or_name = 547207211;
    public static final String _topology_id_or_name_ = "topology-id-or-name";
    public static final int    _server_integrity_process_characteristic = 1897792221;
    public static final String _server_integrity_process_characteristic_ = "server-integrity-process-characteristic";
    public static final int    _complex_rule = 391253057;
    public static final String _complex_rule_ = "complex-rule";
    public static final int    _latency_characteristic = 256624057;
    public static final String _latency_characteristic_ = "latency-characteristic";
    public static final int    _node_rule_group = 1168092929;
    public static final String _node_rule_group_ = "node-rule-group";
    public static final int    _topology = 333175635;
    public static final String _topology_ = "topology";
    public static final int    _cost_name = 1738788381;
    public static final String _cost_name_ = "cost-name";
    public static final int    _rpc_get_link_details = 1342186239;
    public static final String _rpc_get_link_details_ = "rpc-get-link-details";
    public static final int    _get_topology_list = 1253313343;
    public static final String _get_topology_list_ = "get-topology-list";
    public static final int    _associated_node_rule_group = 196296447;
    public static final String _associated_node_rule_group_ = "associated-node-rule-group";
    public static final int    _node = 2084421367;
    public static final String _node_ = "node";
    public static final int    _rpc_get_node_edge_point_details = 709945455;
    public static final String _rpc_get_node_edge_point_details_ = "rpc-get-node-edge-point-details";
    public static final int    _mapped_service_interface_point = 1218458793;
    public static final String _mapped_service_interface_point_ = "mapped-service-interface-point";
    public static final int    _node_rule_group_uuid = 326010516;
    public static final String _node_rule_group_uuid_ = "node-rule-group-uuid";
    public static final int    _layer_protocol_adjacency_validated = 289585593;
    public static final String _layer_protocol_adjacency_validated_ = "layer-protocol-adjacency-validated";
    public static final int    _direction = 1468062370;
    public static final String _direction_ = "direction";
    public static final int    _traffic_property_name = 2080339994;
    public static final String _traffic_property_name_ = "traffic-property-name";
    public static final int    _SIGNAL_PROPERTY_VALUE_RULE_ANY_VALUE = 57848099;
    public static final String _SIGNAL_PROPERTY_VALUE_RULE_ANY_VALUE_ = "SIGNAL_PROPERTY_VALUE_RULE_ANY_VALUE";
    public static final int    _port_role = 1323529581;
    public static final String _port_role_ = "port-role";
    public static final int    _owned_node_edge_point = 262556040;
    public static final String _owned_node_edge_point_ = "owned-node-edge-point";
    public static final int    _total_potential_capacity = 1584610644;
    public static final String _total_potential_capacity_ = "total-potential-capacity";
    public static final int    _get_link_details = 762476862;
    public static final String _get_link_details_ = "get-link-details";
    public static final int    _peak_burst_size = 42505974;
    public static final String _peak_burst_size_ = "peak-burst-size";
    public static final int    _delivery_order_characteristic = 1073987131;
    public static final String _delivery_order_characteristic_ = "delivery-order-characteristic";
    public static final int    _PORT_ROLE_RULE_OPTION = 28204398;
    public static final String _PORT_ROLE_RULE_OPTION_ = "PORT_ROLE_RULE_OPTION";
    public static final int    _bw_profile_type = 649759263;
    public static final String _bw_profile_type_ = "bw-profile-type";
    public static final int    _forwarding_rule = 537071209;
    public static final String _forwarding_rule_ = "forwarding-rule";
    public static final int    _SIGNAL_PROPERTY_VALUE_RULE_SAME_VALUE = 247071612;
    public static final String _SIGNAL_PROPERTY_VALUE_RULE_SAME_VALUE_ = "SIGNAL_PROPERTY_VALUE_RULE_SAME_VALUE";
    public static final int    _available_capacity = 428510579;
    public static final String _available_capacity_ = "available-capacity";
    public static final int    _supported_cep_layer_protocol_qualifier = 1401945003;
    public static final String _supported_cep_layer_protocol_qualifier_ = "supported-cep-layer-protocol-qualifier";
    public static final int    _cost_algorithm = 1731447885;
    public static final String _cost_algorithm_ = "cost-algorithm";
    public static final int    _topology_uuid = 403232376;
    public static final String _topology_uuid_ = "topology-uuid";
    public static final int    _PORT_ROLE_RULE_OPTION_ANY_ROLE = 656525798;
    public static final String _PORT_ROLE_RULE_OPTION_ANY_ROLE_ = "PORT_ROLE_RULE_OPTION_ANY_ROLE";
    public static final int    _node_uuid = 797539952;
    public static final String _node_uuid_ = "node-uuid";
    public static final int    _repeat_delivery_characteristic = 1879285536;
    public static final String _repeat_delivery_characteristic_ = "repeat-delivery-characteristic";
    public static final int    _connection_spec_name = 179000224;
    public static final String _connection_spec_name_ = "connection-spec-name";
    public static final int    _risk_characteristic = 1960238072;
    public static final String _risk_characteristic_ = "risk-characteristic";
    public static final int    _link_id_or_name = 56970228;
    public static final String _link_id_or_name_ = "link-id-or-name";
    public static final int    _name = 1998270519;
    public static final String _name_ = "name";
    public static final int    _resilience_type = 1810976984;
    public static final String _resilience_type_ = "resilience-type";
    public static final int    _link = 481374722;
    public static final String _link_ = "link";
    public static final int    _loss_characteristic = 1587373003;
    public static final String _loss_characteristic_ = "loss-characteristic";
    public static final int    _validation_mechanism = 810062337;
    public static final String _validation_mechanism_ = "validation-mechanism";
    public static final int    _link_port_role = 1034321958;
    public static final String _link_port_role_ = "link-port-role";
    public static final int    _get_topology_details = 763339961;
    public static final String _get_topology_details_ = "get-topology-details";
    public static final int    _rule_type = 508857660;
    public static final String _rule_type_ = "rule-type";
    public static final int    _committed_information_rate = 1688165216;
    public static final String _committed_information_rate_ = "committed-information-rate";
    public static final int    _layer_protocol_name = 1201135583;
    public static final String _layer_protocol_name_ = "layer-protocol-name";
    public static final int    _SIGNAL_PROPERTY_VALUE_RULE = 2129103615;
    public static final String _SIGNAL_PROPERTY_VALUE_RULE_ = "SIGNAL_PROPERTY_VALUE_RULE";
    public static final int    _override_priority = 2116545420;
    public static final String _override_priority_ = "override-priority";
    public static final int    _bandwidth_profile = 1783571670;
    public static final String _bandwidth_profile_ = "bandwidth-profile";
    public static final int    _encap_topology = 1512585430;
    public static final String _encap_topology_ = "encap-topology";
    public static final int    _link_port_direction = 1472924916;
    public static final String _link_port_direction_ = "link-port-direction";
    public static final int    _color_aware = 112024138;
    public static final String _color_aware_ = "color-aware";
    public static final int    _committed_burst_size = 128698928;
    public static final String _committed_burst_size_ = "committed-burst-size";
    public static final int    _unit = 1638458042;
    public static final String _unit_ = "unit";
    public static final int    _SIGNAL_PROPERTY_VALUE_RULE_DIFFERENT_VALUE = 1410729879;
    public static final String _SIGNAL_PROPERTY_VALUE_RULE_DIFFERENT_VALUE_ = "SIGNAL_PROPERTY_VALUE_RULE_DIFFERENT_VALUE";
    public static final int    _queing_latency_characteristic = 2128069169;
    public static final String _queing_latency_characteristic_ = "queing-latency-characteristic";
    public static final int    _coupling_flag = 236387716;
    public static final String _coupling_flag_ = "coupling-flag";
    public static final int    _termination_direction = 881445345;
    public static final String _termination_direction_ = "termination-direction";
    public static final int    _local_id = 1656047607;
    public static final String _local_id_ = "local-id";
    public static final int    _cep_direction = 1531959626;
    public static final String _cep_direction_ = "cep-direction";
    public static final int    _unavailable_time_characteristic = 1938117723;
    public static final String _unavailable_time_characteristic_ = "unavailable-time-characteristic";
    public static final int    _wander_characteristic = 266620206;
    public static final String _wander_characteristic_ = "wander-characteristic";
    public static final int    _lifecycle_state = 1569301757;
    public static final String _lifecycle_state_ = "lifecycle-state";
    public static final int    _PORT_ROLE_RULE_OPTION_SAME_ROLE = 1961349123;
    public static final String _PORT_ROLE_RULE_OPTION_SAME_ROLE_ = "PORT_ROLE_RULE_OPTION_SAME_ROLE";
}
