/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/tapi-photonic-media.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.onftapi.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module tapi-photonic-media.yang */
public class tapiPhotonicMedia extends ConfNamespace {
    public static final int hash = 1489495270;
    public int hash() {
        return tapiPhotonicMedia.hash;
    }

    public static final String id = "_onf-tapi-nc-2.0:onf-tapi-nc-2.0#urn:onf:otcc:yang:tapi-photonic-media";
    public String id() {
        return tapiPhotonicMedia.id;
    }

    public static final String uri = "_onf-tapi-nc-2.0:onf-tapi-nc-2.0#urn:onf:otcc:yang:tapi-photonic-media";
    public String uri() {
        return tapiPhotonicMedia.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(tapiPhotonicMedia.uri);
    }

    public static final String prefix = "tapi-photonic-media";
    public String prefix() {
        return tapiPhotonicMedia.prefix;
    }

    public tapiPhotonicMedia() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _number_of_otsi = 16788745;
    public static final String _number_of_otsi_ = "number-of-otsi";
    public static final int    _supportable_central_frequency_spectrum_band = 1424283212;
    public static final String _supportable_central_frequency_spectrum_band_ = "supportable-central-frequency-spectrum-band";
    public static final int    _selected_application_identifier = 873682762;
    public static final String _selected_application_identifier_ = "selected-application-identifier";
    public static final int    _measured_power_egress = 249858064;
    public static final String _measured_power_egress_ = "measured-power-egress";
    public static final int    _selected_spectrum = 2074570969;
    public static final String _selected_spectrum_ = "selected-spectrum";
    public static final int    _power_management_config_pac = 2045328945;
    public static final String _power_management_config_pac_ = "power-management-config-pac";
    public static final int    _mc_pool = 799483094;
    public static final String _mc_pool_ = "mc-pool";
    public static final int    _supportable_maximum_output_power = 1410662816;
    public static final String _supportable_maximum_output_power_ = "supportable-maximum-output-power";
    public static final int    _total_power_warn_threshold = 7490139;
    public static final String _total_power_warn_threshold_ = "total-power-warn-threshold";
    public static final int    _total_power_lower_warn_threshold_min = 793901280;
    public static final String _total_power_lower_warn_threshold_min_ = "total-power-lower-warn-threshold-min";
    public static final int    _selected_central_frequency = 1084479587;
    public static final String _selected_central_frequency_ = "selected-central-frequency";
    public static final int    _tolerable_minimum_input_power = 57423496;
    public static final String _tolerable_minimum_input_power_ = "tolerable-minimum-input-power";
    public static final int    _PHOTONIC_LAYER_QUALIFIER_SMCA = 563916387;
    public static final String _PHOTONIC_LAYER_QUALIFIER_SMCA_ = "PHOTONIC_LAYER_QUALIFIER_SMCA";
    public static final int    _lower_frequency = 297729851;
    public static final String _lower_frequency_ = "lower-frequency";
    public static final int    _laser_properties = 1728028136;
    public static final String _laser_properties_ = "laser-properties";
    public static final int    _PHOTONIC_LAYER_QUALIFIER_NMCA = 977157501;
    public static final String _PHOTONIC_LAYER_QUALIFIER_NMCA_ = "PHOTONIC_LAYER_QUALIFIER_NMCA";
    public static final int    _expected_maximum_input_power = 216273919;
    public static final String _expected_maximum_input_power_ = "expected-maximum-input-power";
    public static final int    _laser_application_type = 1038006195;
    public static final String _laser_application_type_ = "laser-application-type";
    public static final int    _otsi_config = 1606855622;
    public static final String _otsi_config_ = "otsi-config";
    public static final int    _expected_minimum_input_power = 1185785553;
    public static final String _expected_minimum_input_power_ = "expected-minimum-input-power";
    public static final int    _PHOTONIC_LAYER_QUALIFIER = 616080523;
    public static final String _PHOTONIC_LAYER_QUALIFIER_ = "PHOTONIC_LAYER_QUALIFIER";
    public static final int    _media_channel_connection_end_point_spec = 1509962770;
    public static final String _media_channel_connection_end_point_spec_ = "media-channel-connection-end-point-spec";
    public static final int    _PHOTONIC_LAYER_QUALIFIER_OTSi = 435985502;
    public static final String _PHOTONIC_LAYER_QUALIFIER_OTSi_ = "PHOTONIC_LAYER_QUALIFIER_OTSi";
    public static final int    _frequency_constraint = 2027787218;
    public static final String _frequency_constraint_ = "frequency-constraint";
    public static final int    _media_channel_service_interface_point_spec = 1056251406;
    public static final String _media_channel_service_interface_point_spec_ = "media-channel-service-interface-point-spec";
    public static final int    _total_power_upper_warn_threshold_min = 16318401;
    public static final String _total_power_upper_warn_threshold_min_ = "total-power-upper-warn-threshold-min";
    public static final int    _value = 864367181;
    public static final String _value_ = "value";
    public static final int    _ots_connection_end_point_spec = 267429676;
    public static final String _ots_connection_end_point_spec_ = "ots-connection-end-point-spec";
    public static final int    _value_name = 1213415047;
    public static final String _value_name_ = "value-name";
    public static final int    _otsi_assembly_connection_end_point_spec = 234891528;
    public static final String _otsi_assembly_connection_end_point_spec_ = "otsi-assembly-connection-end-point-spec";
    public static final int    _ots_media_channel = 1703572004;
    public static final String _ots_media_channel_ = "ots-media-channel";
    public static final int    _transmited_power = 2115295466;
    public static final String _transmited_power_ = "transmited-power";
    public static final int    _supportable_modulation = 723634142;
    public static final String _supportable_modulation_ = "supportable-modulation";
    public static final int    _laser_temperature = 2109521396;
    public static final String _laser_temperature_ = "laser-temperature";
    public static final int    _occupied_spectrum = 821481400;
    public static final String _occupied_spectrum_ = "occupied-spectrum";
    public static final int    _pre_fec_ber = 930828535;
    public static final String _pre_fec_ber_ = "pre-fec-ber";
    public static final int    _PHOTONIC_LAYER_QUALIFIER_SMC = 452821503;
    public static final String _PHOTONIC_LAYER_QUALIFIER_SMC_ = "PHOTONIC_LAYER_QUALIFIER_SMC";
    public static final int    _application_identifier_type = 343038842;
    public static final String _application_identifier_type_ = "application-identifier-type";
    public static final int    _transmit_power = 2083230338;
    public static final String _transmit_power_ = "transmit-power";
    public static final int    _intended_maximum_output_power = 1510824273;
    public static final String _intended_maximum_output_power_ = "intended-maximum-output-power";
    public static final int    _intended_minimum_output_power = 1797536716;
    public static final String _intended_minimum_output_power_ = "intended-minimum-output-power";
    public static final int    _otsia_connectivity_service_end_point_spec = 1320566951;
    public static final String _otsia_connectivity_service_end_point_spec_ = "otsia-connectivity-service-end-point-spec";
    public static final int    _laser_status = 1756344020;
    public static final String _laser_status_ = "laser-status";
    public static final int    _otsi_connectivity_service_end_point_spec = 218073590;
    public static final String _otsi_connectivity_service_end_point_spec_ = "otsi-connectivity-service-end-point-spec";
    public static final int    _otsi_termination = 411460940;
    public static final String _otsi_termination_ = "otsi-termination";
    public static final int    _selected_modulation = 1193090539;
    public static final String _selected_modulation_ = "selected-modulation";
    public static final int    _total_power_upper_warn_threshold_max = 1473418512;
    public static final String _total_power_upper_warn_threshold_max_ = "total-power-upper-warn-threshold-max";
    public static final int    _total_power_upper_warn_threshold_default = 170936485;
    public static final String _total_power_upper_warn_threshold_default_ = "total-power-upper-warn-threshold-default";
    public static final int    _supportable_application_identifier = 1561443054;
    public static final String _supportable_application_identifier_ = "supportable-application-identifier";
    public static final int    _otsi_adapter = 672277177;
    public static final String _otsi_adapter_ = "otsi-adapter";
    public static final int    _fec_parameters = 1442909908;
    public static final String _fec_parameters_ = "fec-parameters";
    public static final int    _uncorrectable_bits = 1057261617;
    public static final String _uncorrectable_bits_ = "uncorrectable-bits";
    public static final int    _capacity = 191070892;
    public static final String _capacity_ = "capacity";
    public static final int    _post_fec_ber = 1498085913;
    public static final String _post_fec_ber_ = "post-fec-ber";
    public static final int    _corrected_bytes = 1104495784;
    public static final String _corrected_bytes_ = "corrected-bytes";
    public static final int    _PHOTONIC_LAYER_QUALIFIER_OTS = 1054127028;
    public static final String _PHOTONIC_LAYER_QUALIFIER_OTS_ = "PHOTONIC_LAYER_QUALIFIER_OTS";
    public static final int    _total_power_warn_threshold_lower = 1073414928;
    public static final String _total_power_warn_threshold_lower_ = "total-power-warn-threshold-lower";
    public static final int    _PHOTONIC_LAYER_QUALIFIER_OTSiMCA = 1478597015;
    public static final String _PHOTONIC_LAYER_QUALIFIER_OTSiMCA_ = "PHOTONIC_LAYER_QUALIFIER_OTSiMCA";
    public static final int    _laser_bias_current = 1521732466;
    public static final String _laser_bias_current_ = "laser-bias-current";
    public static final int    _PHOTONIC_LAYER_QUALIFIER_OTSiA = 1441904865;
    public static final String _PHOTONIC_LAYER_QUALIFIER_OTSiA_ = "PHOTONIC_LAYER_QUALIFIER_OTSiA";
    public static final int    _application_identifier = 1270590404;
    public static final String _application_identifier_ = "application-identifier";
    public static final int    _otsi_service_interface_point_spec = 628349602;
    public static final String _otsi_service_interface_point_spec_ = "otsi-service-interface-point-spec";
    public static final int    _uncorrectable_bytes = 38468256;
    public static final String _uncorrectable_bytes_ = "uncorrectable-bytes";
    public static final int    _power_spectral_density = 1432508232;
    public static final String _power_spectral_density_ = "power-spectral-density";
    public static final int    _power_management_capability = 1602754042;
    public static final String _power_management_capability_ = "power-management-capability";
    public static final int    _PHOTONIC_LAYER_QUALIFIER_MCA = 1791791117;
    public static final String _PHOTONIC_LAYER_QUALIFIER_MCA_ = "PHOTONIC_LAYER_QUALIFIER_MCA";
    public static final int    _total_power = 1322562114;
    public static final String _total_power_ = "total-power";
    public static final int    _laser_control = 1258155454;
    public static final String _laser_control_ = "laser-control";
    public static final int    _upper_central_frequency = 242018034;
    public static final String _upper_central_frequency_ = "upper-central-frequency";
    public static final int    _spectrum = 963576108;
    public static final String _spectrum_ = "spectrum";
    public static final int    _media_channel_connectivity_service_end_point_spec = 1118861799;
    public static final String _media_channel_connectivity_service_end_point_spec_ = "media-channel-connectivity-service-end-point-spec";
    public static final int    _name = 1998270519;
    public static final String _name_ = "name";
    public static final int    _media_channel_node_edge_point_spec = 1193673562;
    public static final String _media_channel_node_edge_point_spec_ = "media-channel-node-edge-point-spec";
    public static final int    _total_power_lower_warn_threshold_default = 634101382;
    public static final String _total_power_lower_warn_threshold_default_ = "total-power-lower-warn-threshold-default";
    public static final int    _total_power_lower_warn_threshold_max = 1925982225;
    public static final String _total_power_lower_warn_threshold_max_ = "total-power-lower-warn-threshold-max";
    public static final int    _PHOTONIC_LAYER_QUALIFIER_OMS = 471159733;
    public static final String _PHOTONIC_LAYER_QUALIFIER_OMS_ = "PHOTONIC_LAYER_QUALIFIER_OMS";
    public static final int    _modulation = 943580148;
    public static final String _modulation_ = "modulation";
    public static final int    _otsi_capability = 1260591985;
    public static final String _otsi_capability_ = "otsi-capability";
    public static final int    _tolerable_maximum_input_power = 591726256;
    public static final String _tolerable_maximum_input_power_ = "tolerable-maximum-input-power";
    public static final int    _mca_connectivity_service_end_point_spec = 1211831812;
    public static final String _mca_connectivity_service_end_point_spec_ = "mca-connectivity-service-end-point-spec";
    public static final int    _number_of_mc = 1544743519;
    public static final String _number_of_mc_ = "number-of-mc";
    public static final int    _media_channel = 1003958371;
    public static final String _media_channel_ = "media-channel";
    public static final int    _adjustment_granularity = 1087943415;
    public static final String _adjustment_granularity_ = "adjustment-granularity";
    public static final int    _PHOTONIC_LAYER_QUALIFIER_OTSiG = 83358854;
    public static final String _PHOTONIC_LAYER_QUALIFIER_OTSiG_ = "PHOTONIC_LAYER_QUALIFIER_OTSiG";
    public static final int    _PHOTONIC_LAYER_QUALIFIER_MC = 2051700154;
    public static final String _PHOTONIC_LAYER_QUALIFIER_MC_ = "PHOTONIC_LAYER_QUALIFIER_MC";
    public static final int    _total_power_warn_threshold_upper = 1742471590;
    public static final String _total_power_warn_threshold_upper_ = "total-power-warn-threshold-upper";
    public static final int    _PHOTONIC_LAYER_QUALIFIER_OTSiMC = 524264742;
    public static final String _PHOTONIC_LAYER_QUALIFIER_OTSiMC_ = "PHOTONIC_LAYER_QUALIFIER_OTSiMC";
    public static final int    _application_code = 1202995594;
    public static final String _application_code_ = "application-code";
    public static final int    _corrected_bits = 768476781;
    public static final String _corrected_bits_ = "corrected-bits";
    public static final int    _measured_power_ingress = 192737794;
    public static final String _measured_power_ingress_ = "measured-power-ingress";
    public static final int    _supportable_minimum_output_power = 951742310;
    public static final String _supportable_minimum_output_power_ = "supportable-minimum-output-power";
    public static final int    _unit = 1638458042;
    public static final String _unit_ = "unit";
    public static final int    _central_frequency = 2132299441;
    public static final String _central_frequency_ = "central-frequency";
    public static final int    _PHOTONIC_LAYER_QUALIFIER_NMC = 1940956229;
    public static final String _PHOTONIC_LAYER_QUALIFIER_NMC_ = "PHOTONIC_LAYER_QUALIFIER_NMC";
    public static final int    _otsi_connection_end_point_spec = 409413354;
    public static final String _otsi_connection_end_point_spec_ = "otsi-connection-end-point-spec";
    public static final int    _received_power = 1428978803;
    public static final String _received_power_ = "received-power";
    public static final int    _local_id = 1656047607;
    public static final String _local_id_ = "local-id";
    public static final int    _available_spectrum = 1167125139;
    public static final String _available_spectrum_ = "available-spectrum";
    public static final int    _supportable_spectrum = 1052638910;
    public static final String _supportable_spectrum_ = "supportable-spectrum";
    public static final int    _grid_type = 112189903;
    public static final String _grid_type_ = "grid-type";
    public static final int    _media_channel_assembly_spec = 573495689;
    public static final String _media_channel_assembly_spec_ = "media-channel-assembly-spec";
    public static final int    _upper_frequency = 2069940695;
    public static final String _upper_frequency_ = "upper-frequency";
    public static final int    _PHOTONIC_LAYER_QUALIFIER_OCH = 2039589768;
    public static final String _PHOTONIC_LAYER_QUALIFIER_OCH_ = "PHOTONIC_LAYER_QUALIFIER_OCH";
    public static final int    _mc_config = 1785289579;
    public static final String _mc_config_ = "mc-config";
    public static final int    _lower_central_frequency = 173788631;
    public static final String _lower_central_frequency_ = "lower-central-frequency";
}
