#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/lsa-utils.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module lsa-utils.yang


class ns(object):
    hash = 1529425157

    id = "http://cisco.com/ns/nso/lsa-utils"

    uri = "http://cisco.com/ns/nso/lsa-utils"

    prefix = "lsa-utils"

    lsa_utils_path = 1002915403
    lsa_utils_path_ = "path"
    lsa_utils_duplicate_device_name = 624789200
    lsa_utils_duplicate_device_name_ = "duplicate-device-name"
    lsa_utils_lsa = 2005676224
    lsa_utils_lsa_ = "lsa"
    lsa_utils_internal_dispatch_map_callback = 250607923
    lsa_utils_internal_dispatch_map_callback_ = "internal-dispatch-map-callback"
    lsa_utils_operation = 1037011282
    lsa_utils_operation_ = "operation"
    lsa_utils_device = 617911018
    lsa_utils_device_ = "device"
    lsa_utils_device_deleted = 1
    lsa_utils_device_deleted_ = "deleted"
    lsa_utils_lower_layer = 2
    lsa_utils_lower_layer_ = "lower-layer"
    lsa_utils_dispatch_map_update = 660612098
    lsa_utils_dispatch_map_update_ = "dispatch-map-update"
    lsa_utils_dispatch_map_persist_failure = 2063610731
    lsa_utils_dispatch_map_persist_failure_ = "dispatch-map-persist-failure"
    lsa_utils_lsa_util_alarm = 1225361582
    lsa_utils_lsa_util_alarm_ = "lsa-util-alarm"
    lsa_utils_inter_layer = 1
    lsa_utils_inter_layer_ = "inter-layer"
    lsa_utils_role = 1297556411
    lsa_utils_role_ = "role"
    lsa_utils_remote_nso = 1349233645
    lsa_utils_remote_nso_ = "remote-nso"
    lsa_utils_detail = 984599342
    lsa_utils_detail_ = "detail"
    lsa_utils_dispatch_map = 1257427000
    lsa_utils_dispatch_map_ = "dispatch-map"
    lsa_utils_device_created = 0
    lsa_utils_device_created_ = "created"
    lsa_utils_kicker_id = 1615011589
    lsa_utils_kicker_id_ = "kicker-id"
    lsa_utils_tid = 805616318
    lsa_utils_tid_ = "tid"
    lsa_utils_ned_id = 1774190712
    lsa_utils_ned_id_ = "ned-id"
    lsa_utils_upper_layer = 0
    lsa_utils_upper_layer_ = "upper-layer"
    lsa_utils_name = 1998270519
    lsa_utils_name_ = "name"
    lsa_utils_remote_node = 1553725823
    lsa_utils_remote_node_ = "remote-node"
    lsa_utils_sync = 2047869128
    lsa_utils_sync_ = "sync"
    lsa_utils_success = 87922769
    lsa_utils_success_ = "success"
    lsa_utils_non_lsa = 3
    lsa_utils_non_lsa_ = "non-lsa"
    actionpoint_internal_dispatch_map_callback = "internal-dispatch-map-callback"
    actionpoint_lsa_utils_sync_dispatch_map = "lsa-utils-sync-dispatch-map"
