/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/core-fp-common-status-codes.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.cisco.corefpcommon.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module core-fp-common-status-codes.yang */
public class coreFpCommonStatusCodes extends ConfNamespace {
    public static final int hash = 756363296;
    public int hash() {
        return coreFpCommonStatusCodes.hash;
    }

    public static final String id = "http://com/cisco/cfp-common-status-codes";
    public String id() {
        return coreFpCommonStatusCodes.id;
    }

    public static final String uri = "http://com/cisco/cfp-common-status-codes";
    public String uri() {
        return coreFpCommonStatusCodes.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(coreFpCommonStatusCodes.uri);
    }

    public static final String prefix = "cfp-common-status-codes";
    public String prefix() {
        return coreFpCommonStatusCodes.prefix;
    }

    public coreFpCommonStatusCodes() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _code = 9025151;
    public static final String _code_ = "code";
    public static final int    _recommended_actions = 180304737;
    public static final String _recommended_actions_ = "recommended-actions";
    public static final int    _WARNING = 777626720;
    public static final String _WARNING_ = "WARNING";
    public static final int    _status_codes = 1805334616;
    public static final String _status_codes_ = "status-codes";
    public static final int    _core_function_pack = 14173825;
    public static final String _core_function_pack_ = "core-function-pack";
    public static final int    _severity_type_base = 228232433;
    public static final String _severity_type_base_ = "severity-type-base";
    public static final int    _ERROR = 2110492722;
    public static final String _ERROR_ = "ERROR";
    public static final int    _status_code_enum_path = 1835523920;
    public static final String _status_code_enum_path_ = "status-code-enum-path";
    public static final int    _reason = 565156039;
    public static final String _reason_ = "reason";
    public static final int    _INFO = 1021731163;
    public static final String _INFO_ = "INFO";
    public static final int    _name = 1998270519;
    public static final String _name_ = "name";
    public static final int    _category = 2142289646;
    public static final String _category_ = "category";
    public static final int    _status_code = 573879470;
    public static final String _status_code_ = "status-code";
    public static final int    _severity = 483607279;
    public static final String _severity_ = "severity";
    public static final int    _status_code_cfp = 1532631475;
    public static final String _status_code_cfp_ = "status-code-cfp";
    public static final int    _FATAL = 54493095;
    public static final String _FATAL_ = "FATAL";
    public static final String validate_status_code_validation = "status-code-validation";
    public static final String validate_status_code_validation_py = "status-code-validation-py";
}
