/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/core-fp-release.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.cisco.corefpcommon.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module core-fp-release.yang */
public class coreFpRelease extends ConfNamespace {
    public static final int hash = 1701587574;
    public int hash() {
        return coreFpRelease.hash;
    }

    public static final String id = "http://cisco.com/ns/corefp-release";
    public String id() {
        return coreFpRelease.id;
    }

    public static final String uri = "http://cisco.com/ns/corefp-release";
    public String uri() {
        return coreFpRelease.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(coreFpRelease.uri);
    }

    public static final String prefix = "corefp-release";
    public String prefix() {
        return coreFpRelease.prefix;
    }

    public coreFpRelease() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _git = 1023471063;
    public static final String _git_ = "git";
    public static final int    _java_version = 1246353831;
    public static final String _java_version_ = "java-version";
    public static final int    _function_pack_store = 42294361;
    public static final String _function_pack_store_ = "function-pack-store";
    public static final int    _branch = 347240058;
    public static final String _branch_ = "branch";
    public static final int    _user = 1529217067;
    public static final String _user_ = "user";
    public static final int    _host = 1711485895;
    public static final String _host_ = "host";
    public static final int    _hostname = 840214230;
    public static final String _hostname_ = "hostname";
    public static final int    _version = 1714291735;
    public static final String _version_ = "version";
    public static final int    _revision = 1794066410;
    public static final String _revision_ = "revision";
    public static final int    _depends_on_function = 585051204;
    public static final String _depends_on_function_ = "depends-on-function";
    public static final int    _date_time = 1340198733;
    public static final String _date_time_ = "date-time";
    public static final int    _ref_count = 1570024794;
    public static final String _ref_count_ = "ref-count";
    public static final int    _number = 146471600;
    public static final String _number_ = "number";
    public static final int    _package_version = 1348193950;
    public static final String _package_version_ = "package-version";
    public static final int    _build = 463955894;
    public static final String _build_ = "build";
    public static final int    _uname = 915327512;
    public static final String _uname_ = "uname";
    public static final int    _package = 1915468916;
    public static final String _package_ = "package";
    public static final int    _name = 1998270519;
    public static final String _name_ = "name";
    public static final int    _fp_installed_packages = 1082176501;
    public static final String _fp_installed_packages_ = "fp-installed-packages";
    public static final int    _file_name = 1824330763;
    public static final String _file_name_ = "file-name";
    public static final int    _nso_version = 1846849211;
    public static final String _nso_version_ = "nso-version";
    public static final int    _release = 1325681236;
    public static final String _release_ = "release";
    public static final int    _core_fp_release = 1266241932;
    public static final String _core_fp_release_ = "core-fp-release";
    public static final int    _function_pack_name = 1132003177;
    public static final String _function_pack_name_ = "function-pack-name";
    public static final int    _python_version = 492995137;
    public static final String _python_version_ = "python-version";
    public static final int    _common_packages = 654003127;
    public static final String _common_packages_ = "common-packages";
}
