/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/core-fp-common-template-mapper.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.cisco.corefpcommon.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module core-fp-common-template-mapper.yang */
public class coreFpCommonTemplateMapper extends ConfNamespace {
    public static final int hash = 1299831000;
    public int hash() {
        return coreFpCommonTemplateMapper.hash;
    }

    public static final String id = "http://com/cisco/cfp-common-temp-mapper";
    public String id() {
        return coreFpCommonTemplateMapper.id;
    }

    public static final String uri = "http://com/cisco/cfp-common-temp-mapper";
    public String uri() {
        return coreFpCommonTemplateMapper.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(coreFpCommonTemplateMapper.uri);
    }

    public static final String prefix = "cfp-common-temp-mapper";
    public String prefix() {
        return coreFpCommonTemplateMapper.prefix;
    }

    public coreFpCommonTemplateMapper() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _service_template = 7202507;
    public static final String _service_template_ = "service-template";
    public static final int    _override_template = 1618824398;
    public static final String _override_template_ = "override-template";
    public static final int    _ignore_override_settings = 64952547;
    public static final String _ignore_override_settings_ = "ignore-override-settings";
    public static final int    _service_template_mapper = 1281109754;
    public static final String _service_template_mapper_ = "service-template-mapper";
    public static final int    _per_tenant = 2051589647;
    public static final String _per_tenant_ = "per-tenant";
    public static final int    _tenant = 967868883;
    public static final String _tenant_ = "tenant";
    public static final int    _provider = 837826676;
    public static final String _provider_ = "provider";
    public static final int    _per_provider = 1258956421;
    public static final String _per_provider_ = "per-provider";
}
