/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/core-fp-common.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.cisco.corefpcommon.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module core-fp-common.yang */
public class coreFpCommon extends ConfNamespace {
    public static final int hash = 1396750557;
    public int hash() {
        return coreFpCommon.hash;
    }

    public static final String id = "http://com/cisco/corefpcommon";
    public String id() {
        return coreFpCommon.id;
    }

    public static final String uri = "http://com/cisco/corefpcommon";
    public String uri() {
        return coreFpCommon.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(coreFpCommon.uri);
    }

    public static final String prefix = "core-fp-common";
    public String prefix() {
        return coreFpCommon.prefix;
    }

    public coreFpCommon() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _dispatch_map_events = 693957350;
    public static final String _dispatch_map_events_ = "dispatch-map-events";
    public static final int    _path = 1002915403;
    public static final String _path_ = "path";
    public static final int    _rfs_node = 1384821200;
    public static final String _rfs_node_ = "rfs-node";
    public static final int    _cfp_common_actions = 2087901694;
    public static final String _cfp_common_actions_ = "cfp-common-actions";
    public static final int    _operation = 1037011282;
    public static final String _operation_ = "operation";
    public static final int    _valtype = 98092268;
    public static final String _valtype_ = "valtype";
    public static final int    _var = 2007560533;
    public static final String _var_ = "var";
    public static final int    _device = 617911018;
    public static final String _device_ = "device";
    public static final int    _global_var = 255059789;
    public static final String _global_var_ = "global-var";
    public static final int    _value = 864367181;
    public static final String _value_ = "value";
    public static final int    _tenant_infrastructure = 1757718876;
    public static final String _tenant_infrastructure_ = "tenant-infrastructure";
    public static final int    _provider_infrastructure = 764587948;
    public static final String _provider_infrastructure_ = "provider-infrastructure";
    public static final int    _detail = 984599342;
    public static final String _detail_ = "detail";
    public static final int    _dispatch_map = 1257427000;
    public static final String _dispatch_map_ = "dispatch-map";
    public static final int    _kicker_id = 1615011589;
    public static final String _kicker_id_ = "kicker-id";
    public static final int    _tenant = 967868883;
    public static final String _tenant_ = "tenant";
    public static final int    _tid = 805616318;
    public static final String _tid_ = "tid";
    public static final int    _ned_id = 1774190712;
    public static final String _ned_id_ = "ned-id";
    public static final int    _cfp_local_user = 616556511;
    public static final String _cfp_local_user_ = "cfp-local-user";
    public static final int    _name = 1998270519;
    public static final String _name_ = "name";
    public static final int    _sync_dispatch_map = 247646197;
    public static final String _sync_dispatch_map_ = "sync-dispatch-map";
    public static final int    _encrypted_value = 920496590;
    public static final String _encrypted_value_ = "encrypted-value";
    public static final int    _provider = 837826676;
    public static final String _provider_ = "provider";
    public static final int    _success = 87922769;
    public static final String _success_ = "success";
    public static final int    _rfs_dispatch_map_netconf_notification_handler = 100524093;
    public static final String _rfs_dispatch_map_netconf_notification_handler_ = "rfs-dispatch-map-netconf-notification-handler";
    public static final int    _auto_populate_dispatch_map = 1788365662;
    public static final String _auto_populate_dispatch_map_ = "auto-populate-dispatch-map";
    public static final String actionpoint_rfs_dispatch_map_netconf_notification_handler = "rfs-dispatch-map-netconf-notification-handler";
    public static final String actionpoint_sync_dispatch_map = "sync-dispatch-map";
}
