mkdir -p ./thirdparty
cp ../../../../ncs-dao/target/nso-dao-5.4.0.1.jar ./thirdparty/.
cp ~/nso/java/jar/ncs-5.4.0.1.jar ./thirdparty/.
cp ~/nso/java/jar/conf-api-7.4.jar ./thirdparty/.
cp ~/nso/java/jar/tailf-ganymed-ssh2-262-p10.jar ./thirdparty/. 
cp ~/.m2/repository/org/apache/logging/log4j/log4j-api/2.16.0/*.jar ./thirdparty/.
cp ~/.m2/repository/org/apache/logging/log4j/log4j-core/2.16.0/*.jar ./thirdparty/.
cp ~/.m2/repository/org/slf4j/slf4j-log4j12/1.7.25/*.jar ./thirdparty/.
cp ~/.m2/repository/log4j/log4j/1.2.17/*.jar ./thirdparty/.
