#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/cisco-ron-cfp-nano-plan-services.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module cisco-ron-cfp-nano-plan-services.yang


class ns(object):
    hash = 193952239

    id = "http://cisco.com/ns/nso/cfp/cisco-ron-cfp-nano-plan-services"

    uri = "http://cisco.com/ns/nso/cfp/cisco-ron-cfp-nano-plan-services"

    prefix = "cisco-ron-cfp-nano-plan-services"

    cisco_ron_cfp_nano_plan_services_optical_controller = 1066653164
    cisco_ron_cfp_nano_plan_services_optical_controller_ = "optical-controller"
    cisco_ron_cfp_nano_plan_services_config_apply = 1554681992
    cisco_ron_cfp_nano_plan_services_config_apply_ = "config-apply"
    cisco_ron_cfp_nano_plan_services_router = 532320551
    cisco_ron_cfp_nano_plan_services_router_ = "router"
