#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/iana-crypt-hash.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module iana-crypt-hash.yang


class ns(object):
    hash = 1545491576

    id = "_onf-tapi-nc-2.0:onf-tapi-nc-2.0#urn:ietf:params:xml:ns:yang:iana-crypt-hash"

    uri = "_onf-tapi-nc-2.0:onf-tapi-nc-2.0#urn:ietf:params:xml:ns:yang:iana-crypt-hash"

    prefix = "ianach"

