#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/ietf-ip.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module ietf-ip.yang


class ns(object):
    hash = 554567954

    id = "_onf-tapi-nc-2.0:onf-tapi-nc-2.0#urn:ietf:params:xml:ns:yang:ietf-ip"

    uri = "_onf-tapi-nc-2.0:onf-tapi-nc-2.0#urn:ietf:params:xml:ns:yang:ietf-ip"

    prefix = "ip"

    ip_temporary_preferred_lifetime = 1399830185
    ip_temporary_preferred_lifetime_ = "temporary-preferred-lifetime"
    ip_neighbor = 81789621
    ip_neighbor_ = "neighbor"
    ip_ipv4 = 268057062
    ip_ipv4_ = "ipv4"
    ip_static = 1
    ip_static_ = "static"
    ip_forwarding = 1238173057
    ip_forwarding_ = "forwarding"
    ip_stale = 2
    ip_stale_ = "stale"
    ip_dynamic = 2
    ip_dynamic_ = "dynamic"
    ip_autoconf = 78817100
    ip_autoconf_ = "autoconf"
    ip_preferred = 0
    ip_preferred_ = "preferred"
    ip_enabled = 197426095
    ip_enabled_ = "enabled"
    ip_create_global_addresses = 1061463433
    ip_create_global_addresses_ = "create-global-addresses"
    ip_deprecated = 1
    ip_deprecated_ = "deprecated"
    ip_inaccessible = 3
    ip_inaccessible_ = "inaccessible"
    ip_status = 1950810920
    ip_status_ = "status"
    ip_state = 630973766
    ip_state_ = "state"
    ip_probe = 4
    ip_probe_ = "probe"
    ip_link_layer = 3
    ip_link_layer_ = "link-layer"
    ip_dup_addr_detect_transmits = 53367116
    ip_dup_addr_detect_transmits_ = "dup-addr-detect-transmits"
    ip_optimistic = 7
    ip_optimistic_ = "optimistic"
    ip_temporary_valid_lifetime = 710688618
    ip_temporary_valid_lifetime_ = "temporary-valid-lifetime"
    ip_invalid = 2
    ip_invalid_ = "invalid"
    ip_reachable = 1
    ip_reachable_ = "reachable"
    ip_duplicate = 6
    ip_duplicate_ = "duplicate"
    ip_dhcp = 2
    ip_dhcp_ = "dhcp"
    ip_ipv6 = 1228132394
    ip_ipv6_ = "ipv6"
    ip_origin = 2002579816
    ip_origin_ = "origin"
    ip_mtu = 1751455506
    ip_mtu_ = "mtu"
    ip_create_temporary_addresses = 575599870
    ip_create_temporary_addresses_ = "create-temporary-addresses"
    ip_delay = 3
    ip_delay_ = "delay"
    ip_is_router = 1891156201
    ip_is_router_ = "is-router"
    ip_subnet = 1544472008
    ip_subnet_ = "subnet"
    ip_tentative = 5
    ip_tentative_ = "tentative"
    ip_incomplete = 0
    ip_incomplete_ = "incomplete"
    ip_unknown = 4
    ip_unknown_ = "unknown"
    ip_ip = 1643785435
    ip_ip_ = "ip"
    ip_address = 1266954393
    ip_address_ = "address"
    ip_other = 0
    ip_other_ = "other"
    ip_link_layer_address = 2084100809
    ip_link_layer_address_ = "link-layer-address"
    ip_random = 4
    ip_random_ = "random"
    ip_prefix_length = 524393771
    ip_prefix_length_ = "prefix-length"
    ip_netmask = 240292132
    ip_netmask_ = "netmask"
