#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/ietf-netconf-nmda.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module ietf-netconf-nmda.yang


class ns(object):
    hash = 1844783890

    id = "_onf-tapi-nc-2.0:onf-tapi-nc-2.0#urn:ietf:params:xml:ns:yang:ietf-netconf-nmda"

    uri = "_onf-tapi-nc-2.0:onf-tapi-nc-2.0#urn:ietf:params:xml:ns:yang:ietf-netconf-nmda"

    prefix = "ncds"

    ncds_info = 2062105651
    ncds_info_ = "info"
    ncds_with_origin = 916967366
    ncds_with_origin_ = "with-origin"
    ncds_origin_filters = 621060453
    ncds_origin_filters_ = "origin-filters"
    ncds_url = 1560781157
    ncds_url_ = "url"
    ncds_result = 401396173
    ncds_result_ = "result"
    ncds_rpc_edit_data = 802788069
    ncds_rpc_edit_data_ = "rpc-edit-data"
    ncds_device = 617911018
    ncds_device_ = "device"
    ncds_none = 2
    ncds_none_ = "none"
    ncds_origin_filter = 1819823532
    ncds_origin_filter_ = "origin-filter"
    ncds_with_defaults = 951957594
    ncds_with_defaults_ = "with-defaults"
    ncds_datastore = 449538578
    ncds_datastore_ = "datastore"
    ncds_config_filter = 629654061
    ncds_config_filter_ = "config-filter"
    ncds_default_operation = 1003120352
    ncds_default_operation_ = "default-operation"
    ncds_max_depth = 727061923
    ncds_max_depth_ = "max-depth"
    ncds_negated_origin_filter = 913057017
    ncds_negated_origin_filter_ = "negated-origin-filter"
    ncds_config = 2105663071
    ncds_config_ = "config"
    ncds_unbounded = 0
    ncds_unbounded_ = "unbounded"
    ncds_replace = 1
    ncds_replace_ = "replace"
    ncds_edit_data = 78643628
    ncds_edit_data_ = "edit-data"
    ncds_filter_spec = 354841189
    ncds_filter_spec_ = "filter-spec"
    ncds_name = 1998270519
    ncds_name_ = "name"
    ncds_edit_content = 417982512
    ncds_edit_content_ = "edit-content"
    ncds_get_data = 1422478860
    ncds_get_data_ = "get-data"
    ncds_data = 535242711
    ncds_data_ = "data"
    ncds_subtree_filter = 519763503
    ncds_subtree_filter_ = "subtree-filter"
    ncds_merge = 0
    ncds_merge_ = "merge"
    ncds_xpath_filter = 113610718
    ncds_xpath_filter_ = "xpath-filter"
    ncds_rpc_get_data = 541517833
    ncds_rpc_get_data_ = "rpc-get-data"
