#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/ietf-restconf-monitoring.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module ietf-restconf-monitoring.yang


class ns(object):
    hash = 1533498192

    id = "_onf-tapi-nc-2.0:onf-tapi-nc-2.0#urn:ietf:params:xml:ns:yang:ietf-restconf-monitoring"

    uri = "_onf-tapi-nc-2.0:onf-tapi-nc-2.0#urn:ietf:params:xml:ns:yang:ietf-restconf-monitoring"

    prefix = "rcmon"

    rcmon_stream = 1561687317
    rcmon_stream_ = "stream"
    rcmon_replay_support = 1991147815
    rcmon_replay_support_ = "replay-support"
    rcmon_streams = 1043459567
    rcmon_streams_ = "streams"
    rcmon_location = 1827424758
    rcmon_location_ = "location"
    rcmon_encoding = 180862443
    rcmon_encoding_ = "encoding"
    rcmon_access = 304644663
    rcmon_access_ = "access"
    rcmon_capabilities = 1381570067
    rcmon_capabilities_ = "capabilities"
    rcmon_capability = 1251322185
    rcmon_capability_ = "capability"
    rcmon_restconf_state = 1557343351
    rcmon_restconf_state_ = "restconf-state"
    rcmon_name = 1998270519
    rcmon_name_ = "name"
    rcmon_description = 202559156
    rcmon_description_ = "description"
    rcmon_replay_log_creation_time = 896118574
    rcmon_replay_log_creation_time_ = "replay-log-creation-time"
