#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/ietf-yang-patch.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module ietf-yang-patch.yang


class ns(object):
    hash = 638884508

    id = "_onf-tapi-nc-2.0:onf-tapi-nc-2.0#urn:ietf:params:xml:ns:yang:ietf-yang-patch"

    uri = "_onf-tapi-nc-2.0:onf-tapi-nc-2.0#urn:ietf:params:xml:ns:yang:ietf-yang-patch"

    prefix = "ypatch"

    ypatch_before = 0
    ypatch_before_ = "before"
    ypatch_error_app_tag = 174711818
    ypatch_error_app_tag_ = "error-app-tag"
    ypatch_rpc = 1
    ypatch_rpc_ = "rpc"
    ypatch_error = 126243105
    ypatch_error_ = "error"
    ypatch_target = 1914145912
    ypatch_target_ = "target"
    ypatch_operation = 1037011282
    ypatch_operation_ = "operation"
    ypatch_edit_status_choice = 799887093
    ypatch_edit_status_choice_ = "edit-status-choice"
    ypatch_error_tag = 1676431963
    ypatch_error_tag_ = "error-tag"
    ypatch_error_message = 174234492
    ypatch_error_message_ = "error-message"
    ypatch_value = 864367181
    ypatch_value_ = "value"
    ypatch_point = 1540270895
    ypatch_point_ = "point"
    ypatch_insert = 2
    ypatch_insert_ = "insert"
    ypatch_patch_id = 1325519292
    ypatch_patch_id_ = "patch-id"
    ypatch_move = 4
    ypatch_move_ = "move"
    ypatch_global_errors = 1444755275
    ypatch_global_errors_ = "global-errors"
    ypatch_ok = 410023581
    ypatch_ok_ = "ok"
    ypatch_yang_patch_status = 401006991
    ypatch_yang_patch_status_ = "yang-patch-status"
    ypatch_errors = 1226221644
    ypatch_errors_ = "errors"
    ypatch_error_info = 1461021182
    ypatch_error_info_ = "error-info"
    ypatch_error_type = 1687973556
    ypatch_error_type_ = "error-type"
    ypatch_yang_patch = 1853535404
    ypatch_yang_patch_ = "yang-patch"
    ypatch_replace = 5
    ypatch_replace_ = "replace"
    ypatch_global_status = 1673083135
    ypatch_global_status_ = "global-status"
    ypatch_edit = 1716487530
    ypatch_edit_ = "edit"
    ypatch_comment = 452863039
    ypatch_comment_ = "comment"
    ypatch_transport = 0
    ypatch_transport_ = "transport"
    ypatch_delete = 1
    ypatch_delete_ = "delete"
    ypatch_after = 1
    ypatch_after_ = "after"
    ypatch_where = 121913774
    ypatch_where_ = "where"
    ypatch_edit_id = 2090794113
    ypatch_edit_id_ = "edit-id"
    ypatch_remove = 6
    ypatch_remove_ = "remove"
    ypatch_merge = 3
    ypatch_merge_ = "merge"
    ypatch_protocol = 2
    ypatch_protocol_ = "protocol"
    ypatch_application = 3
    ypatch_application_ = "application"
    ypatch_create = 0
    ypatch_create_ = "create"
    ypatch_last = 3
    ypatch_last_ = "last"
    ypatch_error_path = 1862370029
    ypatch_error_path_ = "error-path"
    ypatch_edit_status = 702369480
    ypatch_edit_status_ = "edit-status"
    ypatch_first = 2
    ypatch_first_ = "first"
