#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/ietf-restconf.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module ietf-restconf.yang


class ns(object):
    hash = 748488482

    id = "_onf-tapi-nc-2.0:onf-tapi-nc-2.0#urn:ietf:params:xml:ns:yang:ietf-restconf"

    uri = "_onf-tapi-nc-2.0:onf-tapi-nc-2.0#urn:ietf:params:xml:ns:yang:ietf-restconf"

    prefix = "rc"

    rc_error_app_tag = 174711818
    rc_error_app_tag_ = "error-app-tag"
    rc_rpc = 1
    rc_rpc_ = "rpc"
    rc_error = 126243105
    rc_error_ = "error"
    rc_error_tag = 1676431963
    rc_error_tag_ = "error-tag"
    rc_error_message = 174234492
    rc_error_message_ = "error-message"
    rc_restconf = 1660138980
    rc_restconf_ = "restconf"
    rc_errors = 1226221644
    rc_errors_ = "errors"
    rc_error_info = 1461021182
    rc_error_info_ = "error-info"
    rc_error_type = 1687973556
    rc_error_type_ = "error-type"
    rc_transport = 0
    rc_transport_ = "transport"
    rc_data = 535242711
    rc_data_ = "data"
    rc_operations = 1455304325
    rc_operations_ = "operations"
    rc_protocol = 2
    rc_protocol_ = "protocol"
    rc_application = 3
    rc_application_ = "application"
    rc_error_path = 1862370029
    rc_error_path_ = "error-path"
