#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/ietf-netconf-partial-lock.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module ietf-netconf-partial-lock.yang


class ns(object):
    hash = 1427669119

    id = "_onf-tapi-nc-2.0:onf-tapi-nc-2.0#urn:ietf:params:xml:ns:netconf:partial-lock:1.0"

    uri = "_onf-tapi-nc-2.0:onf-tapi-nc-2.0#urn:ietf:params:xml:ns:netconf:partial-lock:1.0"

    prefix = "pl"

    pl_rpc_partial_lock = 1082551773
    pl_rpc_partial_lock_ = "rpc-partial-lock"
    pl_info = 2062105651
    pl_info_ = "info"
    pl_lock_id = 1218349718
    pl_lock_id_ = "lock-id"
    pl_result = 401396173
    pl_result_ = "result"
    pl_device = 617911018
    pl_device_ = "device"
    pl_locked_node = 228482246
    pl_locked_node_ = "locked-node"
    pl_rpc_partial_unlock = 101804136
    pl_rpc_partial_unlock_ = "rpc-partial-unlock"
    pl_name = 1998270519
    pl_name_ = "name"
    pl_select = 1473597411
    pl_select_ = "select"
    pl_partial_lock = 957776378
    pl_partial_lock_ = "partial-lock"
    pl_partial_unlock = 1242097148
    pl_partial_unlock_ = "partial-unlock"
