#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/ietf-netconf-with-defaults.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module ietf-netconf-with-defaults.yang


class ns(object):
    hash = 1978391419

    id = "_onf-tapi-nc-2.0:onf-tapi-nc-2.0#urn:ietf:params:xml:ns:yang:ietf-netconf-with-defaults"

    uri = "_onf-tapi-nc-2.0:onf-tapi-nc-2.0#urn:ietf:params:xml:ns:yang:ietf-netconf-with-defaults"

    prefix = "ncwd"

    ncwd_trim = 2
    ncwd_trim_ = "trim"
    ncwd_explicit = 3
    ncwd_explicit_ = "explicit"
    ncwd_with_defaults = 951957594
    ncwd_with_defaults_ = "with-defaults"
    ncwd_report_all_tagged = 1
    ncwd_report_all_tagged_ = "report-all-tagged"
    ncwd_report_all = 0
    ncwd_report_all_ = "report-all"
