#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/ietf-x509-cert-to-name.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module ietf-x509-cert-to-name.yang


class ns(object):
    hash = 1679991348

    id = "_onf-tapi-nc-2.0:onf-tapi-nc-2.0#urn:ietf:params:xml:ns:yang:ietf-x509-cert-to-name"

    uri = "_onf-tapi-nc-2.0:onf-tapi-nc-2.0#urn:ietf:params:xml:ns:yang:ietf-x509-cert-to-name"

    prefix = "x509c2n"

    x509c2n_san_dns_name = 1792132267
    x509c2n_san_dns_name_ = "san-dns-name"
    x509c2n_specified = 983606037
    x509c2n_specified_ = "specified"
    x509c2n_common_name = 1305223065
    x509c2n_common_name_ = "common-name"
    x509c2n_cert_to_name = 1378664366
    x509c2n_cert_to_name_ = "cert-to-name"
    x509c2n_san_any = 1849606202
    x509c2n_san_any_ = "san-any"
    x509c2n_san_ip_address = 830893531
    x509c2n_san_ip_address_ = "san-ip-address"
    x509c2n_san_rfc822_name = 880194234
    x509c2n_san_rfc822_name_ = "san-rfc822-name"
