#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/ietf-yang-push.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module ietf-yang-push.yang


class ns(object):
    hash = 351233928

    id = "_onf-tapi-nc-2.0:onf-tapi-nc-2.0#urn:ietf:params:xml:ns:yang:ietf-yang-push"

    uri = "_onf-tapi-nc-2.0:onf-tapi-nc-2.0#urn:ietf:params:xml:ns:yang:ietf-yang-push"

    prefix = "yp"

    yp_push_update = 2128440115
    yp_push_update_ = "push-update"
    yp_selection_filter_ref = 1041300164
    yp_selection_filter_ref_ = "selection-filter-ref"
    yp_excluded_change = 74302329
    yp_excluded_change_ = "excluded-change"
    yp_filter_failure_hint = 293424073
    yp_filter_failure_hint_ = "filter-failure-hint"
    yp_object_count_limit = 2075417373
    yp_object_count_limit_ = "object-count-limit"
    yp_before = 0
    yp_before_ = "before"
    yp_on_change_sync_unsupported = 1173345710
    yp_on_change_sync_unsupported_ = "on-change-sync-unsupported"
    yp_update_too_big = 2146683486
    yp_update_too_big_ = "update-too-big"
    yp_rpc_resync_subscription = 144231830
    yp_rpc_resync_subscription_ = "rpc-resync-subscription"
    yp_resync_subscription = 1499347311
    yp_resync_subscription_ = "resync-subscription"
    yp_establish_subscription_datastore_error_info = 1301495104
    yp_establish_subscription_datastore_error_info_ = "establish-subscription-datastore-error-info"
    yp_kilobytes_estimate = 236910935
    yp_kilobytes_estimate_ = "kilobytes-estimate"
    yp_within_subscription = 1926240005
    yp_within_subscription_ = "within-subscription"
    yp_incomplete_update = 2095665544
    yp_incomplete_update_ = "incomplete-update"
    yp_target = 1914145912
    yp_target_ = "target"
    yp_selection_filter = 1853185168
    yp_selection_filter_ = "selection-filter"
    yp_operation = 1037011282
    yp_operation_ = "operation"
    yp_modify_subscription_datastore_error_info = 855400698
    yp_modify_subscription_datastore_error_info_ = "modify-subscription-datastore-error-info"
    yp_value = 864367181
    yp_value_ = "value"
    yp_cant_exclude = 1998745783
    yp_cant_exclude_ = "cant-exclude"
    yp_point = 1540270895
    yp_point_ = "point"
    yp_insert = 2
    yp_insert_ = "insert"
    yp_patch_id = 1325519292
    yp_patch_id_ = "patch-id"
    yp_no_such_subscription_resync = 985944552
    yp_no_such_subscription_resync_ = "no-such-subscription-resync"
    yp_periodic = 538465825
    yp_periodic_ = "periodic"
    yp_by_reference = 1956288752
    yp_by_reference_ = "by-reference"
    yp_datastore = 449538578
    yp_datastore_ = "datastore"
    yp_sync_too_big = 545964838
    yp_sync_too_big_ = "sync-too-big"
    yp_filter_id = 1126015794
    yp_filter_id_ = "filter-id"
    yp_datastore_contents = 1539332235
    yp_datastore_contents_ = "datastore-contents"
    yp_kilobytes_limit = 515966394
    yp_kilobytes_limit_ = "kilobytes-limit"
    yp_datastore_not_subscribable = 1154615031
    yp_datastore_not_subscribable_ = "datastore-not-subscribable"
    yp_object_count_estimate = 781918496
    yp_object_count_estimate_ = "object-count-estimate"
    yp_yang_patch = 1853535404
    yp_yang_patch_ = "yang-patch"
    yp_dampening_period = 1195792556
    yp_dampening_period_ = "dampening-period"
    yp_period_unsupported = 829940114
    yp_period_unsupported_ = "period-unsupported"
    yp_unchanging_selection = 917989223
    yp_unchanging_selection_ = "unchanging-selection"
    yp_on_change = 2098028622
    yp_on_change_ = "on-change"
    yp_anchor_time = 1074015300
    yp_anchor_time_ = "anchor-time"
    yp_edit = 1716487530
    yp_edit_ = "edit"
    yp_comment = 452863039
    yp_comment_ = "comment"
    yp_filter_spec = 354841189
    yp_filter_spec_ = "filter-spec"
    yp_push_change_update = 1609217786
    yp_push_change_update_ = "push-change-update"
    yp_reason = 565156039
    yp_reason_ = "reason"
    yp_period_hint = 278441174
    yp_period_hint_ = "period-hint"
    yp_datastore_changes = 2074868284
    yp_datastore_changes_ = "datastore-changes"
    yp_on_change_unsupported = 248219053
    yp_on_change_unsupported_ = "on-change-unsupported"
    yp_period = 1135208285
    yp_period_ = "period"
    yp_delete = 1
    yp_delete_ = "delete"
    yp_after = 1
    yp_after_ = "after"
    yp_resync_subscription_error = 2105489835
    yp_resync_subscription_error_ = "resync-subscription-error"
    yp_where = 121913774
    yp_where_ = "where"
    yp_edit_id = 2090794113
    yp_edit_id_ = "edit-id"
    yp_remove = 6
    yp_remove_ = "remove"
    yp_merge = 3
    yp_merge_ = "merge"
    yp_id = 1279252765
    yp_id_ = "id"
    yp_create = 0
    yp_create_ = "create"
    yp_datastore_subtree_filter = 91341864
    yp_datastore_subtree_filter_ = "datastore-subtree-filter"
    yp_update_trigger = 400709998
    yp_update_trigger_ = "update-trigger"
    yp_last = 3
    yp_last_ = "last"
    yp_datastore_xpath_filter = 2038188293
    yp_datastore_xpath_filter_ = "datastore-xpath-filter"
    yp_first = 2
    yp_first_ = "first"
    yp_sync_on_start = 303588629
    yp_sync_on_start_ = "sync-on-start"
