#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/ietf-origin.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module ietf-origin.yang


class ns(object):
    hash = 394060208

    id = "_onf-tapi-nc-2.0:onf-tapi-nc-2.0#urn:ietf:params:xml:ns:yang:ietf-origin"

    uri = "_onf-tapi-nc-2.0:onf-tapi-nc-2.0#urn:ietf:params:xml:ns:yang:ietf-origin"

    prefix = "or"

    or_dynamic = 1339207079
    or_dynamic_ = "dynamic"
    or_system = 1534086422
    or_system_ = "system"
    or_default = 515137925
    or_default_ = "default"
    or_origin = 2002579816
    or_origin_ = "origin"
    or_learned = 1220332201
    or_learned_ = "learned"
    or_unknown = 966572115
    or_unknown_ = "unknown"
    or_intended = 270744734
    or_intended_ = "intended"
