#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/ietf-network-instance.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module ietf-network-instance.yang


class ns(object):
    hash = 472161184

    id = "_onf-tapi-nc-2.0:onf-tapi-nc-2.0#urn:ietf:params:xml:ns:yang:ietf-network-instance"

    uri = "_onf-tapi-nc-2.0:onf-tapi-nc-2.0#urn:ietf:params:xml:ns:yang:ietf-network-instance"

    prefix = "ni"

    ni_ipv4 = 268057062
    ni_ipv4_ = "ipv4"
    ni_bind_ni_name = 1051667450
    ni_bind_ni_name_ = "bind-ni-name"
    ni_enabled = 197426095
    ni_enabled_ = "enabled"
    ni_vrf_root = 779580575
    ni_vrf_root_ = "vrf-root"
    ni_network_instance = 1958697851
    ni_network_instance_ = "network-instance"
    ni_error_info = 1461021182
    ni_error_info_ = "error-info"
    ni_ni_type = 771026435
    ni_ni_type_ = "ni-type"
    ni_ipv6 = 1228132394
    ni_ipv6_ = "ipv6"
    ni_network_instances = 1258508407
    ni_network_instances_ = "network-instances"
    ni_vsi_root = 2099859672
    ni_vsi_root_ = "vsi-root"
    ni_name = 1998270519
    ni_name_ = "name"
    ni_vv_root = 1535194783
    ni_vv_root_ = "vv-root"
    ni_bind_ni_name_failed = 197464432
    ni_bind_ni_name_failed_ = "bind-ni-name-failed"
    ni_interface = 221572658
    ni_interface_ = "interface"
    ni_root_type = 699849197
    ni_root_type_ = "root-type"
    ni_description = 202559156
    ni_description_ = "description"
