#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/ietf-datastores.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module ietf-datastores.yang


class ns(object):
    hash = 1769400062

    id = "_onf-tapi-nc-2.0:onf-tapi-nc-2.0#urn:ietf:params:xml:ns:yang:ietf-datastores"

    uri = "_onf-tapi-nc-2.0:onf-tapi-nc-2.0#urn:ietf:params:xml:ns:yang:ietf-datastores"

    prefix = "ds"

    ds_operational = 177233883
    ds_operational_ = "operational"
    ds_dynamic = 1339207079
    ds_dynamic_ = "dynamic"
    ds_datastore = 449538578
    ds_datastore_ = "datastore"
    ds_candidate = 1374401854
    ds_candidate_ = "candidate"
    ds_startup = 1476781227
    ds_startup_ = "startup"
    ds_running = 59151599
    ds_running_ = "running"
    ds_intended = 270744734
    ds_intended_ = "intended"
    ds_conventional = 1535769645
    ds_conventional_ = "conventional"
