#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/tailf-ned-id-onf-tapi-nc.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module tailf-ned-id-onf-tapi-nc.yang


class ns(object):
    hash = 719297921

    id = "http://tail-f.com/ns/ned-id/onf-tapi-nc"

    uri = "http://tail-f.com/ns/ned-id/onf-tapi-nc"

    prefix = "onf-tapi-nc"

    ned_id = 1509293339
    ned_id_ = "onf-tapi-nc:onf-tapi-nc"
    onf_tapi_nc_onf_tapi_nc = 1509293339
    onf_tapi_nc_onf_tapi_nc_ = "onf-tapi-nc"
