#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/tailf-ned-id-onf-tapi-nc-2.0.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module tailf-ned-id-onf-tapi-nc-2.0.yang


class ns(object):
    hash = 1779461127

    id = "http://tail-f.com/ns/ned-id/onf-tapi-nc-2.0"

    uri = "http://tail-f.com/ns/ned-id/onf-tapi-nc-2.0"

    prefix = "onf-tapi-nc-2.0"

    onf_tapi_nc_20x2e0_onf_tapi_nc_20x2e0 = 2118563282
    onf_tapi_nc_20x2e0_onf_tapi_nc_20x2e0_ = "onf-tapi-nc-2.0"
