#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/tailf-netconf-forward.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module tailf-netconf-forward.yang


class ns(object):
    hash = 655662875

    id = "_onf-tapi-nc-2.0:onf-tapi-nc-2.0#http://tail-f.com/ns/netconf/forward/1.0"

    uri = "_onf-tapi-nc-2.0:onf-tapi-nc-2.0#http://tail-f.com/ns/netconf/forward/1.0"

    prefix = "fwd"

    fwd_rpc_forward = 1214942383
    fwd_rpc_forward_ = "rpc-forward"
    fwd_info = 2062105651
    fwd_info_ = "info"
    fwd_temporary_auth_failure = 944734092
    fwd_temporary_auth_failure_ = "temporary-auth-failure"
    fwd_forward = 228029135
    fwd_forward_ = "forward"
    fwd_challenge_response = 876635225
    fwd_challenge_response_ = "challenge-response"
    fwd_rpc_challenge_response = 206872506
    fwd_rpc_challenge_response_ = "rpc-challenge-response"
    fwd_error = 126243105
    fwd_error_ = "error"
    fwd_mechanism = 2003451367
    fwd_mechanism_ = "mechanism"
    fwd_connection_failure = 603012695
    fwd_connection_failure_ = "connection-failure"
    fwd_result = 401396173
    fwd_result_ = "result"
    fwd_invalid_mechanism = 1338074409
    fwd_invalid_mechanism_ = "invalid-mechanism"
    fwd_target = 1914145912
    fwd_target_ = "target"
    fwd_device = 617911018
    fwd_device_ = "device"
    fwd_not_authorized = 613918215
    fwd_not_authorized_ = "not-authorized"
    fwd_challenge = 1414041551
    fwd_challenge_ = "challenge"
    fwd_incorrect_encoding = 853274989
    fwd_incorrect_encoding_ = "incorrect-encoding"
    fwd_capabilities = 1381570067
    fwd_capabilities_ = "capabilities"
    fwd_capability = 1251322185
    fwd_capability_ = "capability"
    fwd_initial_response = 890592954
    fwd_initial_response_ = "initial-response"
    fwd_mechanism_too_weak = 882081729
    fwd_mechanism_too_weak_ = "mechanism-too-weak"
    fwd_response = 1363637576
    fwd_response_ = "response"
    fwd_reason = 565156039
    fwd_reason_ = "reason"
    fwd_connected = 1024392365
    fwd_connected_ = "connected"
    fwd_invalid_authzid = 1294980980
    fwd_invalid_authzid_ = "invalid-authzid"
    fwd_name = 1998270519
    fwd_name_ = "name"
    fwd_sasl_failure = 766737558
    fwd_sasl_failure_ = "sasl-failure"
    fwd_sasl_authentication_needed = 1978663406
    fwd_sasl_authentication_needed_ = "sasl-authentication-needed"
    fwd_mechanisms = 145873396
    fwd_mechanisms_ = "mechanisms"
    fwd_auth = 2093501109
    fwd_auth_ = "auth"
    fwd_failure = 1833033127
    fwd_failure_ = "failure"
