#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/tailf-netconf-with-rollback-id.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module tailf-netconf-with-rollback-id.yang


class ns(object):
    hash = 1894472223

    id = "_onf-tapi-nc-2.0:onf-tapi-nc-2.0#http://tail-f.com/ns/netconf/with-rollback-id"

    uri = "_onf-tapi-nc-2.0:onf-tapi-nc-2.0#http://tail-f.com/ns/netconf/with-rollback-id"

    prefix = "wrbid"

    wrbid_with_rollback_id = 607504166
    wrbid_with_rollback_id_ = "with-rollback-id"
    wrbid_rollback = 1666440862
    wrbid_rollback_ = "rollback"
    wrbid_fixed_number = 1086290328
    wrbid_fixed_number_ = "fixed-number"
    wrbid_id = 1279252765
    wrbid_id_ = "id"
