#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/tailf-last-login.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module tailf-last-login.yang


class ns(object):
    hash = 2058770883

    id = "_onf-tapi-nc-2.0:onf-tapi-nc-2.0#http://tail-f.com/yang/last-login"

    uri = "_onf-tapi-nc-2.0:onf-tapi-nc-2.0#http://tail-f.com/yang/last-login"

    prefix = "last"

    last_user = 1529217067
    last_user_ = "user"
    last_num_of_failed_logins = 990687426
    last_num_of_failed_logins_ = "num-of-failed-logins"
    last_login_time = 56217328
    last_login_time_ = "login-time"
    last_name = 1998270519
    last_name_ = "name"
    last_transport = 514190987
    last_transport_ = "transport"
    last_login = 1704196980
    last_login_ = "login"
    last_last_failed = 920339004
    last_last_failed_ = "last-failed"
    last_last_logins = 1946722611
    last_last_logins_ = "last-logins"
    last_client_host = 857297659
    last_client_host_ = "client-host"
    last_authenticating_host = 2140774720
    last_authenticating_host_ = "authenticating-host"
