#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/tailf-confd-progress.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module tailf-confd-progress.yang


class ns(object):
    hash = 440762200

    id = "_onf-tapi-nc-2.0:onf-tapi-nc-2.0#http://tail-f.com/ns/confd-progress"

    uri = "_onf-tapi-nc-2.0:onf-tapi-nc-2.0#http://tail-f.com/ns/confd-progress"

    prefix = "confd-progress"

    confd_progress_debug = 189210324
    confd_progress_debug_ = "debug"
    confd_progress_subscriber = 2
    confd_progress_subscriber_ = "subscriber"
    confd_progress_kicker = 1
    confd_progress_kicker_ = "kicker"
    confd_progress_xpath = 0
    confd_progress_xpath_ = "xpath"
