#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/tailf-netconf-rollback.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module tailf-netconf-rollback.yang


class ns(object):
    hash = 1704065176

    id = "_onf-tapi-nc-2.0:onf-tapi-nc-2.0#http://tail-f.com/ns/netconf/rollback"

    uri = "_onf-tapi-nc-2.0:onf-tapi-nc-2.0#http://tail-f.com/ns/netconf/rollback"

    prefix = "netconf-rollback"

    netconf_rollback_rollback_label = 1809663520
    netconf_rollback_rollback_label_ = "rollback-label"
    netconf_rollback_rollback_comment = 724872097
    netconf_rollback_rollback_comment_ = "rollback-comment"
