#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/tailf-rollback.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module tailf-rollback.yang


class ns(object):
    hash = 1497214267

    id = "_onf-tapi-nc-2.0:onf-tapi-nc-2.0#http://tail-f.com/ns/rollback"

    uri = "_onf-tapi-nc-2.0:onf-tapi-nc-2.0#http://tail-f.com/ns/rollback"

    prefix = "rollback"

    rollback_path = 1002915403
    rollback_path_ = "path"
    rollback_creator = 110891526
    rollback_creator_ = "creator"
    rollback_rollback = 1666440862
    rollback_rollback_ = "rollback"
    rollback_rollback_files = 110392016
    rollback_rollback_files_ = "rollback-files"
    rollback_content = 1400276169
    rollback_content_ = "content"
    rollback_selective = 573448511
    rollback_selective_ = "selective"
    rollback_apply_rollback_file = 1958997142
    rollback_apply_rollback_file_ = "apply-rollback-file"
    rollback_comment = 452863039
    rollback_comment_ = "comment"
    rollback_get_rollback_file = 1216164084
    rollback_get_rollback_file_ = "get-rollback-file"
    rollback_date = 2125704837
    rollback_date_ = "date"
    rollback_via = 1211954281
    rollback_via_ = "via"
    rollback_name = 1998270519
    rollback_name_ = "name"
    rollback_fixed_number = 1086290328
    rollback_fixed_number_ = "fixed-number"
    rollback_file = 867066344
    rollback_file_ = "file"
    rollback_id = 1279252765
    rollback_id_ = "id"
    rollback_label = 1570796500
    rollback_label_ = "label"
