#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/tailf-netconf-extensions.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module tailf-netconf-extensions.yang


class ns(object):
    hash = 1335581562

    id = "_onf-tapi-nc-2.0:onf-tapi-nc-2.0#http://tail-f.com/ns/netconf/extensions"

    uri = "_onf-tapi-nc-2.0:onf-tapi-nc-2.0#http://tail-f.com/ns/netconf/extensions"

    prefix = "tfnce"

    tfnce_has_children = 907427716
    tfnce_has_children_ = "has-children"
    tfnce_path = 1002915403
    tfnce_path_ = "path"
    tfnce_info = 2062105651
    tfnce_info_ = "info"
    tfnce_rpc_has_children = 980578736
    tfnce_rpc_has_children_ = "rpc-has-children"
    tfnce_trace_id = 1065151221
    tfnce_trace_id_ = "trace-id"
    tfnce_maybe = 0
    tfnce_maybe_ = "maybe"
    tfnce_result = 401396173
    tfnce_result_ = "result"
    tfnce_not_found = 1
    tfnce_not_found_ = "not_found"
    tfnce_device = 617911018
    tfnce_device_ = "device"
    tfnce_infinity = 0
    tfnce_infinity_ = "infinity"
    tfnce_false = 1
    tfnce_false_ = "false"
    tfnce_ok = 0
    tfnce_ok_ = "ok"
    tfnce_get_attributes = 1707479010
    tfnce_get_attributes_ = "get-attributes"
    tfnce_rpc_get_attributes = 1107808283
    tfnce_rpc_get_attributes_ = "rpc-get-attributes"
    tfnce_name = 1998270519
    tfnce_name_ = "name"
    tfnce_wait_time = 67539421
    tfnce_wait_time_ = "wait-time"
