#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/tailf-netconf-with-transaction-id.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module tailf-netconf-with-transaction-id.yang


class ns(object):
    hash = 905571072

    id = "_onf-tapi-nc-2.0:onf-tapi-nc-2.0#http://tail-f.com/ns/netconf/with-transaction-id"

    uri = "_onf-tapi-nc-2.0:onf-tapi-nc-2.0#http://tail-f.com/ns/netconf/with-transaction-id"

    prefix = "wtxid"

    wtxid_transaction_id = 1239501533
    wtxid_transaction_id_ = "transaction-id"
    wtxid_with_transaction_id = 1402897322
    wtxid_with_transaction_id_ = "with-transaction-id"
