#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/tailf-netconf-transactions.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module tailf-netconf-transactions.yang


class ns(object):
    hash = 122222200

    id = "_onf-tapi-nc-2.0:onf-tapi-nc-2.0#http://tail-f.com/ns/netconf/transactions/1.0"

    uri = "_onf-tapi-nc-2.0:onf-tapi-nc-2.0#http://tail-f.com/ns/netconf/transactions/1.0"

    prefix = "tr"

    tr_start_transaction = 770915272
    tr_start_transaction_ = "start-transaction"
    tr_abort_transaction = 1282652494
    tr_abort_transaction_ = "abort-transaction"
    tr_target = 1914145912
    tr_target_ = "target"
    tr_rpc_commit_transaction = 979803984
    tr_rpc_commit_transaction_ = "rpc-commit-transaction"
    tr_prepare_transaction = 2049539308
    tr_prepare_transaction_ = "prepare-transaction"
    tr_rpc_start_transaction = 1354312511
    tr_rpc_start_transaction_ = "rpc-start-transaction"
    tr_candidate = 1374401854
    tr_candidate_ = "candidate"
    tr_rpc_abort_transaction = 915338716
    tr_rpc_abort_transaction_ = "rpc-abort-transaction"
    tr_startup = 1476781227
    tr_startup_ = "startup"
    tr_running = 59151599
    tr_running_ = "running"
    tr_commit_transaction = 1058820311
    tr_commit_transaction_ = "commit-transaction"
    tr_rpc_prepare_transaction = 1892808563
    tr_rpc_prepare_transaction_ = "rpc-prepare-transaction"
