#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/tailf-aaa.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module tailf-aaa.yang


class ns(object):
    hash = 78910849

    id = "_onf-tapi-nc-2.0:onf-tapi-nc-2.0#http://tail-f.com/ns/aaa/1.1"

    uri = "_onf-tapi-nc-2.0:onf-tapi-nc-2.0#http://tail-f.com/ns/aaa/1.1"

    prefix = "aaa"

    aaa_prompt1 = 629040938
    aaa_prompt1_ = "prompt1"
    aaa_authentication = 838318934
    aaa_authentication_ = "authentication"
    aaa_complete_on_space = 1202435066
    aaa_complete_on_space_ = "complete-on-space"
    aaa_aaa = 2073600231
    aaa_aaa_ = "aaa"
    aaa_mode = 575893728
    aaa_mode_ = "mode"
    aaa_prompt2 = 513332017
    aaa_prompt2_ = "prompt2"
    aaa_change_password = 387358815
    aaa_change_password_ = "change-password"
    aaa_new_password = 842025097
    aaa_new_password_ = "new-password"
    aaa_command = 36215204
    aaa_command_ = "command"
    aaa_user = 1529217067
    aaa_user_ = "user"
    aaa_users = 987101583
    aaa_users_ = "users"
    aaa_exec = 0
    aaa_exec_ = "exec"
    aaa_display_level = 125770194
    aaa_display_level_ = "display-level"
    aaa_uid = 1587813883
    aaa_uid_ = "uid"
    aaa_password = 880727685
    aaa_password_ = "password"
    aaa_show_defaults = 1036396876
    aaa_show_defaults_ = "show-defaults"
    aaa_ios = 937667110
    aaa_ios_ = "ios"
    aaa_confirm_password = 2124963869
    aaa_confirm_password_ = "confirm-password"
    aaa_prompt = 1796253006
    aaa_prompt_ = "prompt"
    aaa_autowizard = 1810157643
    aaa_autowizard_ = "autowizard"
    aaa_homedir = 1609979376
    aaa_homedir_ = "homedir"
    aaa_devtools = 898584616
    aaa_devtools_ = "devtools"
    aaa_alias = 159608788
    aaa_alias_ = "alias"
    aaa_old_password = 945833963
    aaa_old_password_ = "old-password"
    aaa_idle_timeout = 1670649975
    aaa_idle_timeout_ = "idle-timeout"
    aaa_expansion = 1432673402
    aaa_expansion_ = "expansion"
    aaa_ssh_keydir = 825792753
    aaa_ssh_keydir_ = "ssh_keydir"
    aaa_history = 919502929
    aaa_history_ = "history"
    aaa_configure = 1
    aaa_configure_ = "configure"
    aaa_name = 1998270519
    aaa_name_ = "name"
    aaa_paginate = 570813703
    aaa_paginate_ = "paginate"
    aaa_session = 1896174846
    aaa_session_ = "session"
    aaa_gid = 1021704153
    aaa_gid_ = "gid"
    aaa_nr = 1926304974
    aaa_nr_ = "nr"
    aaa_privilege = 280620355
    aaa_privilege_ = "privilege"
    aaa_secret = 1322085478
    aaa_secret_ = "secret"
    aaa_level = 2112619197
    aaa_level_ = "level"
    aaa_description = 202559156
    aaa_description_ = "description"
    aaa_ignore_leading_space = 372367741
    aaa_ignore_leading_space_ = "ignore-leading-space"
