#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/tailf-netconf-inactive.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module tailf-netconf-inactive.yang


class ns(object):
    hash = 952939550

    id = "_onf-tapi-nc-2.0:onf-tapi-nc-2.0#http://tail-f.com/ns/netconf/inactive/1.0"

    uri = "_onf-tapi-nc-2.0:onf-tapi-nc-2.0#http://tail-f.com/ns/netconf/inactive/1.0"

    prefix = "in"

    in_with_inactive = 439733113
    in_with_inactive_ = "with-inactive"
