#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/tailf-netconf-query.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module tailf-netconf-query.yang


class ns(object):
    hash = 1226912411

    id = "_onf-tapi-nc-2.0:onf-tapi-nc-2.0#http://tail-f.com/ns/netconf/query"

    uri = "_onf-tapi-nc-2.0:onf-tapi-nc-2.0#http://tail-f.com/ns/netconf/query"

    prefix = "tfncq"

    tfncq_rpc_immediate_query = 1217725246
    tfncq_rpc_immediate_query_ = "rpc-immediate-query"
    tfncq_path = 1002915403
    tfncq_path_ = "path"
    tfncq_info = 2062105651
    tfncq_info_ = "info"
    tfncq_result = 401396173
    tfncq_result_ = "result"
    tfncq_rpc_start_query = 1753216580
    tfncq_rpc_start_query_ = "rpc-start-query"
    tfncq_reset_query = 1223114487
    tfncq_reset_query_ = "reset-query"
    tfncq_device = 617911018
    tfncq_device_ = "device"
    tfncq_timeout = 614210192
    tfncq_timeout_ = "timeout"
    tfncq_value = 864367181
    tfncq_value_ = "value"
    tfncq_stop_query = 1335172000
    tfncq_stop_query_ = "stop-query"
    tfncq_foreach = 2052892262
    tfncq_foreach_ = "foreach"
    tfncq_fetch_query_result = 1276818724
    tfncq_fetch_query_result_ = "fetch-query-result"
    tfncq_result_type_leaf_value = 2
    tfncq_result_type_leaf_value_ = "leaf-value"
    tfncq_result_type_inline = 3
    tfncq_result_type_inline_ = "inline"
    tfncq_rpc_reset_query = 1232203757
    tfncq_rpc_reset_query_ = "rpc-reset-query"
    tfncq_query_handle = 144584952
    tfncq_query_handle_ = "query-handle"
    tfncq_result_type = 565147987
    tfncq_result_type_ = "result-type"
    tfncq_result_type_string = 0
    tfncq_result_type_string_ = "string"
    tfncq_result_type_path = 1
    tfncq_result_type_path_ = "path"
    tfncq_query_result = 1542295748
    tfncq_query_result_ = "query-result"
    tfncq_limit = 1553282341
    tfncq_limit_ = "limit"
    tfncq_inline = 1987224790
    tfncq_inline_ = "inline"
    tfncq_rpc_fetch_query_result = 484654965
    tfncq_rpc_fetch_query_result_ = "rpc-fetch-query-result"
    tfncq_name = 1998270519
    tfncq_name_ = "name"
    tfncq_select = 1473597411
    tfncq_select_ = "select"
    tfncq_rpc_stop_query = 1755959753
    tfncq_rpc_stop_query_ = "rpc-stop-query"
    tfncq_data = 535242711
    tfncq_data_ = "data"
    tfncq_immediate_query = 1062477817
    tfncq_immediate_query_ = "immediate-query"
    tfncq_start_query = 1194651801
    tfncq_start_query_ = "start-query"
    tfncq_path_value = 480213734
    tfncq_path_value_ = "path-value"
    tfncq_sort_by = 2079244141
    tfncq_sort_by_ = "sort-by"
    tfncq_select_result = 1142952441
    tfncq_select_result_ = "select-result"
    tfncq_expression = 196994102
    tfncq_expression_ = "expression"
    tfncq_label = 1570796500
    tfncq_label_ = "label"
    tfncq_offset = 1966490361
    tfncq_offset_ = "offset"
