#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/tailf-webui.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module tailf-webui.yang


class ns(object):
    hash = 1212412867

    id = "_onf-tapi-nc-2.0:onf-tapi-nc-2.0#http://tail-f.com/ns/webui"

    uri = "_onf-tapi-nc-2.0:onf-tapi-nc-2.0#http://tail-f.com/ns/webui"

    prefix = "webui"

    webui_list_path = 847214750
    webui_list_path_ = "list-path"
    webui_z_index = 602022078
    webui_z_index_ = "z-index"
    webui_profile = 1538168517
    webui_profile_ = "profile"
    webui_data_store = 340295689
    webui_data_store_ = "data-store"
    webui_gif = 2
    webui_gif_ = "gif"
    webui_png = 1
    webui_png_ = "png"
    webui_value = 864367181
    webui_value_ = "value"
    webui_asset_type = 753992187
    webui_asset_type_ = "asset-type"
    webui_width = 1724310388
    webui_width_ = "width"
    webui_data_stores = 943355165
    webui_data_stores_ = "data-stores"
    webui_type = 2040883914
    webui_type_ = "type"
    webui_username = 870658415
    webui_username_ = "username"
    webui_component_type = 1275398985
    webui_component_type_ = "component-type"
    webui_left = 1845064683
    webui_left_ = "left"
    webui_height = 721582793
    webui_height_ = "height"
    webui_assets = 2007970714
    webui_assets_ = "assets"
    webui_key = 1348858669
    webui_key_ = "key"
    webui_base_64_image = 1234075651
    webui_base_64_image_ = "base-64-image"
    webui_components = 962606743
    webui_components_ = "components"
    webui_asset = 37078947
    webui_asset_ = "asset"
    webui_text = 361183530
    webui_text_ = "text"
    webui_properties = 1953873399
    webui_properties_ = "properties"
    webui_name = 1998270519
    webui_name_ = "name"
    webui_title = 110890495
    webui_title_ = "title"
    webui_user_profile = 1502841590
    webui_user_profile_ = "user-profile"
    webui_component = 1543026623
    webui_component_ = "component"
    webui_top = 703743881
    webui_top_ = "top"
    webui_link = 481374722
    webui_link_ = "link"
    webui_jpeg = 0
    webui_jpeg_ = "jpeg"
    webui_serialized_query = 345701342
    webui_serialized_query_ = "serialized-query"
    webui_panel = 2033856956
    webui_panel_ = "panel"
    webui_saved_query = 1451816574
    webui_saved_query_ = "saved-query"
    webui_panels = 915136013
    webui_panels_ = "panels"
    webui_id = 1279252765
    webui_id_ = "id"
    webui_webui = 1476667922
    webui_webui_ = "webui"
    webui_image = 1283093902
    webui_image_ = "image"
    webui_description = 202559156
    webui_description_ = "description"
    webui_schematics = 766670971
    webui_schematics_ = "schematics"
