#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/tailf-netconf-monitoring.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module tailf-netconf-monitoring.yang


class ns(object):
    hash = 587467833

    id = "_onf-tapi-nc-2.0:onf-tapi-nc-2.0#http://tail-f.com/yang/netconf-monitoring"

    uri = "_onf-tapi-nc-2.0:onf-tapi-nc-2.0#http://tail-f.com/yang/netconf-monitoring"

    prefix = "tncm"

    tncm_webui_https = 2141346136
    tncm_webui_https_ = "webui-https"
    tncm_stream = 1561687317
    tncm_stream_ = "stream"
    tncm_requested = 1485944170
    tncm_requested_ = "requested"
    tncm_replay_support = 1991147815
    tncm_replay_support_ = "replay-support"
    tncm_mode = 575893728
    tncm_mode_ = "mode"
    tncm_streams = 1043459567
    tncm_streams_ = "streams"
    tncm_operational = 4
    tncm_operational_ = "operational"
    tncm_locked_by_session = 916935714
    tncm_locked_by_session_ = "locked-by-session"
    tncm_created = 315396526
    tncm_created_ = "created"
    tncm_subscriber = 1781907650
    tncm_subscriber_ = "subscriber"
    tncm_rest_http = 972237299
    tncm_rest_http_ = "rest-http"
    tncm_none = 0
    tncm_none_ = "none"
    tncm_creator = 110891526
    tncm_creator_ = "creator"
    tncm_rest_https = 468351302
    tncm_rest_https_ = "rest-https"
    tncm_files = 1813401332
    tncm_files_ = "files"
    tncm_status = 1950810920
    tncm_status_ = "status"
    tncm_transaction_id = 1239501533
    tncm_transaction_id_ = "transaction-id"
    tncm_invalid = 1
    tncm_invalid_ = "invalid"
    tncm_snmp_udp = 246778175
    tncm_snmp_udp_ = "snmp-udp"
    tncm_transaction = 343661117
    tncm_transaction_ = "transaction"
    tncm_shared = 2
    tncm_shared_ = "shared"
    tncm_session_id = 372565948
    tncm_session_id_ = "session-id"
    tncm_context = 1600175075
    tncm_context_ = "context"
    tncm_netconf = 1
    tncm_netconf_ = "netconf"
    tncm_cli_console = 2066699732
    tncm_cli_console_ = "cli-console"
    tncm_candidate = 2
    tncm_candidate_ = "candidate"
    tncm_netconf_tcp = 75382026
    tncm_netconf_tcp_ = "netconf-tcp"
    tncm_lock = 95781586
    tncm_lock_ = "lock"
    tncm_transaction_lock = 1008558907
    tncm_transaction_lock_ = "transaction-lock"
    tncm_webui_http = 1877250135
    tncm_webui_http_ = "webui-http"
    tncm_cli = 0
    tncm_cli_ = "cli"
    tncm_cli_ssh = 1141106648
    tncm_cli_ssh_ = "cli-ssh"
    tncm_read_write = 2
    tncm_read_write_ = "read-write"
    tncm_acquired = 1582012411
    tncm_acquired_ = "acquired"
    tncm_replay_log_aged_time = 1588166633
    tncm_replay_log_aged_time_ = "replay-log-aged-time"
    tncm_read_write_obsoleted = 1
    tncm_read_write_obsoleted_ = "read_write"
    tncm_name = 1998270519
    tncm_name_ = "name"
    tncm_startup = 3
    tncm_startup_ = "startup"
    tncm_valid = 0
    tncm_valid_ = "valid"
    tncm_cli_tcp = 1883924901
    tncm_cli_tcp_ = "cli-tcp"
    tncm_file = 867066344
    tncm_file_ = "file"
    tncm_read = 0
    tncm_read_ = "read"
    tncm_start_time = 84038180
    tncm_start_time_ = "start-time"
    tncm_exclusive = 0
    tncm_exclusive_ = "exclusive"
    tncm_db = 1891760492
    tncm_db_ = "db"
    tncm_running = 1
    tncm_running_ = "running"
    tncm_id = 1279252765
    tncm_id_ = "id"
    tncm_private = 1
    tncm_private_ = "private"
    tncm_stop_time = 397011733
    tncm_stop_time_ = "stop-time"
    tncm_webui = 2
    tncm_webui_ = "webui"
    tncm_description = 202559156
    tncm_description_ = "description"
    tncm_config_mode = 1428013043
    tncm_config_mode_ = "config-mode"
    tncm_replay_log_creation_time = 896118574
    tncm_replay_log_creation_time_ = "replay-log-creation-time"
