#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/tailf-tls.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module tailf-tls.yang


class ns(object):
    hash = 1263973932

    id = "_onf-tapi-nc-2.0:onf-tapi-nc-2.0#http://tail-f.com/ns/tls"

    uri = "_onf-tapi-nc-2.0:onf-tapi-nc-2.0#http://tail-f.com/ns/tls"

    prefix = "tls"

    tls_fingerprint = 108417654
    tls_fingerprint_ = "fingerprint"
    tls_key_data = 569544672
    tls_key_data_ = "key-data"
    tls_cacert_data = 1945638180
    tls_cacert_data_ = "cacert-data"
    tls_private_key = 1861699066
    tls_private_key_ = "private-key"
    tls_cert_data = 1172136175
    tls_cert_data_ = "cert-data"
    tls_certificate = 929395308
    tls_certificate_ = "certificate"
    tls_ca_certificates = 1128068089
    tls_ca_certificates_ = "ca-certificates"
    tls_passphrase = 1150200592
    tls_passphrase_ = "passphrase"
    tls_tls_container = 1160896511
    tls_tls_container_ = "tls"
    tls_name = 1998270519
    tls_name_ = "name"
