#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/tailf-common-query.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module tailf-common-query.yang


class ns(object):
    hash = 2119206410

    id = "_onf-tapi-nc-2.0:onf-tapi-nc-2.0#http://tail-f.com/ns/common/query"

    uri = "_onf-tapi-nc-2.0:onf-tapi-nc-2.0#http://tail-f.com/ns/common/query"

    prefix = "tfcq"

    tfcq_result_type_leaf_value = 2
    tfcq_result_type_leaf_value_ = "leaf-value"
    tfcq_result_type_inline = 3
    tfcq_result_type_inline_ = "inline"
    tfcq_result_type_string = 0
    tfcq_result_type_string_ = "string"
    tfcq_result_type_path = 1
    tfcq_result_type_path_ = "path"
