#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/tailf-acm.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module tailf-acm.yang


class ns(object):
    hash = 1747215326

    id = "_onf-tapi-nc-2.0:onf-tapi-nc-2.0#http://tail-f.com/yang/acm"

    uri = "_onf-tapi-nc-2.0:onf-tapi-nc-2.0#http://tail-f.com/yang/acm"

    prefix = "tacm"

    tacm_access_operations = 1622834780
    tacm_access_operations_ = "access-operations"
    tacm_command = 36215204
    tacm_command_ = "command"
    tacm_cmd_exec_default = 311962167
    tacm_cmd_exec_default_ = "cmd-exec-default"
    tacm_context = 1600175075
    tacm_context_ = "context"
    tacm_comment = 452863039
    tacm_comment_ = "comment"
    tacm_cmdrule = 367587804
    tacm_cmdrule_ = "cmdrule"
    tacm_name = 1998270519
    tacm_name_ = "name"
    tacm_gid = 1021704153
    tacm_gid_ = "gid"
    tacm_log_if_permit = 825727182
    tacm_log_if_permit_ = "log-if-permit"
    tacm_cmd_read_default = 1843143316
    tacm_cmd_read_default_ = "cmd-read-default"
    tacm_action = 571883887
    tacm_action_ = "action"
    tacm_log_if_default_permit = 977181334
    tacm_log_if_default_permit_ = "log-if-default-permit"
