#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/tapi-photonic-media-cisco-extn.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module tapi-photonic-media-cisco-extn.yang


class ns(object):
    hash = 445288683

    id = "_onf-tapi-nc-2.0:onf-tapi-nc-2.0#http://cisco.com/yang/conc/tapi/photonic-media-extn"

    uri = "_onf-tapi-nc-2.0:onf-tapi-nc-2.0#http://cisco.com/yang/conc/tapi/photonic-media-extn"

    prefix = "tapi-photonic-media-cisco-extn"

    tapi_photonic_media_cisco_extn_measured_power_egress = 249858064
    tapi_photonic_media_cisco_extn_measured_power_egress_ = "measured-power-egress"
    tapi_photonic_media_cisco_extn_suspect_interval_flag = 1284355977
    tapi_photonic_media_cisco_extn_suspect_interval_flag_ = "suspect-interval-flag"
    tapi_photonic_media_cisco_extn_get_live_power_data = 1962834368
    tapi_photonic_media_cisco_extn_get_live_power_data_ = "get-live-power-data"
    tapi_photonic_media_cisco_extn_ots_media_channel_pm_history_data = 688136616
    tapi_photonic_media_cisco_extn_ots_media_channel_pm_history_data_ = "ots-media-channel-pm-history-data"
    tapi_photonic_media_cisco_extn_c_band = 461813499
    tapi_photonic_media_cisco_extn_c_band_ = "c-band"
    tapi_photonic_media_cisco_extn_period_end_time = 683626802
    tapi_photonic_media_cisco_extn_period_end_time_ = "period-end-time"
    tapi_photonic_media_cisco_extn_ots_media_channel = 1703572004
    tapi_photonic_media_cisco_extn_ots_media_channel_ = "ots-media-channel"
    tapi_photonic_media_cisco_extn_history_power_ingress = 1064267582
    tapi_photonic_media_cisco_extn_history_power_ingress_ = "history-power-ingress"
    tapi_photonic_media_cisco_extn_avg_power = 1925262402
    tapi_photonic_media_cisco_extn_avg_power_ = "avg-power"
    tapi_photonic_media_cisco_extn_period_start_time = 109643003
    tapi_photonic_media_cisco_extn_period_start_time_ = "period-start-time"
    tapi_photonic_media_cisco_extn_max_power = 243894008
    tapi_photonic_media_cisco_extn_max_power_ = "max-power"
    tapi_photonic_media_cisco_extn_min_power = 1395750998
    tapi_photonic_media_cisco_extn_min_power_ = "min-power"
    tapi_photonic_media_cisco_extn_power_spectral_density = 1432508232
    tapi_photonic_media_cisco_extn_power_spectral_density_ = "power-spectral-density"
    tapi_photonic_media_cisco_extn_total_power = 1322562114
    tapi_photonic_media_cisco_extn_total_power_ = "total-power"
    tapi_photonic_media_cisco_extn_history_power_egress = 1225125480
    tapi_photonic_media_cisco_extn_history_power_egress_ = "history-power-egress"
    tapi_photonic_media_cisco_extn_media_channel = 1003958371
    tapi_photonic_media_cisco_extn_media_channel_ = "media-channel"
    tapi_photonic_media_cisco_extn_live_power_data = 60521799
    tapi_photonic_media_cisco_extn_live_power_data_ = "live-power-data"
    tapi_photonic_media_cisco_extn_measured_power_ingress = 192737794
    tapi_photonic_media_cisco_extn_measured_power_ingress_ = "measured-power-ingress"
    tapi_photonic_media_cisco_extn_media_channel_pm_history_data = 520521820
    tapi_photonic_media_cisco_extn_media_channel_pm_history_data_ = "media-channel-pm-history-data"
