/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/custom-template-hook.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.cisco.nso.common.ctutils.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module custom-template-hook.yang */
public class customTemplateHook extends ConfNamespace {
    public static final int hash = 1434694904;
    public int hash() {
        return customTemplateHook.hash;
    }

    public static final String id = "http://cisco.com/yang/nso/common/custom-template-hook";
    public String id() {
        return customTemplateHook.id;
    }

    public static final String uri = "http://cisco.com/yang/nso/common/custom-template-hook";
    public String uri() {
        return customTemplateHook.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(customTemplateHook.uri);
    }

    public static final String prefix = "ct-hook";
    public String prefix() {
        return customTemplateHook.prefix;
    }

    public customTemplateHook() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _apply_custom_template = 1368777847;
    public static final String _apply_custom_template_ = "apply-custom-template";
}
