/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/custom-template-info.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.cisco.nso.common.ctutils.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module custom-template-info.yang */
public class customTemplateInfo extends ConfNamespace {
    public static final int hash = 1404061690;
    public int hash() {
        return customTemplateInfo.hash;
    }

    public static final String id = "http://cisco.com/yang/nso/common/custom-template-info";
    public String id() {
        return customTemplateInfo.id;
    }

    public static final String uri = "http://cisco.com/yang/nso/common/custom-template-info";
    public String uri() {
        return customTemplateInfo.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(customTemplateInfo.uri);
    }

    public static final String prefix = "ct-info";
    public String prefix() {
        return customTemplateInfo.prefix;
    }

    public customTemplateInfo() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _path = 1002915403;
    public static final String _path_ = "path";
    public static final int    _ct_change_netconf_notification_handler = 1315887342;
    public static final String _ct_change_netconf_notification_handler_ = "ct-change-netconf-notification-handler";
    public static final int    _custom_template_events = 1246853814;
    public static final String _custom_template_events_ = "custom-template-events";
    public static final int    _rfs_node = 1384821200;
    public static final String _rfs_node_ = "rfs-node";
    public static final int    _operation = 1037011282;
    public static final String _operation_ = "operation";
    public static final int    _template_name = 448823355;
    public static final String _template_name_ = "template-name";
    public static final int    _custom_template_info = 689905232;
    public static final String _custom_template_info_ = "custom-template-info";
    public static final int    _type = 2040883914;
    public static final String _type_ = "type";
    public static final int    _kicker_id = 1615011589;
    public static final String _kicker_id_ = "kicker-id";
    public static final int    _variables = 1837154669;
    public static final String _variables_ = "variables";
    public static final int    _tid = 805616318;
    public static final String _tid_ = "tid";
    public static final int    _ct_event_stream_enabled = 2067424105;
    public static final String _ct_event_stream_enabled_ = "ct-event-stream-enabled";
    public static final int    _name = 1998270519;
    public static final String _name_ = "name";
    public static final int    _variable = 488361488;
    public static final String _variable_ = "variable";
    public static final int    _device_variable = 1360730187;
    public static final String _device_variable_ = "device-variable";
    public static final int    _ct_actions = 2067244589;
    public static final String _ct_actions_ = "ct-actions";
    public static final String actionpoint_ct_change_netconf_notification_handler = "ct-change-netconf-notification-handler";
}
