/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/lsa-utils.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.lsautils.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module lsa-utils.yang */
public class lsaUtils extends ConfNamespace {
    public static final int hash = 1529425157;
    public int hash() {
        return lsaUtils.hash;
    }

    public static final String id = "http://cisco.com/ns/nso/lsa-utils";
    public String id() {
        return lsaUtils.id;
    }

    public static final String uri = "http://cisco.com/ns/nso/lsa-utils";
    public String uri() {
        return lsaUtils.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(lsaUtils.uri);
    }

    public static final String prefix = "lsa-utils";
    public String prefix() {
        return lsaUtils.prefix;
    }

    public lsaUtils() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _path = 1002915403;
    public static final String _path_ = "path";
    public static final int    _duplicate_device_name = 624789200;
    public static final String _duplicate_device_name_ = "duplicate-device-name";
    public static final int    _lsa = 2005676224;
    public static final String _lsa_ = "lsa";
    public static final int    _internal_dispatch_map_callback = 250607923;
    public static final String _internal_dispatch_map_callback_ = "internal-dispatch-map-callback";
    public static final int    _operation = 1037011282;
    public static final String _operation_ = "operation";
    public static final int    _device = 617911018;
    public static final String _device_ = "device";
    public static final int    _dispatch_map_update = 660612098;
    public static final String _dispatch_map_update_ = "dispatch-map-update";
    public static final int    _dispatch_map_persist_failure = 2063610731;
    public static final String _dispatch_map_persist_failure_ = "dispatch-map-persist-failure";
    public static final int    _lsa_util_alarm = 1225361582;
    public static final String _lsa_util_alarm_ = "lsa-util-alarm";
    public static final int    _role = 1297556411;
    public static final String _role_ = "role";
    public static final int    _remote_nso = 1349233645;
    public static final String _remote_nso_ = "remote-nso";
    public static final int    _detail = 984599342;
    public static final String _detail_ = "detail";
    public static final int    _dispatch_map = 1257427000;
    public static final String _dispatch_map_ = "dispatch-map";
    public static final int    _kicker_id = 1615011589;
    public static final String _kicker_id_ = "kicker-id";
    public static final int    _tid = 805616318;
    public static final String _tid_ = "tid";
    public static final int    _ned_id = 1774190712;
    public static final String _ned_id_ = "ned-id";
    public static final int    _name = 1998270519;
    public static final String _name_ = "name";
    public static final int    _remote_node = 1553725823;
    public static final String _remote_node_ = "remote-node";
    public static final int    _sync = 2047869128;
    public static final String _sync_ = "sync";
    public static final int    _success = 87922769;
    public static final String _success_ = "success";
    public static final String actionpoint_internal_dispatch_map_callback = "internal-dispatch-map-callback";
    public static final String actionpoint_lsa_utils_sync_dispatch_map = "lsa-utils-sync-dispatch-map";
}
