#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/cisco-zr-cfp-nano-plan-services.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module cisco-zr-cfp-nano-plan-services.yang


class ns(object):
    hash = 15308527

    id = "http://cisco.com/ns/nso/cfp/cisco-zr-cfp-nano-plan-services"

    uri = "http://cisco.com/ns/nso/cfp/cisco-zr-cfp-nano-plan-services"

    prefix = "cisco-zr-cfp-nano-plan-services"

    cisco_zr_cfp_nano_plan_services_config_apply = 1554681992
    cisco_zr_cfp_nano_plan_services_config_apply_ = "config-apply"
    cisco_zr_cfp_nano_plan_services_router = 532320551
    cisco_zr_cfp_nano_plan_services_router_ = "router"
