@Library("pipeline-lib@RM-Test") _

properties([buildDiscarder(logRotator(artifactDaysToKeepStr: '', artifactNumToKeepStr: '', daysToKeepStr: '', numToKeepStr: '5'))])

buildPackage {
    luxVersion = '2.3.2'
}
