#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/cisco-ron-core-fp-common.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module cisco-ron-core-fp-common.yang


class ns(object):
    hash = 1772482554

    id = "http://cisco.com/ns/nso/cfp/cisco-ron-core-fp-common"

    uri = "http://cisco.com/ns/nso/cfp/cisco-ron-core-fp-common"

    prefix = "cisco-ron-core-fp-common"

    cisco_ron_core_fp_common_path = 1002915403
    cisco_ron_core_fp_common_path_ = "path"
    cisco_ron_core_fp_common_service_cleanup_progress = 468572804
    cisco_ron_core_fp_common_service_cleanup_progress_ = "service-cleanup-progress"
